// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: LexEntry.DoNotShowMainEntryIn (rel/col CmPossibility, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>LexEntry.DoNotShowMainEntryIn</c> operation kinds.</summary>
public static class LexEntryDoNotShowMainEntryInOperationKinds
{
    public const string AddRefDoNotShowMainEntryIn = "lexical/lexEntry/addRefDoNotShowMainEntryIn";
    public const string RemoveRefDoNotShowMainEntryIn = "lexical/lexEntry/removeRefDoNotShowMainEntryIn";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefDoNotShowMainEntryIn);
        OperationKindRegistry.Register(RemoveRefDoNotShowMainEntryIn);
        OperationHandlerRegistry.Register(AddRefDoNotShowMainEntryIn, LexEntryDoNotShowMainEntryInAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefDoNotShowMainEntryIn, LexEntryDoNotShowMainEntryInRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn"/>
/// and <see cref="LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class LexEntryDoNotShowMainEntryInMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn"/>: resolves the
/// referenced ICmPossibility and adds it to <c>lexEntry.DoNotShowMainEntryInRC</c> (a no-op if already
/// present).</summary>
public static class LexEntryDoNotShowMainEntryInAddRefLowering
{
    public static void Apply(LcmCache cache, ILexEntry lexEntry, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ICmPossibility>(
            cache, lexEntry.DoNotShowMainEntryInRC, memberId, LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn);
}

/// <summary>Lowers <see cref="LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn"/>: resolves the
/// referenced ICmPossibility and removes it from <c>lexEntry.DoNotShowMainEntryInRC</c> (a no-op if
/// absent).</summary>
public static class LexEntryDoNotShowMainEntryInRemoveRefLowering
{
    public static void Apply(LcmCache cache, ILexEntry lexEntry, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ICmPossibility>(
            cache, lexEntry.DoNotShowMainEntryInRC, memberId, LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn"/> operation.</summary>
internal sealed class LexEntryDoNotShowMainEntryInAddRefHandler : IOperationHandler
{
    internal static readonly LexEntryDoNotShowMainEntryInAddRefHandler Instance = new();
    private LexEntryDoNotShowMainEntryInAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn}' requires 'after'.");
        }

        var memberId = LexEntryDoNotShowMainEntryInMemberPayload.Parse(after, LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn);

        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntry.DoNotShowMainEntryInRC);
        LexEntryDoNotShowMainEntryInAddRefLowering.Apply(cache, lexEntry, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntry.DoNotShowMainEntryInRC);

        return new ExpectedEffect(id, SnapshotFields.LexEntryDoNotShowMainEntryIn, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDoNotShowMainEntryInOperationKinds.AddRefDoNotShowMainEntryIn);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntry.DoNotShowMainEntryInRC);
        return new ExpectedEffect(id, SnapshotFields.LexEntryDoNotShowMainEntryIn, current, current);
    }
}

/// <summary>The <see cref="LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn"/> counterpart to
/// <see cref="LexEntryDoNotShowMainEntryInAddRefHandler"/>.</summary>
internal sealed class LexEntryDoNotShowMainEntryInRemoveRefHandler : IOperationHandler
{
    internal static readonly LexEntryDoNotShowMainEntryInRemoveRefHandler Instance = new();
    private LexEntryDoNotShowMainEntryInRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn}' requires 'after'.");
        }

        var memberId = LexEntryDoNotShowMainEntryInMemberPayload.Parse(after, LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn);

        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntry.DoNotShowMainEntryInRC);
        LexEntryDoNotShowMainEntryInRemoveRefLowering.Apply(cache, lexEntry, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntry.DoNotShowMainEntryInRC);

        return new ExpectedEffect(id, SnapshotFields.LexEntryDoNotShowMainEntryIn, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDoNotShowMainEntryInOperationKinds.RemoveRefDoNotShowMainEntryIn);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntry.DoNotShowMainEntryInRC);
        return new ExpectedEffect(id, SnapshotFields.LexEntryDoNotShowMainEntryIn, current, current);
    }
}
