// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoForm.MorphType (rel/atomic MoMorphType, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoForm.MorphType</c> operation kinds.</summary>
public static class MoFormMorphTypeOperationKinds
{
    public const string SetMorphType = "grammar/moForm/setMorphType";
    public const string ClearMorphType = "grammar/moForm/clearMorphType";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetMorphType);
        OperationKindRegistry.Register(ClearMorphType);
        OperationHandlerRegistry.Register(SetMorphType, MoFormMorphTypeSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearMorphType, MoFormMorphTypeClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoFormMorphTypeOperationKinds.SetMorphType"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoFormMorphTypeSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoFormMorphTypeOperationKinds.SetMorphType);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoFormMorphTypeOperationKinds.SetMorphType);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoFormMorphTypeOperationKinds.SetMorphType);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoFormMorphTypeOperationKinds.ClearMorphType"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoFormMorphTypeClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoFormMorphTypeOperationKinds.ClearMorphType);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoFormMorphTypeOperationKinds.ClearMorphType);
    }
}

/// <summary>Lowers <see cref="MoFormMorphTypeOperationKinds.SetMorphType"/>: resolves the
/// referenced IMoMorphType and assigns it to <c>moForm.MorphTypeRA</c>.</summary>
public static class MoFormMorphTypeSetLowering
{
    public static void Apply(LcmCache cache, IMoForm moForm, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IMoMorphType>(
            cache, value => moForm.MorphTypeRA = value, refId, MoFormMorphTypeOperationKinds.SetMorphType);
}

/// <summary>Lowers <see cref="MoFormMorphTypeOperationKinds.ClearMorphType"/>: detaches
/// <c>moForm.MorphTypeRA</c>.</summary>
public static class MoFormMorphTypeClearLowering
{
    public static void Apply(IMoForm moForm) =>
        ReferenceFieldLowering.ApplyClear<IMoMorphType>(value => moForm.MorphTypeRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoFormMorphTypeOperationKinds.SetMorphType"/> operation.</summary>
internal sealed class MoFormMorphTypeSetHandler : IOperationHandler
{
    internal static readonly MoFormMorphTypeSetHandler Instance = new();
    private MoFormMorphTypeSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoFormMorphTypeOperationKinds.SetMorphType}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoFormMorphTypeOperationKinds.SetMorphType}' requires 'after'.");
        }

        var refId = MoFormMorphTypeSetPayload.Parse(after);

        var (id, moForm) = TargetResolution.Resolve<IMoForm>(cache, operation, MoFormMorphTypeOperationKinds.SetMorphType);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moForm.MorphTypeRA);
        MoFormMorphTypeSetLowering.Apply(cache, moForm, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moForm.MorphTypeRA);

        return new ExpectedEffect(id, SnapshotFields.MoFormMorphType, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moForm) = TargetResolution.Resolve<IMoForm>(cache, operation, MoFormMorphTypeOperationKinds.SetMorphType);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moForm.MorphTypeRA);
        return new ExpectedEffect(id, SnapshotFields.MoFormMorphType, current, current);
    }
}

/// <summary>The <see cref="MoFormMorphTypeOperationKinds.ClearMorphType"/> counterpart to
/// <see cref="MoFormMorphTypeSetHandler"/>.</summary>
internal sealed class MoFormMorphTypeClearHandler : IOperationHandler
{
    internal static readonly MoFormMorphTypeClearHandler Instance = new();
    private MoFormMorphTypeClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoFormMorphTypeOperationKinds.ClearMorphType}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoFormMorphTypeOperationKinds.ClearMorphType}' requires 'after'.");
        }

        MoFormMorphTypeClearPayload.Parse(after);

        var (id, moForm) = TargetResolution.Resolve<IMoForm>(cache, operation, MoFormMorphTypeOperationKinds.ClearMorphType);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moForm.MorphTypeRA);
        MoFormMorphTypeClearLowering.Apply(moForm);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moForm.MorphTypeRA);

        return new ExpectedEffect(id, SnapshotFields.MoFormMorphType, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moForm) = TargetResolution.Resolve<IMoForm>(cache, operation, MoFormMorphTypeOperationKinds.ClearMorphType);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moForm.MorphTypeRA);
        return new ExpectedEffect(id, SnapshotFields.MoFormMorphType, current, current);
    }
}
