// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, Kind=basic, Verbs=set|clear, DeclaringClass=MoCompoundRule):
//   MoCompoundRule.Disabled (Boolean).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IMoCompoundRule</c>'s in-scope basic <c>set|clear</c> fields into the
/// LibLCM-free <see cref="ObjectSnapshot"/> projection.
/// </summary>
public static class MoCompoundRuleSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IMoCompoundRule moCompoundRule)
    {
        var canonicalId = CanonicalId.FromGuid(moCompoundRule.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        fields[SnapshotFields.MoCompoundRuleDisabled] = BooleanFieldAlternatives.ToAlternatives(moCompoundRule.Disabled);

        return new ObjectSnapshot(canonicalId, fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName,
        IReadOnlyDictionary<string, string> alternatives)
    {
        if (alternatives.Count > 0)
            fields[fieldName] = alternatives;
    }
}
