// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, Kind=basic, Verbs=set|clear, DeclaringClass=MoInflAffixTemplate):
//   MoInflAffixTemplate.Final (Boolean), MoInflAffixTemplate.Disabled (Boolean).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IMoInflAffixTemplate</c>'s in-scope basic <c>set|clear</c> fields into the
/// LibLCM-free <see cref="ObjectSnapshot"/> projection.
/// </summary>
public static class MoInflAffixTemplateSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate)
    {
        var canonicalId = CanonicalId.FromGuid(moInflAffixTemplate.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        fields[SnapshotFields.MoInflAffixTemplateFinal] = BooleanFieldAlternatives.ToAlternatives(moInflAffixTemplate.Final);
        fields[SnapshotFields.MoInflAffixTemplateDisabled] = BooleanFieldAlternatives.ToAlternatives(moInflAffixTemplate.Disabled);

        return new ObjectSnapshot(canonicalId, fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName,
        IReadOnlyDictionary<string, string> alternatives)
    {
        if (alternatives.Count > 0)
            fields[fieldName] = alternatives;
    }
}
