// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, DeclaringClass=MoInflAffMsa): MoInflAffMsa.PartOfSpeech (PartOfSpeech, rel/atomic), MoInflAffMsa.Slots (MoInflAffixSlot, rel/col), MoInflAffMsa.FromProdRestrict (CmPossibility, rel/col).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IMoInflAffMsa</c>'s in-scope slice-2 relation/owning-atomic fields into
/// the LibLCM-free <see cref="ObjectSnapshot"/> projection. Sibling to the slice-1
/// <c>MoInflAffMsaSnapshotter</c>; see this file's own remarks (RelationsSnapshotterEmitter.cs,
/// SIL.Motif.Generator) for why the two are not merged.
/// </summary>
public static class MoInflAffMsaRelationsSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IMoInflAffMsa moInflAffMsa)
    {
        var canonicalId = CanonicalId.FromGuid(moInflAffMsa.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        AddIfPopulated(fields, SnapshotFields.MoInflAffMsaPartOfSpeech, ReferenceFieldSnapshotting.ReadAlternatives(moInflAffMsa.PartOfSpeechRA));
        AddIfPopulated(fields, SnapshotFields.MoInflAffMsaSlots, ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.SlotsRC));
        AddIfPopulated(fields, SnapshotFields.MoInflAffMsaFromProdRestrict, ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.FromProdRestrictRC));

        return new ObjectSnapshot(canonicalId, fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName,
        IReadOnlyDictionary<string, string> alternatives)
    {
        if (alternatives.Count > 0)
            fields[fieldName] = alternatives;
    }
}
