// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, DeclaringClass=MoStemMsa): MoStemMsa.PartOfSpeech (PartOfSpeech, rel/atomic), MoStemMsa.InflectionClass (MoInflClass, rel/atomic), MoStemMsa.ProdRestrict (CmPossibility, rel/col), MoStemMsa.FromPartsOfSpeech (PartOfSpeech, rel/col), MoStemMsa.Slots (MoInflAffixSlot, rel/col).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IMoStemMsa</c>'s in-scope slice-2 relation/owning-atomic fields into
/// the LibLCM-free <see cref="ObjectSnapshot"/> projection. Sibling to the slice-1
/// <c>MoStemMsaSnapshotter</c>; see this file's own remarks (RelationsSnapshotterEmitter.cs,
/// SIL.Motif.Generator) for why the two are not merged.
/// </summary>
public static class MoStemMsaRelationsSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IMoStemMsa moStemMsa)
    {
        var canonicalId = CanonicalId.FromGuid(moStemMsa.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        AddIfPopulated(fields, SnapshotFields.MoStemMsaPartOfSpeech, ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.PartOfSpeechRA));
        AddIfPopulated(fields, SnapshotFields.MoStemMsaInflectionClass, ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.InflectionClassRA));
        AddIfPopulated(fields, SnapshotFields.MoStemMsaProdRestrict, ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.ProdRestrictRC));
        AddIfPopulated(fields, SnapshotFields.MoStemMsaFromPartsOfSpeech, ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.FromPartsOfSpeechRC));
        AddIfPopulated(fields, SnapshotFields.MoStemMsaSlots, ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.SlotsRC));

        return new ObjectSnapshot(canonicalId, fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName,
        IReadOnlyDictionary<string, string> alternatives)
    {
        if (alternatives.Count > 0)
            fields[fieldName] = alternatives;
    }
}
