// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, DeclaringClass=PartOfSpeech): PartOfSpeech.DefaultInflectionClass (MoInflClass, rel/atomic).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IPartOfSpeech</c>'s in-scope MOT-4 slice-2 relation/owning-atomic fields into
/// the LibLCM-free <see cref="ObjectSnapshot"/> projection. Sibling to the slice-1
/// <c>PartOfSpeechSnapshotter</c>; see this file's own remarks (RelationsSnapshotterEmitter.cs,
/// SIL.Motif.Generator) for why the two are not merged.
/// </summary>
public static class PartOfSpeechRelationsSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IPartOfSpeech partOfSpeech)
    {
        var canonicalId = CanonicalId.FromGuid(partOfSpeech.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        AddIfPopulated(fields, SnapshotFields.PartOfSpeechDefaultInflectionClass, ReferenceFieldSnapshotting.ReadAlternatives(partOfSpeech.DefaultInflectionClassRA));

        return new ObjectSnapshot(canonicalId, fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName,
        IReadOnlyDictionary<string, string> alternatives)
    {
        if (alternatives.Count > 0)
            fields[fieldName] = alternatives;
    }
}
