using SIL.Motif.Generator.Checks;
using SIL.Motif.Generator.Derivation;
using SIL.Motif.Generator.Join;
using SIL.Motif.Generator.Model;

namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits <c>Operations/Generated2/LexEntryLexemeForm.g.cs</c>: <c>LexEntry.LexemeForm</c>'s
/// <c>create</c>/<c>delete</c> kinds, the one field in this slice
/// needing hand-written logic no template can produce mechanically: entity-construction validity for
/// <c>create</c> is not emitted, because the manifest cannot know it.
/// </summary>
/// <remarks>
/// <para>
/// <b>What is still derived, not hand-typed.</b> The kind strings' <c>group</c> and <c>construct</c>
/// segments come from the same <see cref="GroupDerivation"/>/<see cref="ConstructDerivation"/>/
/// <see cref="KindNameDerivation"/> every other field uses — <c>lexical/lexEntry/createLexemeForm</c>,
/// <c>...deleteLexemeForm</c> — so a future rename of <c>LexEntry</c>'s group or construct rule would
/// still flow through here, exactly as for a mechanical field. <see cref="AbstractClassRule"/> is also
/// exercised for real: <c>LexEntry.LexemeForm</c>'s <c>Sig</c> is <c>MoForm</c>, which is
/// <c>abstract="true"</c>, so this method must pass a <em>concrete</em> class to the check rather than
/// the field's raw <c>Sig</c> — the check would (correctly) throw otherwise. Which concrete class is
/// exactly the fact the manifest cannot supply, so it is asserted here as the hand-authored decision
/// this field needs (ADR 0023 decision 2), and the check proves that decision is a legal one before any
/// code is emitted.
/// </para>
/// <para>
/// <b>What is not derived.</b> The payload shape (<c>morphType</c>/<c>ws</c>/<c>text</c>), the
/// morph-type-to-concrete-class table, and the create/delete lowering bodies are fixed, hand-modelled
/// content — there is exactly one field of this shape in this slice, so a general template would be
/// speculative generality for a family of one. The runtime logic those bodies call
/// (<c>SIL.Motif.Runner.Operations.MoFormConcreteClassSelection</c>) is permanent, checked-in,
/// hand-written Runner infrastructure, analogous to <c>MultiAlternativesFieldLowering</c> — this
/// emitter only reproduces the wiring around it.
/// </para>
/// </remarks>
public static class LexEntryLexemeFormEmitter
{
    /// <summary>The concrete class the kinds are checked against; the remarks say why not <c>MoForm</c>.</summary>
    private const string ConcreteClassForAbstractCheck = "MoStemAllomorph";

    public static string Render(JoinedRow lexemeFormRow, IReadOnlyList<ModelClass> classes)
    {
        if (lexemeFormRow.DeclaringClass != "LexEntry" || lexemeFormRow.FieldName != "LexemeForm")
        {
            throw new GeneratorException(
                $"LexEntryLexemeFormEmitter only knows how to render LexEntry.LexemeForm, not " +
                $"{lexemeFormRow.DeclaringClass}.{lexemeFormRow.FieldName}.");
        }

        var concreteClass = classes.SingleOrDefault(c => c.Id == ConcreteClassForAbstractCheck)
            ?? throw new GeneratorException(
                $"'{ConcreteClassForAbstractCheck}' was not found in the parsed model — " +
                "LexEntryLexemeFormEmitter's hand-chosen concrete class must exist in MasterLCModel.xml.");

        // Runs before anything is emitted: the rule accepts this class and would reject the raw abstract Sig.
        AbstractClassRule.Check(lexemeFormRow.DeclaringClass, lexemeFormRow.FieldName, "create", concreteClass);
        AbstractClassRule.Check(lexemeFormRow.DeclaringClass, lexemeFormRow.FieldName, "delete", concreteClass);

        var group = GroupDerivation.Derive(lexemeFormRow.DeclaringClass);
        var construct = ConstructDerivation.Derive(lexemeFormRow.DeclaringClass);
        var createKind = KindNameDerivation.DeriveOne(group, construct, "create", lexemeFormRow.FieldName);
        var deleteKind = KindNameDerivation.DeriveOne(group, construct, "delete", lexemeFormRow.FieldName);

        return Template
            .Replace("__CREATEKIND__", createKind)
            .Replace("__DELETEKIND__", deleteKind);
    }

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit the kind names, payload shape, or wiring below. Rerun
        //   `dotnet run --project src/SIL.Motif.Generator -- emit` after a manifest or MasterLCModel.xml
        //   change, and check in the result.
        //
        //   Source: LexEntry.LexemeForm (owning/atomic MoForm, Verbs=create|delete).
        //
        //   UNLIKE every other file in this directory, the *body* of the lowering below is hand-written, not
        //   templated from the field's shape alone -- MoForm is abstract="true" (ADR 0023 decision 2), so a
        //   `create` cannot instantiate it, and which concrete class to build (MoStemAllomorph vs
        //   MoAffixAllomorph) is a fact about FieldWorks' seeded morph-type list that MasterLCModel.xml does
        //   not carry ("not emitted, because the manifest cannot know it"). That
        //   logic lives in the permanent, hand-maintained SIL.Motif.Runner.Operations.MoFormConcreteClassSelection,
        //   referenced by name below rather than duplicated here. See Emit/LexEntryLexemeFormEmitter.cs
        //   (SIL.Motif.Generator) for the generator-side rationale.
        // </auto-generated>
        using System;
        using System.Collections.Generic;
        using System.Runtime.CompilerServices;
        using System.Text.Json;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Contract.Model;
        using SIL.Motif.Contract.Parsing;
        using SIL.Motif.Model.Effects;
        using SIL.Motif.Model.Snapshot;
        using SIL.Motif.Runner.Snapshotting;
        using SIL.LCModel;

        namespace SIL.Motif.Runner.Operations;

        /// <summary>Names the two <c>LexEntry.LexemeForm</c> operation kinds.</summary>
        public static class LexEntryLexemeFormOperationKinds
        {
            public const string CreateLexemeForm = "__CREATEKIND__";
            public const string DeleteLexemeForm = "__DELETEKIND__";

            [ModuleInitializer]
            internal static void Register()
            {
                OperationKindRegistry.Register(CreateLexemeForm);
                OperationKindRegistry.Register(DeleteLexemeForm);
                OperationHandlerRegistry.Register(CreateLexemeForm, LexEntryLexemeFormCreateHandler.Instance);
                OperationHandlerRegistry.Register(DeleteLexemeForm, LexEntryLexemeFormDeleteHandler.Instance);
            }
        }

        /// <summary>
        /// The <c>after</c> payload for <see cref="LexEntryLexemeFormOperationKinds.CreateLexemeForm"/>:
        /// <c>{ "morphType": "&lt;canonicalId&gt;", "ws": "...", "text": "..." }</c>. Closed: any other
        /// property is rejected. All three are required -- this <em>is</em> the hand-written entity-construction
        /// validity ADR 0014 says the manifest cannot supply: a lexeme form with no morph type is not a
        /// usable one, so <c>create</c> does not offer a two-step "create empty, set morph type later" path.
        /// </summary>
        public static class LexEntryLexemeFormCreatePayload
        {
            private static readonly string[] AllowedProperties = { "morphType", "ws", "text" };

            public static (CanonicalId MorphType, string Ws, string Text) Parse(JsonElement after)
            {
                ClosedPayloadParsing.RequireObject(after, LexEntryLexemeFormOperationKinds.CreateLexemeForm);
                ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, LexEntryLexemeFormOperationKinds.CreateLexemeForm);

                var morphType = ClosedPayloadParsing.GetRequiredCanonicalId(after, "morphType", LexEntryLexemeFormOperationKinds.CreateLexemeForm);
                var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", LexEntryLexemeFormOperationKinds.CreateLexemeForm);
                var text = ClosedPayloadParsing.GetRequiredString(after, "text", LexEntryLexemeFormOperationKinds.CreateLexemeForm);

                return (morphType, ws, text);
            }
        }

        /// <summary>The <c>after</c> payload for <see cref="LexEntryLexemeFormOperationKinds.DeleteLexemeForm"/>:
        /// <c>{}</c>. Closed: any property at all is rejected -- an entry has at most one lexeme form, so there
        /// is nothing left to disambiguate once the target entry is known.</summary>
        public static class LexEntryLexemeFormDeletePayload
        {
            private static readonly string[] AllowedProperties = Array.Empty<string>();

            public static void Parse(JsonElement after)
            {
                ClosedPayloadParsing.RequireObject(after, LexEntryLexemeFormOperationKinds.DeleteLexemeForm);
                ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, LexEntryLexemeFormOperationKinds.DeleteLexemeForm);
            }
        }

        /// <summary>
        /// Lowers <see cref="LexEntryLexemeFormOperationKinds.CreateLexemeForm"/>: builds a concrete
        /// <c>MoStemAllomorph</c> or <c>MoAffixAllomorph</c> (never a bare, abstract <c>MoForm</c>) with the
        /// authored identity, morph type, and initial written form, then assigns it into <c>entry.LexemeFormOA</c>.
        /// </summary>
        /// <remarks>
        /// <para>
        /// <b>Never delete-plus-create</b> (docs/change-set-contract.md's change-class contract): this performs
        /// exactly one owning-atomic assignment. If the slot is already occupied, that single assignment is
        /// LibLCM's own "create-into-occupied, with implicit detach" semantics
        /// (docs/api-surface-layer1.md, "Totality: owning/atomic replacement resolved") -- verified empirically
        /// against a real occupied <c>LexemeFormOA</c> slot in <c>TestLangProj</c> rather than assumed. What was
        /// NOT verified to hold is the contract's further claim that the displaced occupant survives as an
        /// orphan needing an explicit disclosure/delete decision (docs/change-set-contract.md, "Owning-atomic
        /// replacement"): in this LibLCM version the previous occupant is fully removed from the object
        /// repository by the assignment itself (confirmed by <c>MoStemAllomorph</c>/total <c>CmObject</c> counts
        /// being unchanged across a replace-one-add-one, and by the old GUID no longer resolving at all) --
        /// there is no surviving orphan for this slice to disclose or refuse over.
        /// </para>
        /// <para>Must run inside an already-open unit of work (docs/adr/0006, decision 5).</para>
        /// </remarks>
        public static class LexEntryLexemeFormCreateLowering
        {
            public static IMoForm Apply(
                LcmCache cache, ILexEntry entry, Guid formId, CanonicalId morphTypeId, string writingSystemTag, string text)
            {
                var morphType = ReferenceFieldLowering.Resolve<IMoMorphType>(
                    cache, morphTypeId, LexEntryLexemeFormOperationKinds.CreateLexemeForm);
                var concreteClass = MoFormConcreteClassSelection.ClassFor(
                    morphType, LexEntryLexemeFormOperationKinds.CreateLexemeForm);
                var newForm = MoFormConcreteClassSelection.Create(cache, concreteClass, formId);

                newForm.MorphTypeRA = morphType;
                MultiAlternativesFieldLowering.ApplySet(
                    cache, newForm.Form, writingSystemTag, text, LexEntryLexemeFormOperationKinds.CreateLexemeForm);

                entry.LexemeFormOA = newForm;

                return newForm;
            }
        }

        /// <summary>
        /// Lowers <see cref="LexEntryLexemeFormOperationKinds.DeleteLexemeForm"/>: removes the entry's current
        /// lexeme form through LibLCM's native ownership cascade (<c>ICmObject.Delete</c>). Requires a form to
        /// be present -- there is nothing to name a "delete" over an already-empty slot.
        /// </summary>
        public static class LexEntryLexemeFormDeleteLowering
        {
            public static void Apply(ILexEntry entry)
            {
                if (entry.LexemeFormOA is not { } form)
                {
                    throw new InvalidOperationException(
                        $"'{LexEntryLexemeFormOperationKinds.DeleteLexemeForm}' operation: entry '{entry.Guid}' " +
                        "has no lexeme form to delete.");
                }

                form.Delete();
            }
        }

        /// <summary>Resolves, snapshots, lowers, and re-snapshots one
        /// <see cref="LexEntryLexemeFormOperationKinds.CreateLexemeForm"/> operation.</summary>
        internal sealed class LexEntryLexemeFormCreateHandler : IOperationHandler
        {
            internal static readonly LexEntryLexemeFormCreateHandler Instance = new();
            private LexEntryLexemeFormCreateHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{LexEntryLexemeFormOperationKinds.CreateLexemeForm}' requires 'target'.");
                }

                if (operation.EntityId is not { } entityId)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{LexEntryLexemeFormOperationKinds.CreateLexemeForm}' requires 'entityId'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{LexEntryLexemeFormOperationKinds.CreateLexemeForm}' requires 'after'.");
                }

                var (morphTypeId, ws, text) = LexEntryLexemeFormCreatePayload.Parse(after);

                var (id, entry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryLexemeFormOperationKinds.CreateLexemeForm);
                touchedTargets.Add(id);

                var before = ReferenceFieldSnapshotting.ReadAlternatives(entry.LexemeFormOA);
                LexEntryLexemeFormCreateLowering.Apply(cache, entry, entityId.ToGuid(), morphTypeId, ws, text);
                var afterValue = ReferenceFieldAlternatives.ToAlternatives(entityId);

                return new ExpectedEffect(id, SnapshotFields.LexEntryLexemeForm, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, entry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryLexemeFormOperationKinds.CreateLexemeForm);
                var current = ReferenceFieldSnapshotting.ReadAlternatives(entry.LexemeFormOA);
                return new ExpectedEffect(id, SnapshotFields.LexEntryLexemeForm, current, current);
            }
        }

        /// <summary>The <see cref="LexEntryLexemeFormOperationKinds.DeleteLexemeForm"/> counterpart to
        /// <see cref="LexEntryLexemeFormCreateHandler"/>.</summary>
        internal sealed class LexEntryLexemeFormDeleteHandler : IOperationHandler
        {
            internal static readonly LexEntryLexemeFormDeleteHandler Instance = new();
            private LexEntryLexemeFormDeleteHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{LexEntryLexemeFormOperationKinds.DeleteLexemeForm}' requires 'target'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{LexEntryLexemeFormOperationKinds.DeleteLexemeForm}' requires 'after'.");
                }

                LexEntryLexemeFormDeletePayload.Parse(after);

                var (id, entry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryLexemeFormOperationKinds.DeleteLexemeForm);
                touchedTargets.Add(id);

                var before = ReferenceFieldSnapshotting.ReadAlternatives(entry.LexemeFormOA);
                LexEntryLexemeFormDeleteLowering.Apply(entry);
                var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(entry.LexemeFormOA);

                return new ExpectedEffect(id, SnapshotFields.LexEntryLexemeForm, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, entry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryLexemeFormOperationKinds.DeleteLexemeForm);
                var current = ReferenceFieldSnapshotting.ReadAlternatives(entry.LexemeFormOA);
                return new ExpectedEffect(id, SnapshotFields.LexEntryLexemeForm, current, current);
            }
        }

        """;
}
