namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits one <c>Operations/Generated2/{DeclaringClass}{FieldName}.g.cs</c> file for a <c>rel/col</c> or
/// <c>rel/seq</c> field's <c>addRef</c>/<c>removeRef</c> kinds, via
/// <see cref="Runner.Operations.ReferenceCollectionFieldLowering"/>.
/// </summary>
/// <remarks>
/// <c>move</c> is deliberately not emitted for a <c>rel/seq</c> field
/// (<c>LexEntry.DialectLabels</c> is the one in this slice). Placement uses identity-relative anchors
/// (ADR 0026; the Change Set contract's ordered-data rules), and nothing in the Runner lowers
/// <see cref="Contract.Model.OperationEnvelope.Placement"/> into an actual LibLCM reorder yet — the
/// Contract kernel only ever reads it to feed the intent digest
/// (<c>IntentProjectionWriter</c>) — so building a real <c>move</c> kind here would be new,
/// unreviewed machinery riding along with a mechanical field-emission slice, not a template
/// instantiation of something already proven. Also live: ADR 0023's own consequences record that
/// <c>sequence/move</c> "does not fit <c>group/construct/verb</c> at all", and whether a field-agnostic
/// placement primitive belongs alongside per-field kinds is a still-open architectural question this
/// emitter does not decide. <c>addRef</c>/<c>removeRef</c> are unaffected: they
/// are unordered membership changes regardless of the field's cardinality.
/// </remarks>
public static class ReferenceCollectionFieldEmitter
{
    public static string Render(ReferenceCollectionFieldSpec spec)
    {
        var prefix = spec.SnapshotFieldConstant;
        var varName = spec.Construct;

        return Template
            .Replace("__PREFIX__", prefix)
            .Replace("__DECLARINGCLASS__", spec.DeclaringClass)
            .Replace("__FIELDNAME__", spec.FieldName)
            .Replace("__SIG__", spec.Sig)
            .Replace("__CARD__", spec.Card.ToString().ToLowerInvariant())
            .Replace("__ADDKIND__", spec.AddRefKind)
            .Replace("__REMOVEKIND__", spec.RemoveRefKind)
            .Replace("__TARGETIFACE__", spec.TargetInterface)
            .Replace("__REFIFACE__", spec.RefInterface)
            .Replace("__ACCESSOR__", spec.AccessorPropertyName)
            .Replace("__VAR__", varName)
            .Replace("__SNAPSHOTFIELD__", "SnapshotFields." + prefix);
    }

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        //
        //   Source: __DECLARINGCLASS__.__FIELDNAME__ (rel/__CARD__ __SIG__, addRef|removeRef emitted;
        //   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
        // </auto-generated>
        using System;
        using System.Collections.Generic;
        using System.Runtime.CompilerServices;
        using System.Text.Json;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Contract.Model;
        using SIL.Motif.Contract.Parsing;
        using SIL.Motif.Model.Effects;
        using SIL.Motif.Model.Snapshot;
        using SIL.Motif.Runner.Snapshotting;
        using SIL.LCModel;

        namespace SIL.Motif.Runner.Operations;

        /// <summary>Names the two <c>__DECLARINGCLASS__.__FIELDNAME__</c> operation kinds.</summary>
        public static class __PREFIX__OperationKinds
        {
            public const string AddRef__FIELDNAME__ = "__ADDKIND__";
            public const string RemoveRef__FIELDNAME__ = "__REMOVEKIND__";

            [ModuleInitializer]
            internal static void Register()
            {
                OperationKindRegistry.Register(AddRef__FIELDNAME__);
                OperationKindRegistry.Register(RemoveRef__FIELDNAME__);
                OperationHandlerRegistry.Register(AddRef__FIELDNAME__, __PREFIX__AddRefHandler.Instance);
                OperationHandlerRegistry.Register(RemoveRef__FIELDNAME__, __PREFIX__RemoveRefHandler.Instance);
            }
        }

        /// <summary>The <c>after</c> payload for both <see cref="__PREFIX__OperationKinds.AddRef__FIELDNAME__"/>
        /// and <see cref="__PREFIX__OperationKinds.RemoveRef__FIELDNAME__"/>:
        /// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
        public static class __PREFIX__MemberPayload
        {
            private static readonly string[] AllowedProperties = { "member" };

            public static CanonicalId Parse(JsonElement after, string kind)
            {
                ClosedPayloadParsing.RequireObject(after, kind);
                ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

                return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
            }
        }

        /// <summary>Lowers <see cref="__PREFIX__OperationKinds.AddRef__FIELDNAME__"/>: resolves the
        /// referenced __REFIFACE__ and adds it to <c>__VAR__.__ACCESSOR__</c> (a no-op if already
        /// present).</summary>
        public static class __PREFIX__AddRefLowering
        {
            public static void Apply(LcmCache cache, __TARGETIFACE__ __VAR__, CanonicalId memberId) =>
                ReferenceCollectionFieldLowering.ApplyAddRef<__REFIFACE__>(
                    cache, __VAR__.__ACCESSOR__, memberId, __PREFIX__OperationKinds.AddRef__FIELDNAME__);
        }

        /// <summary>Lowers <see cref="__PREFIX__OperationKinds.RemoveRef__FIELDNAME__"/>: resolves the
        /// referenced __REFIFACE__ and removes it from <c>__VAR__.__ACCESSOR__</c> (a no-op if
        /// absent).</summary>
        public static class __PREFIX__RemoveRefLowering
        {
            public static void Apply(LcmCache cache, __TARGETIFACE__ __VAR__, CanonicalId memberId) =>
                ReferenceCollectionFieldLowering.ApplyRemoveRef<__REFIFACE__>(
                    cache, __VAR__.__ACCESSOR__, memberId, __PREFIX__OperationKinds.RemoveRef__FIELDNAME__);
        }

        /// <summary>Resolves, snapshots, lowers, and re-snapshots one
        /// <see cref="__PREFIX__OperationKinds.AddRef__FIELDNAME__"/> operation.</summary>
        internal sealed class __PREFIX__AddRefHandler : IOperationHandler
        {
            internal static readonly __PREFIX__AddRefHandler Instance = new();
            private __PREFIX__AddRefHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.AddRef__FIELDNAME__}' requires 'target'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.AddRef__FIELDNAME__}' requires 'after'.");
                }

                var memberId = __PREFIX__MemberPayload.Parse(after, __PREFIX__OperationKinds.AddRef__FIELDNAME__);

                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.AddRef__FIELDNAME__);
                touchedTargets.Add(id);

                var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(__VAR__.__ACCESSOR__);
                __PREFIX__AddRefLowering.Apply(cache, __VAR__, memberId);
                var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(__VAR__.__ACCESSOR__);

                return new ExpectedEffect(id, __SNAPSHOTFIELD__, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.AddRef__FIELDNAME__);
                var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(__VAR__.__ACCESSOR__);
                return new ExpectedEffect(id, __SNAPSHOTFIELD__, current, current);
            }
        }

        /// <summary>The <see cref="__PREFIX__OperationKinds.RemoveRef__FIELDNAME__"/> counterpart to
        /// <see cref="__PREFIX__AddRefHandler"/>.</summary>
        internal sealed class __PREFIX__RemoveRefHandler : IOperationHandler
        {
            internal static readonly __PREFIX__RemoveRefHandler Instance = new();
            private __PREFIX__RemoveRefHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.RemoveRef__FIELDNAME__}' requires 'target'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.RemoveRef__FIELDNAME__}' requires 'after'.");
                }

                var memberId = __PREFIX__MemberPayload.Parse(after, __PREFIX__OperationKinds.RemoveRef__FIELDNAME__);

                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.RemoveRef__FIELDNAME__);
                touchedTargets.Add(id);

                var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(__VAR__.__ACCESSOR__);
                __PREFIX__RemoveRefLowering.Apply(cache, __VAR__, memberId);
                var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(__VAR__.__ACCESSOR__);

                return new ExpectedEffect(id, __SNAPSHOTFIELD__, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.RemoveRef__FIELDNAME__);
                var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(__VAR__.__ACCESSOR__);
                return new ExpectedEffect(id, __SNAPSHOTFIELD__, current, current);
            }
        }

        """;
}
