namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits one <c>Snapshotting/Generated2/{DeclaringClass}RelationsSnapshotter.g.cs</c> file: reads every
/// in-scope slice-2 field of one declaring class (<c>rel/atomic</c>, <c>rel/col</c>/<c>rel/seq</c>,
/// and <c>LexEntry.LexemeForm</c>'s own owning/atomic slot) into an <see cref="Model.Snapshot.ObjectSnapshot"/>.
/// </summary>
/// <remarks>
/// A separate type from slice 1's checked-in <c>{DeclaringClass}Snapshotter.g.cs</c>
/// (<see cref="SnapshotterEmitter"/>) rather than an addition to it: slice 1's emitter and its byte-identity
/// drift guard (<c>GeneratedCatalogWriterTests</c>, <c>GeneratedFilesAreUpToDateTests</c>) hard-assert an
/// exact file/kind count that predates this slice, so widening that file would break an existing test this
/// task must not touch. Each generated field handler only ever reads back its own field via
/// <c>TryGetValue</c>, never a full merged snapshot, so two sibling snapshotter classes per class cost
/// nothing functionally today — see <c>Slice2CatalogWriter</c>'s remarks for the fuller rationale.
/// </remarks>
public static class RelationsSnapshotterEmitter
{
    /// <summary>One field's snapshot-population statement, plus the source-row comment describing it.</summary>
    public sealed record PopulationLine(string SourceComment, string Code);

    public static string Render(string declaringClass, string targetInterface, string varName, IReadOnlyList<PopulationLine> lines)
    {
        var body = string.Join("\n", lines.Select(l => "        " + l.Code));
        var sourceRowsComment = string.Join(", ", lines.Select(l => l.SourceComment));

        return Template
            .Replace("__DECLARINGCLASS__", declaringClass)
            .Replace("__TARGETIFACE__", targetInterface)
            .Replace("__VAR__", varName)
            .Replace("__SOURCEROWS__", sourceRowsComment)
            .Replace("__BODY__", body);
    }

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        //
        //   Source rows (Scope=in, DeclaringClass=__DECLARINGCLASS__): __SOURCEROWS__.
        // </auto-generated>
        using System.Collections.Generic;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Model.Snapshot;
        using SIL.LCModel;

        namespace SIL.Motif.Runner.Snapshotting;

        /// <summary>
        /// Reads a real <c>__TARGETIFACE__</c>'s in-scope slice-2 relation/owning-atomic fields into
        /// the LibLCM-free <see cref="ObjectSnapshot"/> projection. Sibling to the slice-1
        /// <c>__DECLARINGCLASS__Snapshotter</c>; see this file's own remarks (RelationsSnapshotterEmitter.cs,
        /// SIL.Motif.Generator) for why the two are not merged.
        /// </summary>
        public static class __DECLARINGCLASS__RelationsSnapshotter
        {
            public static ObjectSnapshot Snapshot(LcmCache cache, __TARGETIFACE__ __VAR__)
            {
                var canonicalId = CanonicalId.FromGuid(__VAR__.Guid);
                var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        __BODY__

                return new ObjectSnapshot(canonicalId, fields);
            }

            private static void AddIfPopulated(
                Dictionary<string, IReadOnlyDictionary<string, string>> fields,
                string fieldName,
                IReadOnlyDictionary<string, string> alternatives)
            {
                if (alternatives.Count > 0)
                    fields[fieldName] = alternatives;
            }
        }

        """;
}
