using System.Text;

namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits <c>SIL.Motif.Model/Snapshot/SnapshotFields.Generated2.g.cs</c>: one constant per MOT-4
/// slice-2 field, in its own file rather than appended to slice 1's checked-in
/// <c>SnapshotFields.Generated.g.cs</c>. <c>SnapshotFields</c> is already declared <c>partial</c>
/// (docs/plan-motif.md MOT-4), so a second generated file simply contributes more constants to the
/// same type — this keeps slice 1's file, and its byte-identity drift guard
/// (<c>GeneratedFilesAreUpToDateTests</c>), completely untouched.
/// </summary>
public static class Slice2SnapshotFieldsEmitter
{
    /// <summary>One constant to emit: the same facts <see cref="SnapshotFieldsEmitter"/> needs, kept
    /// spec-shape-agnostic so <c>rel/atomic</c>, <c>rel/col</c>/<c>rel/seq</c>, and the hand-modelled
    /// <c>LexEntry.LexemeForm</c> row can all feed one emitter.</summary>
    public sealed record ConstantEntry(
        string DeclaringClass, string FieldName, string Group, string Construct, string SnapshotFieldConstant, string SigDescription);

    public static string Render(IReadOnlyList<ConstantEntry> entries)
    {
        var body = new StringBuilder();
        foreach (var entry in entries.OrderBy(e => e.SnapshotFieldConstant, StringComparer.Ordinal))
        {
            body.AppendLine(
                $"    /// <summary>A <c>{entry.DeclaringClass}</c>'s <c>{entry.FieldName}</c> {entry.SigDescription} field.</summary>");
            body.AppendLine(
                $"    public const string {entry.SnapshotFieldConstant} = \"{entry.Group}/{entry.Construct}/{LowerFirst(entry.FieldName)}\";");
            body.AppendLine();
        }

        return Template.Replace("__BODY__", body.ToString().TrimEnd('\r', '\n'));
    }

    private static string LowerFirst(string value) => char.ToLowerInvariant(value[0]) + value[1..];

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        // </auto-generated>
        namespace SIL.Motif.Model.Snapshot;

        public static partial class SnapshotFields
        {
        __BODY__
        }

        """;
}
