using System.Text;

namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits <c>SIL.Motif.Model/Snapshot/SnapshotFields.Generated3.g.cs</c>: one constant per
/// slice-3 field, in its own file rather than appended to slice 1's or slice 2's checked-in
/// generated files. <c>SnapshotFields</c> is already declared <c>partial</c>, so a third generated
/// file simply contributes more constants to the same type — this keeps slice 1's and slice 2's
/// files, and their byte-identity drift guards, completely untouched.
/// </summary>
public static class Slice3SnapshotFieldsEmitter
{
    /// <summary>One constant to emit — spec-shape-agnostic so basic, <c>rel/atomic</c>, and
    /// <c>rel/col</c>/<c>rel/seq</c> rows can all feed one emitter, mirroring
    /// <see cref="Slice2SnapshotFieldsEmitter.ConstantEntry"/>.</summary>
    public sealed record ConstantEntry(
        string DeclaringClass, string FieldName, string Group, string Construct, string SnapshotFieldConstant, string SigDescription);

    public static string Render(IReadOnlyList<ConstantEntry> entries)
    {
        var body = new StringBuilder();
        foreach (var entry in entries.OrderBy(e => e.SnapshotFieldConstant, StringComparer.Ordinal))
        {
            body.AppendLine(
                $"    /// <summary>A <c>{entry.DeclaringClass}</c>'s <c>{entry.FieldName}</c> {entry.SigDescription} field.</summary>");
            body.AppendLine(
                $"    public const string {entry.SnapshotFieldConstant} = \"{entry.Group}/{entry.Construct}/{LowerFirst(entry.FieldName)}\";");
            body.AppendLine();
        }

        return Template.Replace("__BODY__", body.ToString().TrimEnd('\r', '\n'));
    }

    private static string LowerFirst(string value) => char.ToLowerInvariant(value[0]) + value[1..];

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        // </auto-generated>
        namespace SIL.Motif.Model.Snapshot;

        public static partial class SnapshotFields
        {
        __BODY__
        }

        """;
}
