using System.Text;

namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits one <c>Snapshotting/Generated/{DeclaringClass}Snapshotter.g.cs</c> file: reads every
/// in-scope basic <c>set|clear</c> field of one declaring class into one <see cref="Runner.Snapshotting"/>-shaped
/// <c>ObjectSnapshot</c>, modelled on the hand-written <c>LexSenseSnapshotter</c>.
/// MultiUnicode/MultiString fields go through <c>MultiAlternativesFieldSnapshotting.ReadAlternatives</c>
/// (which converts each populated alternative's writing-system handle to its tag before storing —
/// handles are per-cache and must never be persisted, docs/adr/0016 amended); Boolean fields go
/// through <c>BooleanFieldAlternatives.ToAlternatives</c> — see that type's remarks for why a scalar
/// value reuses the same alternatives-map shape.
/// </summary>
public static class SnapshotterEmitter
{
    public static string Render(string declaringClass, IReadOnlyList<BasicFieldSpec> fieldsForClass)
    {
        var targetInterface = "I" + declaringClass;
        var varName = fieldsForClass[0].Construct;
        var body = new StringBuilder();

        foreach (var field in fieldsForClass)
        {
            var constant = "SnapshotFields." + field.SnapshotFieldConstant;
            if (field.Sig == "Boolean")
            {
                body.AppendLine(
                    $"        fields[{constant}] = BooleanFieldAlternatives.ToAlternatives({varName}.{field.FieldName});");
            }
            else
            {
                body.AppendLine(
                    $"        AddIfPopulated(fields, {constant}, MultiAlternativesFieldSnapshotting.ReadAlternatives(cache, {varName}.{field.FieldName}));");
            }
        }

        var sourceRowsComment = string.Join(", ", fieldsForClass.Select(f => $"{f.DeclaringClass}.{f.FieldName} ({f.Sig})"));

        return Template
            .Replace("__DECLARINGCLASS__", declaringClass)
            .Replace("__TARGETIFACE__", targetInterface)
            .Replace("__VAR__", varName)
            .Replace("__SOURCEROWS__", sourceRowsComment)
            .Replace("__BODY__", body.ToString().TrimEnd('\r', '\n'));
    }

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        //
        //   Source rows (Scope=in, Kind=basic, Verbs=set|clear, DeclaringClass=__DECLARINGCLASS__):
        //   __SOURCEROWS__.
        // </auto-generated>
        using System.Collections.Generic;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Model.Snapshot;
        using SIL.LCModel;

        namespace SIL.Motif.Runner.Snapshotting;

        /// <summary>
        /// Reads a real <c>__TARGETIFACE__</c>'s in-scope basic <c>set|clear</c> fields into the
        /// LibLCM-free <see cref="ObjectSnapshot"/> projection.
        /// </summary>
        public static class __DECLARINGCLASS__Snapshotter
        {
            public static ObjectSnapshot Snapshot(LcmCache cache, __TARGETIFACE__ __VAR__)
            {
                var canonicalId = CanonicalId.FromGuid(__VAR__.Guid);
                var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        __BODY__

                return new ObjectSnapshot(canonicalId, fields);
            }

            private static void AddIfPopulated(
                Dictionary<string, IReadOnlyDictionary<string, string>> fields,
                string fieldName,
                IReadOnlyDictionary<string, string> alternatives)
            {
                if (alternatives.Count > 0)
                    fields[fieldName] = alternatives;
            }
        }

        """;
}
