// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-22).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, Kind=basic, Sig=Integer, Verbs=set, DeclaringClass=WfiWordform):
//   WfiWordform.SpellingStatus (Integer).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IWfiWordform</c>'s basic-Integer-enum fields into the
/// LibLCM-free <see cref="ObjectSnapshot"/> projection.
/// </summary>
public static class WfiWordformSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IWfiWordform wfiWordform)
    {
        var canonicalId = CanonicalId.FromGuid(wfiWordform.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        fields[SnapshotFields.WfiWordformSpellingStatus] = IntegerFieldAlternatives.ToAlternatives(wfiWordform.SpellingStatus);

        return new ObjectSnapshot(canonicalId, fields);
    }
}
