// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
// </auto-generated>
namespace SIL.Motif.Model.Snapshot;

public static partial class SnapshotFields
{
    /// <summary>A <c>WfiWordform</c>'s <c>SpellingStatus</c> basic Integer field.</summary>
    public const string WfiWordformSpellingStatus = "analysis/wfiWordform/spellingStatus";
}
