// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
// </auto-generated>
namespace SIL.Motif.Model.Snapshot;

public static partial class SnapshotFields
{
    /// <summary>A <c>LexEntry</c>'s <c>DialectLabels</c> rel/seq CmPossibility field.</summary>
    public const string LexEntryDialectLabels = "lexical/lexEntry/dialectLabels";

    /// <summary>A <c>LexEntry</c>'s <c>DoNotPublishIn</c> rel/col CmPossibility field.</summary>
    public const string LexEntryDoNotPublishIn = "lexical/lexEntry/doNotPublishIn";

    /// <summary>A <c>LexEntry</c>'s <c>DoNotShowMainEntryIn</c> rel/col CmPossibility field.</summary>
    public const string LexEntryDoNotShowMainEntryIn = "lexical/lexEntry/doNotShowMainEntryIn";

    /// <summary>A <c>LexEntry</c>'s <c>LexemeForm</c> owning/atomic MoForm field.</summary>
    public const string LexEntryLexemeForm = "lexical/lexEntry/lexemeForm";

    /// <summary>A <c>MoForm</c>'s <c>MorphType</c> rel/atomic MoMorphType field.</summary>
    public const string MoFormMorphType = "grammar/moForm/morphType";
}
