// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
// </auto-generated>
namespace SIL.Motif.Model.Snapshot;

public static partial class SnapshotFields
{
    /// <summary>A <c>LexEntry</c>'s <c>Bibliography</c> MultiString field.</summary>
    public const string LexEntryBibliography = "lexical/lexEntry/bibliography";

    /// <summary>A <c>LexEntry</c>'s <c>CitationForm</c> MultiUnicode field.</summary>
    public const string LexEntryCitationForm = "lexical/lexEntry/citationForm";

    /// <summary>A <c>LexEntry</c>'s <c>Comment</c> MultiString field.</summary>
    public const string LexEntryComment = "lexical/lexEntry/comment";

    /// <summary>A <c>LexEntry</c>'s <c>DoNotUseForParsing</c> Boolean field.</summary>
    public const string LexEntryDoNotUseForParsing = "lexical/lexEntry/doNotUseForParsing";

    /// <summary>A <c>LexEntry</c>'s <c>LiteralMeaning</c> MultiString field.</summary>
    public const string LexEntryLiteralMeaning = "lexical/lexEntry/literalMeaning";

    /// <summary>A <c>LexEntry</c>'s <c>Restrictions</c> MultiString field.</summary>
    public const string LexEntryRestrictions = "lexical/lexEntry/restrictions";

    /// <summary>A <c>LexEntry</c>'s <c>SummaryDefinition</c> MultiString field.</summary>
    public const string LexEntrySummaryDefinition = "lexical/lexEntry/summaryDefinition";

    /// <summary>A <c>MoForm</c>'s <c>Form</c> MultiUnicode field.</summary>
    public const string MoFormForm = "grammar/moForm/form";

    /// <summary>A <c>MoForm</c>'s <c>IsAbstract</c> Boolean field.</summary>
    public const string MoFormIsAbstract = "grammar/moForm/isAbstract";
}
