// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
// </auto-generated>
namespace SIL.Motif.Model.Snapshot;

public static partial class SnapshotFields
{
    /// <summary>A <c>CmPossibility</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string CmPossibilityAbbreviation = "lists/cmPossibility/abbreviation";

    /// <summary>A <c>CmPossibilityList</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string CmPossibilityListAbbreviation = "lists/cmPossibilityList/abbreviation";

    /// <summary>A <c>FsFeatDefn</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string FsFeatDefnAbbreviation = "grammar/fsFeatDefn/abbreviation";

    /// <summary>A <c>FsFeatStrucType</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string FsFeatStrucTypeAbbreviation = "grammar/fsFeatStrucType/abbreviation";

    /// <summary>A <c>FsFeatStrucType</c>'s <c>Features</c> rel/seq FsFeatDefn field.</summary>
    public const string FsFeatStrucTypeFeatures = "grammar/fsFeatStrucType/features";

    /// <summary>A <c>FsFeatureSpecification</c>'s <c>Feature</c> rel/atomic FsFeatDefn field.</summary>
    public const string FsFeatureSpecificationFeature = "grammar/fsFeatureSpecification/feature";

    /// <summary>A <c>FsSymFeatVal</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string FsSymFeatValAbbreviation = "grammar/fsSymFeatVal/abbreviation";

    /// <summary>A <c>LexEntryInflType</c>'s <c>GlossAppend</c> basic MultiUnicode field.</summary>
    public const string LexEntryInflTypeGlossAppend = "lexical/lexEntryInflType/glossAppend";

    /// <summary>A <c>LexEntryInflType</c>'s <c>GlossPrepend</c> basic MultiUnicode field.</summary>
    public const string LexEntryInflTypeGlossPrepend = "lexical/lexEntryInflType/glossPrepend";

    /// <summary>A <c>LexEntryInflType</c>'s <c>Slots</c> rel/col MoInflAffixSlot field.</summary>
    public const string LexEntryInflTypeSlots = "lexical/lexEntryInflType/slots";

    /// <summary>A <c>LexEntryRef</c>'s <c>ComponentLexemes</c> rel/seq CmObject field.</summary>
    public const string LexEntryRefComponentLexemes = "lexical/lexEntryRef/componentLexemes";

    /// <summary>A <c>LexEntryRef</c>'s <c>VariantEntryTypes</c> rel/seq LexEntryType field.</summary>
    public const string LexEntryRefVariantEntryTypes = "lexical/lexEntryRef/variantEntryTypes";

    /// <summary>A <c>LexEtymology</c>'s <c>Form</c> basic MultiString field.</summary>
    public const string LexEtymologyForm = "lexical/lexEtymology/form";

    /// <summary>A <c>LexEtymology</c>'s <c>Gloss</c> basic MultiString field.</summary>
    public const string LexEtymologyGloss = "lexical/lexEtymology/gloss";

    /// <summary>A <c>LexPronunciation</c>'s <c>Form</c> basic MultiUnicode field.</summary>
    public const string LexPronunciationForm = "lexical/lexPronunciation/form";

    /// <summary>A <c>LexSense</c>'s <c>MorphoSyntaxAnalysis</c> rel/atomic MoMorphSynAnalysis field.</summary>
    public const string LexSenseMorphoSyntaxAnalysis = "lexical/lexSense/morphoSyntaxAnalysis";

    /// <summary>A <c>MoAdhocProhib</c>'s <c>Disabled</c> basic Boolean field.</summary>
    public const string MoAdhocProhibDisabled = "grammar/moAdhocProhib/disabled";

    /// <summary>A <c>MoAffixAllomorph</c>'s <c>PhoneEnv</c> rel/col PhEnvironment field.</summary>
    public const string MoAffixAllomorphPhoneEnv = "grammar/moAffixAllomorph/phoneEnv";

    /// <summary>A <c>MoAffixAllomorph</c>'s <c>Position</c> rel/seq PhEnvironment field.</summary>
    public const string MoAffixAllomorphPosition = "grammar/moAffixAllomorph/position";

    /// <summary>A <c>MoAffixForm</c>'s <c>InflectionClasses</c> rel/col MoInflClass field.</summary>
    public const string MoAffixFormInflectionClasses = "grammar/moAffixForm/inflectionClasses";

    /// <summary>A <c>MoAlloAdhocProhib</c>'s <c>Allomorphs</c> rel/seq MoForm field.</summary>
    public const string MoAlloAdhocProhibAllomorphs = "grammar/moAlloAdhocProhib/allomorphs";

    /// <summary>A <c>MoAlloAdhocProhib</c>'s <c>FirstAllomorph</c> rel/atomic MoForm field.</summary>
    public const string MoAlloAdhocProhibFirstAllomorph = "grammar/moAlloAdhocProhib/firstAllomorph";

    /// <summary>A <c>MoAlloAdhocProhib</c>'s <c>RestOfAllos</c> rel/seq MoForm field.</summary>
    public const string MoAlloAdhocProhibRestOfAllos = "grammar/moAlloAdhocProhib/restOfAllos";

    /// <summary>A <c>MoCompoundRule</c>'s <c>Disabled</c> basic Boolean field.</summary>
    public const string MoCompoundRuleDisabled = "grammar/moCompoundRule/disabled";

    /// <summary>A <c>MoCompoundRule</c>'s <c>ToProdRestrict</c> rel/col CmPossibility field.</summary>
    public const string MoCompoundRuleToProdRestrict = "grammar/moCompoundRule/toProdRestrict";

    /// <summary>A <c>MoCopyFromInput</c>'s <c>Content</c> rel/atomic PhContextOrVar field.</summary>
    public const string MoCopyFromInputContent = "grammar/moCopyFromInput/content";

    /// <summary>A <c>MoDerivAffMsa</c>'s <c>FromInflectionClass</c> rel/atomic MoInflClass field.</summary>
    public const string MoDerivAffMsaFromInflectionClass = "grammar/moDerivAffMsa/fromInflectionClass";

    /// <summary>A <c>MoDerivAffMsa</c>'s <c>FromPartOfSpeech</c> rel/atomic PartOfSpeech field.</summary>
    public const string MoDerivAffMsaFromPartOfSpeech = "grammar/moDerivAffMsa/fromPartOfSpeech";

    /// <summary>A <c>MoDerivAffMsa</c>'s <c>FromProdRestrict</c> rel/col CmPossibility field.</summary>
    public const string MoDerivAffMsaFromProdRestrict = "grammar/moDerivAffMsa/fromProdRestrict";

    /// <summary>A <c>MoDerivAffMsa</c>'s <c>FromStemName</c> rel/atomic MoStemName field.</summary>
    public const string MoDerivAffMsaFromStemName = "grammar/moDerivAffMsa/fromStemName";

    /// <summary>A <c>MoDerivAffMsa</c>'s <c>ToInflectionClass</c> rel/atomic MoInflClass field.</summary>
    public const string MoDerivAffMsaToInflectionClass = "grammar/moDerivAffMsa/toInflectionClass";

    /// <summary>A <c>MoDerivAffMsa</c>'s <c>ToPartOfSpeech</c> rel/atomic PartOfSpeech field.</summary>
    public const string MoDerivAffMsaToPartOfSpeech = "grammar/moDerivAffMsa/toPartOfSpeech";

    /// <summary>A <c>MoDerivAffMsa</c>'s <c>ToProdRestrict</c> rel/col CmPossibility field.</summary>
    public const string MoDerivAffMsaToProdRestrict = "grammar/moDerivAffMsa/toProdRestrict";

    /// <summary>A <c>MoEndoCompound</c>'s <c>HeadLast</c> basic Boolean field.</summary>
    public const string MoEndoCompoundHeadLast = "grammar/moEndoCompound/headLast";

    /// <summary>A <c>MoInflAffMsa</c>'s <c>FromProdRestrict</c> rel/col CmPossibility field.</summary>
    public const string MoInflAffMsaFromProdRestrict = "grammar/moInflAffMsa/fromProdRestrict";

    /// <summary>A <c>MoInflAffMsa</c>'s <c>PartOfSpeech</c> rel/atomic PartOfSpeech field.</summary>
    public const string MoInflAffMsaPartOfSpeech = "grammar/moInflAffMsa/partOfSpeech";

    /// <summary>A <c>MoInflAffMsa</c>'s <c>Slots</c> rel/col MoInflAffixSlot field.</summary>
    public const string MoInflAffMsaSlots = "grammar/moInflAffMsa/slots";

    /// <summary>A <c>MoInflAffixSlot</c>'s <c>Optional</c> basic Boolean field.</summary>
    public const string MoInflAffixSlotOptional = "grammar/moInflAffixSlot/optional";

    /// <summary>A <c>MoInflAffixTemplate</c>'s <c>Disabled</c> basic Boolean field.</summary>
    public const string MoInflAffixTemplateDisabled = "grammar/moInflAffixTemplate/disabled";

    /// <summary>A <c>MoInflAffixTemplate</c>'s <c>Final</c> basic Boolean field.</summary>
    public const string MoInflAffixTemplateFinal = "grammar/moInflAffixTemplate/final";

    /// <summary>A <c>MoInflAffixTemplate</c>'s <c>PrefixSlots</c> rel/seq MoInflAffixSlot field.</summary>
    public const string MoInflAffixTemplatePrefixSlots = "grammar/moInflAffixTemplate/prefixSlots";

    /// <summary>A <c>MoInflAffixTemplate</c>'s <c>SuffixSlots</c> rel/seq MoInflAffixSlot field.</summary>
    public const string MoInflAffixTemplateSuffixSlots = "grammar/moInflAffixTemplate/suffixSlots";

    /// <summary>A <c>MoInflClass</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string MoInflClassAbbreviation = "grammar/moInflClass/abbreviation";

    /// <summary>A <c>MoInsertNC</c>'s <c>Content</c> rel/atomic PhNaturalClass field.</summary>
    public const string MoInsertNCContent = "grammar/moInsertNC/content";

    /// <summary>A <c>MoInsertPhones</c>'s <c>Content</c> rel/seq PhTerminalUnit field.</summary>
    public const string MoInsertPhonesContent = "grammar/moInsertPhones/content";

    /// <summary>A <c>MoModifyFromInput</c>'s <c>Content</c> rel/atomic PhContextOrVar field.</summary>
    public const string MoModifyFromInputContent = "grammar/moModifyFromInput/content";

    /// <summary>A <c>MoModifyFromInput</c>'s <c>Modification</c> rel/atomic PhNCFeatures field.</summary>
    public const string MoModifyFromInputModification = "grammar/moModifyFromInput/modification";

    /// <summary>A <c>MoMorphAdhocProhib</c>'s <c>FirstMorpheme</c> rel/atomic MoMorphSynAnalysis field.</summary>
    public const string MoMorphAdhocProhibFirstMorpheme = "grammar/moMorphAdhocProhib/firstMorpheme";

    /// <summary>A <c>MoMorphAdhocProhib</c>'s <c>RestOfMorphs</c> rel/seq MoMorphSynAnalysis field.</summary>
    public const string MoMorphAdhocProhibRestOfMorphs = "grammar/moMorphAdhocProhib/restOfMorphs";

    /// <summary>A <c>MoStemAllomorph</c>'s <c>PhoneEnv</c> rel/col PhEnvironment field.</summary>
    public const string MoStemAllomorphPhoneEnv = "grammar/moStemAllomorph/phoneEnv";

    /// <summary>A <c>MoStemAllomorph</c>'s <c>StemName</c> rel/atomic MoStemName field.</summary>
    public const string MoStemAllomorphStemName = "grammar/moStemAllomorph/stemName";

    /// <summary>A <c>MoStemMsa</c>'s <c>FromPartsOfSpeech</c> rel/col PartOfSpeech field.</summary>
    public const string MoStemMsaFromPartsOfSpeech = "grammar/moStemMsa/fromPartsOfSpeech";

    /// <summary>A <c>MoStemMsa</c>'s <c>InflectionClass</c> rel/atomic MoInflClass field.</summary>
    public const string MoStemMsaInflectionClass = "grammar/moStemMsa/inflectionClass";

    /// <summary>A <c>MoStemMsa</c>'s <c>PartOfSpeech</c> rel/atomic PartOfSpeech field.</summary>
    public const string MoStemMsaPartOfSpeech = "grammar/moStemMsa/partOfSpeech";

    /// <summary>A <c>MoStemMsa</c>'s <c>ProdRestrict</c> rel/col CmPossibility field.</summary>
    public const string MoStemMsaProdRestrict = "grammar/moStemMsa/prodRestrict";

    /// <summary>A <c>MoStemMsa</c>'s <c>Slots</c> rel/col MoInflAffixSlot field.</summary>
    public const string MoStemMsaSlots = "grammar/moStemMsa/slots";

    /// <summary>A <c>MoStemName</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string MoStemNameAbbreviation = "grammar/moStemName/abbreviation";

    /// <summary>A <c>MoStratum</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string MoStratumAbbreviation = "grammar/moStratum/abbreviation";

    /// <summary>A <c>MoUnclassifiedAffixMsa</c>'s <c>PartOfSpeech</c> rel/atomic PartOfSpeech field.</summary>
    public const string MoUnclassifiedAffixMsaPartOfSpeech = "grammar/moUnclassifiedAffixMsa/partOfSpeech";

    /// <summary>A <c>PartOfSpeech</c>'s <c>DefaultInflectionClass</c> rel/atomic MoInflClass field.</summary>
    public const string PartOfSpeechDefaultInflectionClass = "grammar/partOfSpeech/defaultInflectionClass";

    /// <summary>A <c>PhCode</c>'s <c>Representation</c> basic MultiUnicode field.</summary>
    public const string PhCodeRepresentation = "grammar/phCode/representation";

    /// <summary>A <c>PhFeatureConstraint</c>'s <c>Feature</c> rel/atomic FsFeatDefn field.</summary>
    public const string PhFeatureConstraintFeature = "grammar/phFeatureConstraint/feature";

    /// <summary>A <c>PhIterationContext</c>'s <c>Member</c> rel/atomic PhPhonContext field.</summary>
    public const string PhIterationContextMember = "grammar/phIterationContext/member";

    /// <summary>A <c>PhNCSegments</c>'s <c>Segments</c> rel/col PhPhoneme field.</summary>
    public const string PhNCSegmentsSegments = "grammar/phNCSegments/segments";

    /// <summary>A <c>PhNaturalClass</c>'s <c>Abbreviation</c> basic MultiUnicode field.</summary>
    public const string PhNaturalClassAbbreviation = "grammar/phNaturalClass/abbreviation";

    /// <summary>A <c>PhSegRuleRHS</c>'s <c>ExclRuleFeats</c> rel/col PhPhonRuleFeat field.</summary>
    public const string PhSegRuleRHSExclRuleFeats = "grammar/phSegRuleRHS/exclRuleFeats";

    /// <summary>A <c>PhSegRuleRHS</c>'s <c>InputPOSes</c> rel/col PartOfSpeech field.</summary>
    public const string PhSegRuleRHSInputPOSes = "grammar/phSegRuleRHS/inputPOSes";

    /// <summary>A <c>PhSegRuleRHS</c>'s <c>ReqRuleFeats</c> rel/col PhPhonRuleFeat field.</summary>
    public const string PhSegRuleRHSReqRuleFeats = "grammar/phSegRuleRHS/reqRuleFeats";

    /// <summary>A <c>PhSegmentRule</c>'s <c>Disabled</c> basic Boolean field.</summary>
    public const string PhSegmentRuleDisabled = "grammar/phSegmentRule/disabled";

    /// <summary>A <c>PhSequenceContext</c>'s <c>Members</c> rel/seq PhPhonContext field.</summary>
    public const string PhSequenceContextMembers = "grammar/phSequenceContext/members";

    /// <summary>A <c>PhSimpleContextBdry</c>'s <c>FeatureStructure</c> rel/atomic PhBdryMarker field.</summary>
    public const string PhSimpleContextBdryFeatureStructure = "grammar/phSimpleContextBdry/featureStructure";

    /// <summary>A <c>PhSimpleContextNC</c>'s <c>FeatureStructure</c> rel/atomic PhNaturalClass field.</summary>
    public const string PhSimpleContextNCFeatureStructure = "grammar/phSimpleContextNC/featureStructure";

    /// <summary>A <c>PhSimpleContextNC</c>'s <c>MinusConstr</c> rel/seq PhFeatureConstraint field.</summary>
    public const string PhSimpleContextNCMinusConstr = "grammar/phSimpleContextNC/minusConstr";

    /// <summary>A <c>PhSimpleContextNC</c>'s <c>PlusConstr</c> rel/seq PhFeatureConstraint field.</summary>
    public const string PhSimpleContextNCPlusConstr = "grammar/phSimpleContextNC/plusConstr";

    /// <summary>A <c>PhSimpleContextSeg</c>'s <c>FeatureStructure</c> rel/atomic PhPhoneme field.</summary>
    public const string PhSimpleContextSegFeatureStructure = "grammar/phSimpleContextSeg/featureStructure";

    /// <summary>A <c>ReversalIndexEntry</c>'s <c>PartOfSpeech</c> rel/atomic PartOfSpeech field.</summary>
    public const string ReversalIndexEntryPartOfSpeech = "lexical/reversalIndexEntry/partOfSpeech";

    /// <summary>A <c>ReversalIndexEntry</c>'s <c>Senses</c> rel/seq LexSense field.</summary>
    public const string ReversalIndexEntrySenses = "lexical/reversalIndexEntry/senses";

    /// <summary>A <c>StText</c>'s <c>RightToLeft</c> basic Boolean field.</summary>
    public const string StTextRightToLeft = "system/stText/rightToLeft";
}
