<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SIL.LCAtom.Cli</RootNamespace>
    <AssemblyName>lcatom</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIL.LCAtom.Host\SIL.LCAtom.Host.csproj" />
    <ProjectReference Include="..\SIL.LCAtom.Runner\SIL.LCAtom.Runner.csproj" />
    <ProjectReference Include="..\SIL.LCAtom.Contract\SIL.LCAtom.Contract.csproj" />
    <ProjectReference Include="..\SIL.LCAtom.Model\SIL.LCAtom.Model.csproj" />
  </ItemGroup>

</Project>
