<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIL.LCAtom.Contract\SIL.LCAtom.Contract.csproj" />
    <ProjectReference Include="..\SIL.LCAtom.Model\SIL.LCAtom.Model.csproj" />
  </ItemGroup>

</Project>
