// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-22).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: WfiWordform.SpellingStatus (basic Integer, Verbs=set|clear; allowed values:
//   0 (Undecided), 1 (Correct), 2 (Incorrect)).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>WfiWordform.SpellingStatus</c> operation kinds.</summary>
public static class WfiWordformSpellingStatusOperationKinds
{
    public const string SetSpellingStatus = "analysis/wfiWordform/setSpellingStatus";
    public const string ClearSpellingStatus = "analysis/wfiWordform/clearSpellingStatus";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetSpellingStatus);
        OperationKindRegistry.Register(ClearSpellingStatus);
        OperationHandlerRegistry.Register(SetSpellingStatus, WfiWordformSpellingStatusSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearSpellingStatus, WfiWordformSpellingStatusClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="WfiWordformSpellingStatusOperationKinds.SetSpellingStatus"/>:
/// <c>{ "value": &lt;integer&gt; }</c>, where <c>value</c> must be one of
/// 0 (Undecided), 1 (Correct), 2 (Incorrect). Closed: any other property is rejected, and a <c>value</c>
/// outside that set is rejected here rather than clamped by LibLCM's own validation, which this
/// operation deliberately does not rely on.</summary>
public static class WfiWordformSpellingStatusSetPayload
{
    private static readonly string[] AllowedProperties = { "value" };
    private static readonly int[] AllowedValues = { 0, 1, 2 };

    public static int Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, WfiWordformSpellingStatusOperationKinds.SetSpellingStatus);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, WfiWordformSpellingStatusOperationKinds.SetSpellingStatus);

        var value = ClosedPayloadParsing.GetRequiredInteger(after, "value", WfiWordformSpellingStatusOperationKinds.SetSpellingStatus);
        if (Array.IndexOf(AllowedValues, value) < 0)
        {
            throw new ContractParseException(
                $"'{WfiWordformSpellingStatusOperationKinds.SetSpellingStatus}' operation 'after.value' ({value}) must be one of 0 (Undecided), 1 (Correct), 2 (Incorrect).");
        }

        return value;
    }
}

/// <summary>The <c>after</c> payload for <see cref="WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus"/>:
/// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear
/// to.</summary>
public static class WfiWordformSpellingStatusClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus);
    }
}

/// <summary>Lowers <see cref="WfiWordformSpellingStatusOperationKinds.SetSpellingStatus"/>: the one LibLCM
/// write it performs, <c>wfiWordform.SpellingStatus = value</c>.</summary>
public static class WfiWordformSpellingStatusSetLowering
{
    public static void Apply(IWfiWordform wfiWordform, int value) => wfiWordform.SpellingStatus = value;
}

/// <summary>Lowers <see cref="WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus"/>: writes the enum's
/// zero member, <c>0</c> (Undecided). Clearing this field retracts whatever judgement was
/// recorded; it does not erase the field, which has no absent state to erase to.</summary>
public static class WfiWordformSpellingStatusClearLowering
{
    public static void Apply(IWfiWordform wfiWordform) => wfiWordform.SpellingStatus = 0;
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="WfiWordformSpellingStatusOperationKinds.SetSpellingStatus"/> operation.</summary>
internal sealed class WfiWordformSpellingStatusSetHandler : IOperationHandler
{
    internal static readonly WfiWordformSpellingStatusSetHandler Instance = new();
    private WfiWordformSpellingStatusSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{WfiWordformSpellingStatusOperationKinds.SetSpellingStatus}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{WfiWordformSpellingStatusOperationKinds.SetSpellingStatus}' requires 'after'.");
        }

        var desired = WfiWordformSpellingStatusSetPayload.Parse(after);

        var (id, wfiWordform) = TargetResolution.Resolve<IWfiWordform>(cache, operation, WfiWordformSpellingStatusOperationKinds.SetSpellingStatus);
        touchedTargets.Add(id);

        var before = ReadField(cache, wfiWordform);
        WfiWordformSpellingStatusSetLowering.Apply(wfiWordform, desired);
        var afterValue = ReadField(cache, wfiWordform);

        return new ExpectedEffect(id, SnapshotFields.WfiWordformSpellingStatus, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, wfiWordform) = TargetResolution.Resolve<IWfiWordform>(cache, operation, WfiWordformSpellingStatusOperationKinds.SetSpellingStatus);
        var current = ReadField(cache, wfiWordform);
        return new ExpectedEffect(id, SnapshotFields.WfiWordformSpellingStatus, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IWfiWordform wfiWordform) =>
        WfiWordformSnapshotter.Snapshot(cache, wfiWordform).AlternativesFields
            .TryGetValue(SnapshotFields.WfiWordformSpellingStatus, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus"/> counterpart to
/// <see cref="WfiWordformSpellingStatusSetHandler"/>.</summary>
internal sealed class WfiWordformSpellingStatusClearHandler : IOperationHandler
{
    internal static readonly WfiWordformSpellingStatusClearHandler Instance = new();
    private WfiWordformSpellingStatusClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus}' requires 'after'.");
        }

        WfiWordformSpellingStatusClearPayload.Parse(after);

        var (id, wfiWordform) = TargetResolution.Resolve<IWfiWordform>(cache, operation, WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus);
        touchedTargets.Add(id);

        var before = ReadField(cache, wfiWordform);
        WfiWordformSpellingStatusClearLowering.Apply(wfiWordform);
        var afterValue = ReadField(cache, wfiWordform);

        return new ExpectedEffect(id, SnapshotFields.WfiWordformSpellingStatus, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, wfiWordform) = TargetResolution.Resolve<IWfiWordform>(cache, operation, WfiWordformSpellingStatusOperationKinds.ClearSpellingStatus);
        var current = ReadField(cache, wfiWordform);
        return new ExpectedEffect(id, SnapshotFields.WfiWordformSpellingStatus, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IWfiWordform wfiWordform) =>
        WfiWordformSnapshotter.Snapshot(cache, wfiWordform).AlternativesFields
            .TryGetValue(SnapshotFields.WfiWordformSpellingStatus, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
