// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: CmPossibilityList.Abbreviation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>CmPossibilityList.Abbreviation</c> operation kinds.</summary>
public static class CmPossibilityListAbbreviationOperationKinds
{
    public const string SetAbbreviation = "lists/cmPossibilityList/setAbbreviation";
    public const string ClearAbbreviation = "lists/cmPossibilityList/clearAbbreviation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetAbbreviation);
        OperationKindRegistry.Register(ClearAbbreviation);
        OperationHandlerRegistry.Register(SetAbbreviation, CmPossibilityListAbbreviationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearAbbreviation, CmPossibilityListAbbreviationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="CmPossibilityListAbbreviationOperationKinds.SetAbbreviation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class CmPossibilityListAbbreviationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, CmPossibilityListAbbreviationOperationKinds.SetAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, CmPossibilityListAbbreviationOperationKinds.SetAbbreviation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", CmPossibilityListAbbreviationOperationKinds.SetAbbreviation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", CmPossibilityListAbbreviationOperationKinds.SetAbbreviation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class CmPossibilityListAbbreviationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation);
    }
}

/// <summary>Lowers <see cref="CmPossibilityListAbbreviationOperationKinds.SetAbbreviation"/>: sets one
/// writing-system alternative of <c>cmPossibilityList.Abbreviation</c>.</summary>
public static class CmPossibilityListAbbreviationSetLowering
{
    public static void Apply(LcmCache cache, ICmPossibilityList cmPossibilityList, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, cmPossibilityList.Abbreviation, writingSystemTag, text, CmPossibilityListAbbreviationOperationKinds.SetAbbreviation);
}

/// <summary>Lowers <see cref="CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation"/>: clears one
/// writing-system alternative of <c>cmPossibilityList.Abbreviation</c>.</summary>
public static class CmPossibilityListAbbreviationClearLowering
{
    public static void Apply(LcmCache cache, ICmPossibilityList cmPossibilityList, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, cmPossibilityList.Abbreviation, writingSystemTag, CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="CmPossibilityListAbbreviationOperationKinds.SetAbbreviation"/> operation.</summary>
internal sealed class CmPossibilityListAbbreviationSetHandler : IOperationHandler
{
    internal static readonly CmPossibilityListAbbreviationSetHandler Instance = new();
    private CmPossibilityListAbbreviationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{CmPossibilityListAbbreviationOperationKinds.SetAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{CmPossibilityListAbbreviationOperationKinds.SetAbbreviation}' requires 'after'.");
        }

        var (writingSystemTag, text) = CmPossibilityListAbbreviationSetPayload.Parse(after);

        var (id, cmPossibilityList) = TargetResolution.Resolve<ICmPossibilityList>(cache, operation, CmPossibilityListAbbreviationOperationKinds.SetAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, cmPossibilityList);
        CmPossibilityListAbbreviationSetLowering.Apply(cache, cmPossibilityList, writingSystemTag, text);
        var afterValue = ReadField(cache, cmPossibilityList);

        return new ExpectedEffect(id, SnapshotFields.CmPossibilityListAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, cmPossibilityList) = TargetResolution.Resolve<ICmPossibilityList>(cache, operation, CmPossibilityListAbbreviationOperationKinds.SetAbbreviation);
        var current = ReadField(cache, cmPossibilityList);
        return new ExpectedEffect(id, SnapshotFields.CmPossibilityListAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, ICmPossibilityList cmPossibilityList) =>
        CmPossibilityListSnapshotter.Snapshot(cache, cmPossibilityList).AlternativesFields
            .TryGetValue(SnapshotFields.CmPossibilityListAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation"/> counterpart to
/// <see cref="CmPossibilityListAbbreviationSetHandler"/>.</summary>
internal sealed class CmPossibilityListAbbreviationClearHandler : IOperationHandler
{
    internal static readonly CmPossibilityListAbbreviationClearHandler Instance = new();
    private CmPossibilityListAbbreviationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation}' requires 'after'.");
        }

        var writingSystemTag = CmPossibilityListAbbreviationClearPayload.Parse(after);

        var (id, cmPossibilityList) = TargetResolution.Resolve<ICmPossibilityList>(cache, operation, CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, cmPossibilityList);
        CmPossibilityListAbbreviationClearLowering.Apply(cache, cmPossibilityList, writingSystemTag);
        var afterValue = ReadField(cache, cmPossibilityList);

        return new ExpectedEffect(id, SnapshotFields.CmPossibilityListAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, cmPossibilityList) = TargetResolution.Resolve<ICmPossibilityList>(cache, operation, CmPossibilityListAbbreviationOperationKinds.ClearAbbreviation);
        var current = ReadField(cache, cmPossibilityList);
        return new ExpectedEffect(id, SnapshotFields.CmPossibilityListAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, ICmPossibilityList cmPossibilityList) =>
        CmPossibilityListSnapshotter.Snapshot(cache, cmPossibilityList).AlternativesFields
            .TryGetValue(SnapshotFields.CmPossibilityListAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
