// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: FsFeatDefn.Abbreviation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>FsFeatDefn.Abbreviation</c> operation kinds.</summary>
public static class FsFeatDefnAbbreviationOperationKinds
{
    public const string SetAbbreviation = "grammar/fsFeatDefn/setAbbreviation";
    public const string ClearAbbreviation = "grammar/fsFeatDefn/clearAbbreviation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetAbbreviation);
        OperationKindRegistry.Register(ClearAbbreviation);
        OperationHandlerRegistry.Register(SetAbbreviation, FsFeatDefnAbbreviationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearAbbreviation, FsFeatDefnAbbreviationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsFeatDefnAbbreviationOperationKinds.SetAbbreviation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class FsFeatDefnAbbreviationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsFeatDefnAbbreviationOperationKinds.SetAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsFeatDefnAbbreviationOperationKinds.SetAbbreviation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", FsFeatDefnAbbreviationOperationKinds.SetAbbreviation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", FsFeatDefnAbbreviationOperationKinds.SetAbbreviation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class FsFeatDefnAbbreviationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation);
    }
}

/// <summary>Lowers <see cref="FsFeatDefnAbbreviationOperationKinds.SetAbbreviation"/>: sets one
/// writing-system alternative of <c>fsFeatDefn.Abbreviation</c>.</summary>
public static class FsFeatDefnAbbreviationSetLowering
{
    public static void Apply(LcmCache cache, IFsFeatDefn fsFeatDefn, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, fsFeatDefn.Abbreviation, writingSystemTag, text, FsFeatDefnAbbreviationOperationKinds.SetAbbreviation);
}

/// <summary>Lowers <see cref="FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation"/>: clears one
/// writing-system alternative of <c>fsFeatDefn.Abbreviation</c>.</summary>
public static class FsFeatDefnAbbreviationClearLowering
{
    public static void Apply(LcmCache cache, IFsFeatDefn fsFeatDefn, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, fsFeatDefn.Abbreviation, writingSystemTag, FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="FsFeatDefnAbbreviationOperationKinds.SetAbbreviation"/> operation.</summary>
internal sealed class FsFeatDefnAbbreviationSetHandler : IOperationHandler
{
    internal static readonly FsFeatDefnAbbreviationSetHandler Instance = new();
    private FsFeatDefnAbbreviationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatDefnAbbreviationOperationKinds.SetAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatDefnAbbreviationOperationKinds.SetAbbreviation}' requires 'after'.");
        }

        var (writingSystemTag, text) = FsFeatDefnAbbreviationSetPayload.Parse(after);

        var (id, fsFeatDefn) = TargetResolution.Resolve<IFsFeatDefn>(cache, operation, FsFeatDefnAbbreviationOperationKinds.SetAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, fsFeatDefn);
        FsFeatDefnAbbreviationSetLowering.Apply(cache, fsFeatDefn, writingSystemTag, text);
        var afterValue = ReadField(cache, fsFeatDefn);

        return new ExpectedEffect(id, SnapshotFields.FsFeatDefnAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatDefn) = TargetResolution.Resolve<IFsFeatDefn>(cache, operation, FsFeatDefnAbbreviationOperationKinds.SetAbbreviation);
        var current = ReadField(cache, fsFeatDefn);
        return new ExpectedEffect(id, SnapshotFields.FsFeatDefnAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IFsFeatDefn fsFeatDefn) =>
        FsFeatDefnSnapshotter.Snapshot(cache, fsFeatDefn).AlternativesFields
            .TryGetValue(SnapshotFields.FsFeatDefnAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation"/> counterpart to
/// <see cref="FsFeatDefnAbbreviationSetHandler"/>.</summary>
internal sealed class FsFeatDefnAbbreviationClearHandler : IOperationHandler
{
    internal static readonly FsFeatDefnAbbreviationClearHandler Instance = new();
    private FsFeatDefnAbbreviationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation}' requires 'after'.");
        }

        var writingSystemTag = FsFeatDefnAbbreviationClearPayload.Parse(after);

        var (id, fsFeatDefn) = TargetResolution.Resolve<IFsFeatDefn>(cache, operation, FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, fsFeatDefn);
        FsFeatDefnAbbreviationClearLowering.Apply(cache, fsFeatDefn, writingSystemTag);
        var afterValue = ReadField(cache, fsFeatDefn);

        return new ExpectedEffect(id, SnapshotFields.FsFeatDefnAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatDefn) = TargetResolution.Resolve<IFsFeatDefn>(cache, operation, FsFeatDefnAbbreviationOperationKinds.ClearAbbreviation);
        var current = ReadField(cache, fsFeatDefn);
        return new ExpectedEffect(id, SnapshotFields.FsFeatDefnAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IFsFeatDefn fsFeatDefn) =>
        FsFeatDefnSnapshotter.Snapshot(cache, fsFeatDefn).AlternativesFields
            .TryGetValue(SnapshotFields.FsFeatDefnAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
