// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: FsFeatureSpecification.Feature (rel/atomic FsFeatDefn, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>FsFeatureSpecification.Feature</c> operation kinds.</summary>
public static class FsFeatureSpecificationFeatureOperationKinds
{
    public const string SetFeature = "grammar/fsFeatureSpecification/setFeature";
    public const string ClearFeature = "grammar/fsFeatureSpecification/clearFeature";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetFeature);
        OperationKindRegistry.Register(ClearFeature);
        OperationHandlerRegistry.Register(SetFeature, FsFeatureSpecificationFeatureSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearFeature, FsFeatureSpecificationFeatureClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsFeatureSpecificationFeatureOperationKinds.SetFeature"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class FsFeatureSpecificationFeatureSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsFeatureSpecificationFeatureOperationKinds.SetFeature);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsFeatureSpecificationFeatureOperationKinds.SetFeature);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", FsFeatureSpecificationFeatureOperationKinds.SetFeature);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsFeatureSpecificationFeatureOperationKinds.ClearFeature"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class FsFeatureSpecificationFeatureClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsFeatureSpecificationFeatureOperationKinds.ClearFeature);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsFeatureSpecificationFeatureOperationKinds.ClearFeature);
    }
}

/// <summary>Lowers <see cref="FsFeatureSpecificationFeatureOperationKinds.SetFeature"/>: resolves the
/// referenced IFsFeatDefn and assigns it to <c>fsFeatureSpecification.FeatureRA</c>.</summary>
public static class FsFeatureSpecificationFeatureSetLowering
{
    public static void Apply(LcmCache cache, IFsFeatureSpecification fsFeatureSpecification, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IFsFeatDefn>(
            cache, value => fsFeatureSpecification.FeatureRA = value, refId, FsFeatureSpecificationFeatureOperationKinds.SetFeature);
}

/// <summary>Lowers <see cref="FsFeatureSpecificationFeatureOperationKinds.ClearFeature"/>: detaches
/// <c>fsFeatureSpecification.FeatureRA</c>.</summary>
public static class FsFeatureSpecificationFeatureClearLowering
{
    public static void Apply(IFsFeatureSpecification fsFeatureSpecification) =>
        ReferenceFieldLowering.ApplyClear<IFsFeatDefn>(value => fsFeatureSpecification.FeatureRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="FsFeatureSpecificationFeatureOperationKinds.SetFeature"/> operation.</summary>
internal sealed class FsFeatureSpecificationFeatureSetHandler : IOperationHandler
{
    internal static readonly FsFeatureSpecificationFeatureSetHandler Instance = new();
    private FsFeatureSpecificationFeatureSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatureSpecificationFeatureOperationKinds.SetFeature}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatureSpecificationFeatureOperationKinds.SetFeature}' requires 'after'.");
        }

        var refId = FsFeatureSpecificationFeatureSetPayload.Parse(after);

        var (id, fsFeatureSpecification) = TargetResolution.Resolve<IFsFeatureSpecification>(cache, operation, FsFeatureSpecificationFeatureOperationKinds.SetFeature);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(fsFeatureSpecification.FeatureRA);
        FsFeatureSpecificationFeatureSetLowering.Apply(cache, fsFeatureSpecification, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(fsFeatureSpecification.FeatureRA);

        return new ExpectedEffect(id, SnapshotFields.FsFeatureSpecificationFeature, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatureSpecification) = TargetResolution.Resolve<IFsFeatureSpecification>(cache, operation, FsFeatureSpecificationFeatureOperationKinds.SetFeature);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(fsFeatureSpecification.FeatureRA);
        return new ExpectedEffect(id, SnapshotFields.FsFeatureSpecificationFeature, current, current);
    }
}

/// <summary>The <see cref="FsFeatureSpecificationFeatureOperationKinds.ClearFeature"/> counterpart to
/// <see cref="FsFeatureSpecificationFeatureSetHandler"/>.</summary>
internal sealed class FsFeatureSpecificationFeatureClearHandler : IOperationHandler
{
    internal static readonly FsFeatureSpecificationFeatureClearHandler Instance = new();
    private FsFeatureSpecificationFeatureClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatureSpecificationFeatureOperationKinds.ClearFeature}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatureSpecificationFeatureOperationKinds.ClearFeature}' requires 'after'.");
        }

        FsFeatureSpecificationFeatureClearPayload.Parse(after);

        var (id, fsFeatureSpecification) = TargetResolution.Resolve<IFsFeatureSpecification>(cache, operation, FsFeatureSpecificationFeatureOperationKinds.ClearFeature);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(fsFeatureSpecification.FeatureRA);
        FsFeatureSpecificationFeatureClearLowering.Apply(fsFeatureSpecification);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(fsFeatureSpecification.FeatureRA);

        return new ExpectedEffect(id, SnapshotFields.FsFeatureSpecificationFeature, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatureSpecification) = TargetResolution.Resolve<IFsFeatureSpecification>(cache, operation, FsFeatureSpecificationFeatureOperationKinds.ClearFeature);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(fsFeatureSpecification.FeatureRA);
        return new ExpectedEffect(id, SnapshotFields.FsFeatureSpecificationFeature, current, current);
    }
}
