// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: FsFeatStrucType.Abbreviation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>FsFeatStrucType.Abbreviation</c> operation kinds.</summary>
public static class FsFeatStrucTypeAbbreviationOperationKinds
{
    public const string SetAbbreviation = "grammar/fsFeatStrucType/setAbbreviation";
    public const string ClearAbbreviation = "grammar/fsFeatStrucType/clearAbbreviation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetAbbreviation);
        OperationKindRegistry.Register(ClearAbbreviation);
        OperationHandlerRegistry.Register(SetAbbreviation, FsFeatStrucTypeAbbreviationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearAbbreviation, FsFeatStrucTypeAbbreviationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class FsFeatStrucTypeAbbreviationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class FsFeatStrucTypeAbbreviationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation);
    }
}

/// <summary>Lowers <see cref="FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation"/>: sets one
/// writing-system alternative of <c>fsFeatStrucType.Abbreviation</c>.</summary>
public static class FsFeatStrucTypeAbbreviationSetLowering
{
    public static void Apply(LcmCache cache, IFsFeatStrucType fsFeatStrucType, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, fsFeatStrucType.Abbreviation, writingSystemTag, text, FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation);
}

/// <summary>Lowers <see cref="FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation"/>: clears one
/// writing-system alternative of <c>fsFeatStrucType.Abbreviation</c>.</summary>
public static class FsFeatStrucTypeAbbreviationClearLowering
{
    public static void Apply(LcmCache cache, IFsFeatStrucType fsFeatStrucType, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, fsFeatStrucType.Abbreviation, writingSystemTag, FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation"/> operation.</summary>
internal sealed class FsFeatStrucTypeAbbreviationSetHandler : IOperationHandler
{
    internal static readonly FsFeatStrucTypeAbbreviationSetHandler Instance = new();
    private FsFeatStrucTypeAbbreviationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation}' requires 'after'.");
        }

        var (writingSystemTag, text) = FsFeatStrucTypeAbbreviationSetPayload.Parse(after);

        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, fsFeatStrucType);
        FsFeatStrucTypeAbbreviationSetLowering.Apply(cache, fsFeatStrucType, writingSystemTag, text);
        var afterValue = ReadField(cache, fsFeatStrucType);

        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeAbbreviationOperationKinds.SetAbbreviation);
        var current = ReadField(cache, fsFeatStrucType);
        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IFsFeatStrucType fsFeatStrucType) =>
        FsFeatStrucTypeSnapshotter.Snapshot(cache, fsFeatStrucType).AlternativesFields
            .TryGetValue(SnapshotFields.FsFeatStrucTypeAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation"/> counterpart to
/// <see cref="FsFeatStrucTypeAbbreviationSetHandler"/>.</summary>
internal sealed class FsFeatStrucTypeAbbreviationClearHandler : IOperationHandler
{
    internal static readonly FsFeatStrucTypeAbbreviationClearHandler Instance = new();
    private FsFeatStrucTypeAbbreviationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation}' requires 'after'.");
        }

        var writingSystemTag = FsFeatStrucTypeAbbreviationClearPayload.Parse(after);

        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, fsFeatStrucType);
        FsFeatStrucTypeAbbreviationClearLowering.Apply(cache, fsFeatStrucType, writingSystemTag);
        var afterValue = ReadField(cache, fsFeatStrucType);

        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeAbbreviationOperationKinds.ClearAbbreviation);
        var current = ReadField(cache, fsFeatStrucType);
        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IFsFeatStrucType fsFeatStrucType) =>
        FsFeatStrucTypeSnapshotter.Snapshot(cache, fsFeatStrucType).AlternativesFields
            .TryGetValue(SnapshotFields.FsFeatStrucTypeAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
