// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: FsSymFeatVal.Abbreviation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>FsSymFeatVal.Abbreviation</c> operation kinds.</summary>
public static class FsSymFeatValAbbreviationOperationKinds
{
    public const string SetAbbreviation = "grammar/fsSymFeatVal/setAbbreviation";
    public const string ClearAbbreviation = "grammar/fsSymFeatVal/clearAbbreviation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetAbbreviation);
        OperationKindRegistry.Register(ClearAbbreviation);
        OperationHandlerRegistry.Register(SetAbbreviation, FsSymFeatValAbbreviationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearAbbreviation, FsSymFeatValAbbreviationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsSymFeatValAbbreviationOperationKinds.SetAbbreviation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class FsSymFeatValAbbreviationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsSymFeatValAbbreviationOperationKinds.SetAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsSymFeatValAbbreviationOperationKinds.SetAbbreviation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", FsSymFeatValAbbreviationOperationKinds.SetAbbreviation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", FsSymFeatValAbbreviationOperationKinds.SetAbbreviation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class FsSymFeatValAbbreviationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation);
    }
}

/// <summary>Lowers <see cref="FsSymFeatValAbbreviationOperationKinds.SetAbbreviation"/>: sets one
/// writing-system alternative of <c>fsSymFeatVal.Abbreviation</c>.</summary>
public static class FsSymFeatValAbbreviationSetLowering
{
    public static void Apply(LcmCache cache, IFsSymFeatVal fsSymFeatVal, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, fsSymFeatVal.Abbreviation, writingSystemTag, text, FsSymFeatValAbbreviationOperationKinds.SetAbbreviation);
}

/// <summary>Lowers <see cref="FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation"/>: clears one
/// writing-system alternative of <c>fsSymFeatVal.Abbreviation</c>.</summary>
public static class FsSymFeatValAbbreviationClearLowering
{
    public static void Apply(LcmCache cache, IFsSymFeatVal fsSymFeatVal, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, fsSymFeatVal.Abbreviation, writingSystemTag, FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="FsSymFeatValAbbreviationOperationKinds.SetAbbreviation"/> operation.</summary>
internal sealed class FsSymFeatValAbbreviationSetHandler : IOperationHandler
{
    internal static readonly FsSymFeatValAbbreviationSetHandler Instance = new();
    private FsSymFeatValAbbreviationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsSymFeatValAbbreviationOperationKinds.SetAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsSymFeatValAbbreviationOperationKinds.SetAbbreviation}' requires 'after'.");
        }

        var (writingSystemTag, text) = FsSymFeatValAbbreviationSetPayload.Parse(after);

        var (id, fsSymFeatVal) = TargetResolution.Resolve<IFsSymFeatVal>(cache, operation, FsSymFeatValAbbreviationOperationKinds.SetAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, fsSymFeatVal);
        FsSymFeatValAbbreviationSetLowering.Apply(cache, fsSymFeatVal, writingSystemTag, text);
        var afterValue = ReadField(cache, fsSymFeatVal);

        return new ExpectedEffect(id, SnapshotFields.FsSymFeatValAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsSymFeatVal) = TargetResolution.Resolve<IFsSymFeatVal>(cache, operation, FsSymFeatValAbbreviationOperationKinds.SetAbbreviation);
        var current = ReadField(cache, fsSymFeatVal);
        return new ExpectedEffect(id, SnapshotFields.FsSymFeatValAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IFsSymFeatVal fsSymFeatVal) =>
        FsSymFeatValSnapshotter.Snapshot(cache, fsSymFeatVal).AlternativesFields
            .TryGetValue(SnapshotFields.FsSymFeatValAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation"/> counterpart to
/// <see cref="FsSymFeatValAbbreviationSetHandler"/>.</summary>
internal sealed class FsSymFeatValAbbreviationClearHandler : IOperationHandler
{
    internal static readonly FsSymFeatValAbbreviationClearHandler Instance = new();
    private FsSymFeatValAbbreviationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation}' requires 'after'.");
        }

        var writingSystemTag = FsSymFeatValAbbreviationClearPayload.Parse(after);

        var (id, fsSymFeatVal) = TargetResolution.Resolve<IFsSymFeatVal>(cache, operation, FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, fsSymFeatVal);
        FsSymFeatValAbbreviationClearLowering.Apply(cache, fsSymFeatVal, writingSystemTag);
        var afterValue = ReadField(cache, fsSymFeatVal);

        return new ExpectedEffect(id, SnapshotFields.FsSymFeatValAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsSymFeatVal) = TargetResolution.Resolve<IFsSymFeatVal>(cache, operation, FsSymFeatValAbbreviationOperationKinds.ClearAbbreviation);
        var current = ReadField(cache, fsSymFeatVal);
        return new ExpectedEffect(id, SnapshotFields.FsSymFeatValAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IFsSymFeatVal fsSymFeatVal) =>
        FsSymFeatValSnapshotter.Snapshot(cache, fsSymFeatVal).AlternativesFields
            .TryGetValue(SnapshotFields.FsSymFeatValAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
