// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: LexEntryInflType.GlossPrepend (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>LexEntryInflType.GlossPrepend</c> operation kinds.</summary>
public static class LexEntryInflTypeGlossPrependOperationKinds
{
    public const string SetGlossPrepend = "lexical/lexEntryInflType/setGlossPrepend";
    public const string ClearGlossPrepend = "lexical/lexEntryInflType/clearGlossPrepend";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetGlossPrepend);
        OperationKindRegistry.Register(ClearGlossPrepend);
        OperationHandlerRegistry.Register(SetGlossPrepend, LexEntryInflTypeGlossPrependSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearGlossPrepend, LexEntryInflTypeGlossPrependClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class LexEntryInflTypeGlossPrependSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class LexEntryInflTypeGlossPrependClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend);
    }
}

/// <summary>Lowers <see cref="LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend"/>: sets one
/// writing-system alternative of <c>lexEntryInflType.GlossPrepend</c>.</summary>
public static class LexEntryInflTypeGlossPrependSetLowering
{
    public static void Apply(LcmCache cache, ILexEntryInflType lexEntryInflType, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, lexEntryInflType.GlossPrepend, writingSystemTag, text, LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend);
}

/// <summary>Lowers <see cref="LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend"/>: clears one
/// writing-system alternative of <c>lexEntryInflType.GlossPrepend</c>.</summary>
public static class LexEntryInflTypeGlossPrependClearLowering
{
    public static void Apply(LcmCache cache, ILexEntryInflType lexEntryInflType, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, lexEntryInflType.GlossPrepend, writingSystemTag, LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend"/> operation.</summary>
internal sealed class LexEntryInflTypeGlossPrependSetHandler : IOperationHandler
{
    internal static readonly LexEntryInflTypeGlossPrependSetHandler Instance = new();
    private LexEntryInflTypeGlossPrependSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend}' requires 'after'.");
        }

        var (writingSystemTag, text) = LexEntryInflTypeGlossPrependSetPayload.Parse(after);

        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend);
        touchedTargets.Add(id);

        var before = ReadField(cache, lexEntryInflType);
        LexEntryInflTypeGlossPrependSetLowering.Apply(cache, lexEntryInflType, writingSystemTag, text);
        var afterValue = ReadField(cache, lexEntryInflType);

        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeGlossPrepend, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeGlossPrependOperationKinds.SetGlossPrepend);
        var current = ReadField(cache, lexEntryInflType);
        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeGlossPrepend, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, ILexEntryInflType lexEntryInflType) =>
        LexEntryInflTypeSnapshotter.Snapshot(cache, lexEntryInflType).AlternativesFields
            .TryGetValue(SnapshotFields.LexEntryInflTypeGlossPrepend, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend"/> counterpart to
/// <see cref="LexEntryInflTypeGlossPrependSetHandler"/>.</summary>
internal sealed class LexEntryInflTypeGlossPrependClearHandler : IOperationHandler
{
    internal static readonly LexEntryInflTypeGlossPrependClearHandler Instance = new();
    private LexEntryInflTypeGlossPrependClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend}' requires 'after'.");
        }

        var writingSystemTag = LexEntryInflTypeGlossPrependClearPayload.Parse(after);

        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend);
        touchedTargets.Add(id);

        var before = ReadField(cache, lexEntryInflType);
        LexEntryInflTypeGlossPrependClearLowering.Apply(cache, lexEntryInflType, writingSystemTag);
        var afterValue = ReadField(cache, lexEntryInflType);

        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeGlossPrepend, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeGlossPrependOperationKinds.ClearGlossPrepend);
        var current = ReadField(cache, lexEntryInflType);
        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeGlossPrepend, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, ILexEntryInflType lexEntryInflType) =>
        LexEntryInflTypeSnapshotter.Snapshot(cache, lexEntryInflType).AlternativesFields
            .TryGetValue(SnapshotFields.LexEntryInflTypeGlossPrepend, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
