// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: LexEntryInflType.Slots (rel/col MoInflAffixSlot, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>LexEntryInflType.Slots</c> operation kinds.</summary>
public static class LexEntryInflTypeSlotsOperationKinds
{
    public const string AddRefSlots = "lexical/lexEntryInflType/addRefSlots";
    public const string RemoveRefSlots = "lexical/lexEntryInflType/removeRefSlots";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefSlots);
        OperationKindRegistry.Register(RemoveRefSlots);
        OperationHandlerRegistry.Register(AddRefSlots, LexEntryInflTypeSlotsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefSlots, LexEntryInflTypeSlotsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="LexEntryInflTypeSlotsOperationKinds.AddRefSlots"/>
/// and <see cref="LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class LexEntryInflTypeSlotsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="LexEntryInflTypeSlotsOperationKinds.AddRefSlots"/>: resolves the
/// referenced IMoInflAffixSlot and adds it to <c>lexEntryInflType.SlotsRC</c> (a no-op if already
/// present).</summary>
public static class LexEntryInflTypeSlotsAddRefLowering
{
    public static void Apply(LcmCache cache, ILexEntryInflType lexEntryInflType, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoInflAffixSlot>(
            cache, lexEntryInflType.SlotsRC, memberId, LexEntryInflTypeSlotsOperationKinds.AddRefSlots);
}

/// <summary>Lowers <see cref="LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots"/>: resolves the
/// referenced IMoInflAffixSlot and removes it from <c>lexEntryInflType.SlotsRC</c> (a no-op if
/// absent).</summary>
public static class LexEntryInflTypeSlotsRemoveRefLowering
{
    public static void Apply(LcmCache cache, ILexEntryInflType lexEntryInflType, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoInflAffixSlot>(
            cache, lexEntryInflType.SlotsRC, memberId, LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="LexEntryInflTypeSlotsOperationKinds.AddRefSlots"/> operation.</summary>
internal sealed class LexEntryInflTypeSlotsAddRefHandler : IOperationHandler
{
    internal static readonly LexEntryInflTypeSlotsAddRefHandler Instance = new();
    private LexEntryInflTypeSlotsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeSlotsOperationKinds.AddRefSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeSlotsOperationKinds.AddRefSlots}' requires 'after'.");
        }

        var memberId = LexEntryInflTypeSlotsMemberPayload.Parse(after, LexEntryInflTypeSlotsOperationKinds.AddRefSlots);

        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeSlotsOperationKinds.AddRefSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntryInflType.SlotsRC);
        LexEntryInflTypeSlotsAddRefLowering.Apply(cache, lexEntryInflType, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntryInflType.SlotsRC);

        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeSlotsOperationKinds.AddRefSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntryInflType.SlotsRC);
        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeSlots, current, current);
    }
}

/// <summary>The <see cref="LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots"/> counterpart to
/// <see cref="LexEntryInflTypeSlotsAddRefHandler"/>.</summary>
internal sealed class LexEntryInflTypeSlotsRemoveRefHandler : IOperationHandler
{
    internal static readonly LexEntryInflTypeSlotsRemoveRefHandler Instance = new();
    private LexEntryInflTypeSlotsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots}' requires 'after'.");
        }

        var memberId = LexEntryInflTypeSlotsMemberPayload.Parse(after, LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots);

        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntryInflType.SlotsRC);
        LexEntryInflTypeSlotsRemoveRefLowering.Apply(cache, lexEntryInflType, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntryInflType.SlotsRC);

        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryInflType) = TargetResolution.Resolve<ILexEntryInflType>(cache, operation, LexEntryInflTypeSlotsOperationKinds.RemoveRefSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(lexEntryInflType.SlotsRC);
        return new ExpectedEffect(id, SnapshotFields.LexEntryInflTypeSlots, current, current);
    }
}
