// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: LexSense.MorphoSyntaxAnalysis (rel/atomic MoMorphSynAnalysis, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>LexSense.MorphoSyntaxAnalysis</c> operation kinds.</summary>
public static class LexSenseMorphoSyntaxAnalysisOperationKinds
{
    public const string SetMorphoSyntaxAnalysis = "lexical/lexSense/setMorphoSyntaxAnalysis";
    public const string ClearMorphoSyntaxAnalysis = "lexical/lexSense/clearMorphoSyntaxAnalysis";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetMorphoSyntaxAnalysis);
        OperationKindRegistry.Register(ClearMorphoSyntaxAnalysis);
        OperationHandlerRegistry.Register(SetMorphoSyntaxAnalysis, LexSenseMorphoSyntaxAnalysisSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearMorphoSyntaxAnalysis, LexSenseMorphoSyntaxAnalysisClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class LexSenseMorphoSyntaxAnalysisSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis);
    }
}

/// <summary>The <c>after</c> payload for <see cref="LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class LexSenseMorphoSyntaxAnalysisClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis);
    }
}

/// <summary>Lowers <see cref="LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis"/>: resolves the
/// referenced IMoMorphSynAnalysis and assigns it to <c>lexSense.MorphoSyntaxAnalysisRA</c>.</summary>
public static class LexSenseMorphoSyntaxAnalysisSetLowering
{
    public static void Apply(LcmCache cache, ILexSense lexSense, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IMoMorphSynAnalysis>(
            cache, value => lexSense.MorphoSyntaxAnalysisRA = value, refId, LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis);
}

/// <summary>Lowers <see cref="LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis"/>: detaches
/// <c>lexSense.MorphoSyntaxAnalysisRA</c>.</summary>
public static class LexSenseMorphoSyntaxAnalysisClearLowering
{
    public static void Apply(ILexSense lexSense) =>
        ReferenceFieldLowering.ApplyClear<IMoMorphSynAnalysis>(value => lexSense.MorphoSyntaxAnalysisRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis"/> operation.</summary>
internal sealed class LexSenseMorphoSyntaxAnalysisSetHandler : IOperationHandler
{
    internal static readonly LexSenseMorphoSyntaxAnalysisSetHandler Instance = new();
    private LexSenseMorphoSyntaxAnalysisSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis}' requires 'after'.");
        }

        var refId = LexSenseMorphoSyntaxAnalysisSetPayload.Parse(after);

        var (id, lexSense) = TargetResolution.Resolve<ILexSense>(cache, operation, LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(lexSense.MorphoSyntaxAnalysisRA);
        LexSenseMorphoSyntaxAnalysisSetLowering.Apply(cache, lexSense, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(lexSense.MorphoSyntaxAnalysisRA);

        return new ExpectedEffect(id, SnapshotFields.LexSenseMorphoSyntaxAnalysis, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexSense) = TargetResolution.Resolve<ILexSense>(cache, operation, LexSenseMorphoSyntaxAnalysisOperationKinds.SetMorphoSyntaxAnalysis);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(lexSense.MorphoSyntaxAnalysisRA);
        return new ExpectedEffect(id, SnapshotFields.LexSenseMorphoSyntaxAnalysis, current, current);
    }
}

/// <summary>The <see cref="LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis"/> counterpart to
/// <see cref="LexSenseMorphoSyntaxAnalysisSetHandler"/>.</summary>
internal sealed class LexSenseMorphoSyntaxAnalysisClearHandler : IOperationHandler
{
    internal static readonly LexSenseMorphoSyntaxAnalysisClearHandler Instance = new();
    private LexSenseMorphoSyntaxAnalysisClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis}' requires 'after'.");
        }

        LexSenseMorphoSyntaxAnalysisClearPayload.Parse(after);

        var (id, lexSense) = TargetResolution.Resolve<ILexSense>(cache, operation, LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(lexSense.MorphoSyntaxAnalysisRA);
        LexSenseMorphoSyntaxAnalysisClearLowering.Apply(lexSense);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(lexSense.MorphoSyntaxAnalysisRA);

        return new ExpectedEffect(id, SnapshotFields.LexSenseMorphoSyntaxAnalysis, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexSense) = TargetResolution.Resolve<ILexSense>(cache, operation, LexSenseMorphoSyntaxAnalysisOperationKinds.ClearMorphoSyntaxAnalysis);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(lexSense.MorphoSyntaxAnalysisRA);
        return new ExpectedEffect(id, SnapshotFields.LexSenseMorphoSyntaxAnalysis, current, current);
    }
}
