// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoAffixForm.InflectionClasses (rel/col MoInflClass, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoAffixForm.InflectionClasses</c> operation kinds.</summary>
public static class MoAffixFormInflectionClassesOperationKinds
{
    public const string AddRefInflectionClasses = "grammar/moAffixForm/addRefInflectionClasses";
    public const string RemoveRefInflectionClasses = "grammar/moAffixForm/removeRefInflectionClasses";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefInflectionClasses);
        OperationKindRegistry.Register(RemoveRefInflectionClasses);
        OperationHandlerRegistry.Register(AddRefInflectionClasses, MoAffixFormInflectionClassesAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefInflectionClasses, MoAffixFormInflectionClassesRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses"/>
/// and <see cref="MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoAffixFormInflectionClassesMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses"/>: resolves the
/// referenced IMoInflClass and adds it to <c>moAffixForm.InflectionClassesRC</c> (a no-op if already
/// present).</summary>
public static class MoAffixFormInflectionClassesAddRefLowering
{
    public static void Apply(LcmCache cache, IMoAffixForm moAffixForm, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoInflClass>(
            cache, moAffixForm.InflectionClassesRC, memberId, MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses);
}

/// <summary>Lowers <see cref="MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses"/>: resolves the
/// referenced IMoInflClass and removes it from <c>moAffixForm.InflectionClassesRC</c> (a no-op if
/// absent).</summary>
public static class MoAffixFormInflectionClassesRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoAffixForm moAffixForm, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoInflClass>(
            cache, moAffixForm.InflectionClassesRC, memberId, MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses"/> operation.</summary>
internal sealed class MoAffixFormInflectionClassesAddRefHandler : IOperationHandler
{
    internal static readonly MoAffixFormInflectionClassesAddRefHandler Instance = new();
    private MoAffixFormInflectionClassesAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses}' requires 'after'.");
        }

        var memberId = MoAffixFormInflectionClassesMemberPayload.Parse(after, MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses);

        var (id, moAffixForm) = TargetResolution.Resolve<IMoAffixForm>(cache, operation, MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixForm.InflectionClassesRC);
        MoAffixFormInflectionClassesAddRefLowering.Apply(cache, moAffixForm, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixForm.InflectionClassesRC);

        return new ExpectedEffect(id, SnapshotFields.MoAffixFormInflectionClasses, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAffixForm) = TargetResolution.Resolve<IMoAffixForm>(cache, operation, MoAffixFormInflectionClassesOperationKinds.AddRefInflectionClasses);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixForm.InflectionClassesRC);
        return new ExpectedEffect(id, SnapshotFields.MoAffixFormInflectionClasses, current, current);
    }
}

/// <summary>The <see cref="MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses"/> counterpart to
/// <see cref="MoAffixFormInflectionClassesAddRefHandler"/>.</summary>
internal sealed class MoAffixFormInflectionClassesRemoveRefHandler : IOperationHandler
{
    internal static readonly MoAffixFormInflectionClassesRemoveRefHandler Instance = new();
    private MoAffixFormInflectionClassesRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses}' requires 'after'.");
        }

        var memberId = MoAffixFormInflectionClassesMemberPayload.Parse(after, MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses);

        var (id, moAffixForm) = TargetResolution.Resolve<IMoAffixForm>(cache, operation, MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixForm.InflectionClassesRC);
        MoAffixFormInflectionClassesRemoveRefLowering.Apply(cache, moAffixForm, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixForm.InflectionClassesRC);

        return new ExpectedEffect(id, SnapshotFields.MoAffixFormInflectionClasses, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAffixForm) = TargetResolution.Resolve<IMoAffixForm>(cache, operation, MoAffixFormInflectionClassesOperationKinds.RemoveRefInflectionClasses);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixForm.InflectionClassesRC);
        return new ExpectedEffect(id, SnapshotFields.MoAffixFormInflectionClasses, current, current);
    }
}
