// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoAffixAllomorph.PhoneEnv (rel/col PhEnvironment, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoAffixAllomorph.PhoneEnv</c> operation kinds.</summary>
public static class MoAffixAllomorphPhoneEnvOperationKinds
{
    public const string AddRefPhoneEnv = "grammar/moAffixAllomorph/addRefPhoneEnv";
    public const string RemoveRefPhoneEnv = "grammar/moAffixAllomorph/removeRefPhoneEnv";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefPhoneEnv);
        OperationKindRegistry.Register(RemoveRefPhoneEnv);
        OperationHandlerRegistry.Register(AddRefPhoneEnv, MoAffixAllomorphPhoneEnvAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefPhoneEnv, MoAffixAllomorphPhoneEnvRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv"/>
/// and <see cref="MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoAffixAllomorphPhoneEnvMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv"/>: resolves the
/// referenced IPhEnvironment and adds it to <c>moAffixAllomorph.PhoneEnvRC</c> (a no-op if already
/// present).</summary>
public static class MoAffixAllomorphPhoneEnvAddRefLowering
{
    public static void Apply(LcmCache cache, IMoAffixAllomorph moAffixAllomorph, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhEnvironment>(
            cache, moAffixAllomorph.PhoneEnvRC, memberId, MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);
}

/// <summary>Lowers <see cref="MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv"/>: resolves the
/// referenced IPhEnvironment and removes it from <c>moAffixAllomorph.PhoneEnvRC</c> (a no-op if
/// absent).</summary>
public static class MoAffixAllomorphPhoneEnvRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoAffixAllomorph moAffixAllomorph, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhEnvironment>(
            cache, moAffixAllomorph.PhoneEnvRC, memberId, MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv"/> operation.</summary>
internal sealed class MoAffixAllomorphPhoneEnvAddRefHandler : IOperationHandler
{
    internal static readonly MoAffixAllomorphPhoneEnvAddRefHandler Instance = new();
    private MoAffixAllomorphPhoneEnvAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv}' requires 'after'.");
        }

        var memberId = MoAffixAllomorphPhoneEnvMemberPayload.Parse(after, MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);

        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PhoneEnvRC);
        MoAffixAllomorphPhoneEnvAddRefLowering.Apply(cache, moAffixAllomorph, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PhoneEnvRC);

        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPhoneEnv, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PhoneEnvRC);
        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPhoneEnv, current, current);
    }
}

/// <summary>The <see cref="MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv"/> counterpart to
/// <see cref="MoAffixAllomorphPhoneEnvAddRefHandler"/>.</summary>
internal sealed class MoAffixAllomorphPhoneEnvRemoveRefHandler : IOperationHandler
{
    internal static readonly MoAffixAllomorphPhoneEnvRemoveRefHandler Instance = new();
    private MoAffixAllomorphPhoneEnvRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv}' requires 'after'.");
        }

        var memberId = MoAffixAllomorphPhoneEnvMemberPayload.Parse(after, MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);

        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PhoneEnvRC);
        MoAffixAllomorphPhoneEnvRemoveRefLowering.Apply(cache, moAffixAllomorph, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PhoneEnvRC);

        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPhoneEnv, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PhoneEnvRC);
        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPhoneEnv, current, current);
    }
}
