// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoAlloAdhocProhib.FirstAllomorph (rel/atomic MoForm, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoAlloAdhocProhib.FirstAllomorph</c> operation kinds.</summary>
public static class MoAlloAdhocProhibFirstAllomorphOperationKinds
{
    public const string SetFirstAllomorph = "grammar/moAlloAdhocProhib/setFirstAllomorph";
    public const string ClearFirstAllomorph = "grammar/moAlloAdhocProhib/clearFirstAllomorph";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetFirstAllomorph);
        OperationKindRegistry.Register(ClearFirstAllomorph);
        OperationHandlerRegistry.Register(SetFirstAllomorph, MoAlloAdhocProhibFirstAllomorphSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearFirstAllomorph, MoAlloAdhocProhibFirstAllomorphClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoAlloAdhocProhibFirstAllomorphSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoAlloAdhocProhibFirstAllomorphClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph);
    }
}

/// <summary>Lowers <see cref="MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph"/>: resolves the
/// referenced IMoForm and assigns it to <c>moAlloAdhocProhib.FirstAllomorphRA</c>.</summary>
public static class MoAlloAdhocProhibFirstAllomorphSetLowering
{
    public static void Apply(LcmCache cache, IMoAlloAdhocProhib moAlloAdhocProhib, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IMoForm>(
            cache, value => moAlloAdhocProhib.FirstAllomorphRA = value, refId, MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph);
}

/// <summary>Lowers <see cref="MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph"/>: detaches
/// <c>moAlloAdhocProhib.FirstAllomorphRA</c>.</summary>
public static class MoAlloAdhocProhibFirstAllomorphClearLowering
{
    public static void Apply(IMoAlloAdhocProhib moAlloAdhocProhib) =>
        ReferenceFieldLowering.ApplyClear<IMoForm>(value => moAlloAdhocProhib.FirstAllomorphRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph"/> operation.</summary>
internal sealed class MoAlloAdhocProhibFirstAllomorphSetHandler : IOperationHandler
{
    internal static readonly MoAlloAdhocProhibFirstAllomorphSetHandler Instance = new();
    private MoAlloAdhocProhibFirstAllomorphSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph}' requires 'after'.");
        }

        var refId = MoAlloAdhocProhibFirstAllomorphSetPayload.Parse(after);

        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.FirstAllomorphRA);
        MoAlloAdhocProhibFirstAllomorphSetLowering.Apply(cache, moAlloAdhocProhib, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.FirstAllomorphRA);

        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibFirstAllomorph, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibFirstAllomorphOperationKinds.SetFirstAllomorph);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.FirstAllomorphRA);
        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibFirstAllomorph, current, current);
    }
}

/// <summary>The <see cref="MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph"/> counterpart to
/// <see cref="MoAlloAdhocProhibFirstAllomorphSetHandler"/>.</summary>
internal sealed class MoAlloAdhocProhibFirstAllomorphClearHandler : IOperationHandler
{
    internal static readonly MoAlloAdhocProhibFirstAllomorphClearHandler Instance = new();
    private MoAlloAdhocProhibFirstAllomorphClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph}' requires 'after'.");
        }

        MoAlloAdhocProhibFirstAllomorphClearPayload.Parse(after);

        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.FirstAllomorphRA);
        MoAlloAdhocProhibFirstAllomorphClearLowering.Apply(moAlloAdhocProhib);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.FirstAllomorphRA);

        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibFirstAllomorph, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibFirstAllomorphOperationKinds.ClearFirstAllomorph);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.FirstAllomorphRA);
        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibFirstAllomorph, current, current);
    }
}
