// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoCompoundRule.ToProdRestrict (rel/col CmPossibility, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoCompoundRule.ToProdRestrict</c> operation kinds.</summary>
public static class MoCompoundRuleToProdRestrictOperationKinds
{
    public const string AddRefToProdRestrict = "grammar/moCompoundRule/addRefToProdRestrict";
    public const string RemoveRefToProdRestrict = "grammar/moCompoundRule/removeRefToProdRestrict";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefToProdRestrict);
        OperationKindRegistry.Register(RemoveRefToProdRestrict);
        OperationHandlerRegistry.Register(AddRefToProdRestrict, MoCompoundRuleToProdRestrictAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefToProdRestrict, MoCompoundRuleToProdRestrictRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict"/>
/// and <see cref="MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoCompoundRuleToProdRestrictMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict"/>: resolves the
/// referenced ICmPossibility and adds it to <c>moCompoundRule.ToProdRestrictRC</c> (a no-op if already
/// present).</summary>
public static class MoCompoundRuleToProdRestrictAddRefLowering
{
    public static void Apply(LcmCache cache, IMoCompoundRule moCompoundRule, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ICmPossibility>(
            cache, moCompoundRule.ToProdRestrictRC, memberId, MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict);
}

/// <summary>Lowers <see cref="MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict"/>: resolves the
/// referenced ICmPossibility and removes it from <c>moCompoundRule.ToProdRestrictRC</c> (a no-op if
/// absent).</summary>
public static class MoCompoundRuleToProdRestrictRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoCompoundRule moCompoundRule, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ICmPossibility>(
            cache, moCompoundRule.ToProdRestrictRC, memberId, MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict"/> operation.</summary>
internal sealed class MoCompoundRuleToProdRestrictAddRefHandler : IOperationHandler
{
    internal static readonly MoCompoundRuleToProdRestrictAddRefHandler Instance = new();
    private MoCompoundRuleToProdRestrictAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict}' requires 'after'.");
        }

        var memberId = MoCompoundRuleToProdRestrictMemberPayload.Parse(after, MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict);

        var (id, moCompoundRule) = TargetResolution.Resolve<IMoCompoundRule>(cache, operation, MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moCompoundRule.ToProdRestrictRC);
        MoCompoundRuleToProdRestrictAddRefLowering.Apply(cache, moCompoundRule, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moCompoundRule.ToProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoCompoundRuleToProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moCompoundRule) = TargetResolution.Resolve<IMoCompoundRule>(cache, operation, MoCompoundRuleToProdRestrictOperationKinds.AddRefToProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moCompoundRule.ToProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoCompoundRuleToProdRestrict, current, current);
    }
}

/// <summary>The <see cref="MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict"/> counterpart to
/// <see cref="MoCompoundRuleToProdRestrictAddRefHandler"/>.</summary>
internal sealed class MoCompoundRuleToProdRestrictRemoveRefHandler : IOperationHandler
{
    internal static readonly MoCompoundRuleToProdRestrictRemoveRefHandler Instance = new();
    private MoCompoundRuleToProdRestrictRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict}' requires 'after'.");
        }

        var memberId = MoCompoundRuleToProdRestrictMemberPayload.Parse(after, MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict);

        var (id, moCompoundRule) = TargetResolution.Resolve<IMoCompoundRule>(cache, operation, MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moCompoundRule.ToProdRestrictRC);
        MoCompoundRuleToProdRestrictRemoveRefLowering.Apply(cache, moCompoundRule, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moCompoundRule.ToProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoCompoundRuleToProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moCompoundRule) = TargetResolution.Resolve<IMoCompoundRule>(cache, operation, MoCompoundRuleToProdRestrictOperationKinds.RemoveRefToProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moCompoundRule.ToProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoCompoundRuleToProdRestrict, current, current);
    }
}
