// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoDerivAffMsa.FromStemName (rel/atomic MoStemName, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoDerivAffMsa.FromStemName</c> operation kinds.</summary>
public static class MoDerivAffMsaFromStemNameOperationKinds
{
    public const string SetFromStemName = "grammar/moDerivAffMsa/setFromStemName";
    public const string ClearFromStemName = "grammar/moDerivAffMsa/clearFromStemName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetFromStemName);
        OperationKindRegistry.Register(ClearFromStemName);
        OperationHandlerRegistry.Register(SetFromStemName, MoDerivAffMsaFromStemNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearFromStemName, MoDerivAffMsaFromStemNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoDerivAffMsaFromStemNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoDerivAffMsaFromStemNameClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName);
    }
}

/// <summary>Lowers <see cref="MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName"/>: resolves the
/// referenced IMoStemName and assigns it to <c>moDerivAffMsa.FromStemNameRA</c>.</summary>
public static class MoDerivAffMsaFromStemNameSetLowering
{
    public static void Apply(LcmCache cache, IMoDerivAffMsa moDerivAffMsa, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IMoStemName>(
            cache, value => moDerivAffMsa.FromStemNameRA = value, refId, MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName);
}

/// <summary>Lowers <see cref="MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName"/>: detaches
/// <c>moDerivAffMsa.FromStemNameRA</c>.</summary>
public static class MoDerivAffMsaFromStemNameClearLowering
{
    public static void Apply(IMoDerivAffMsa moDerivAffMsa) =>
        ReferenceFieldLowering.ApplyClear<IMoStemName>(value => moDerivAffMsa.FromStemNameRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName"/> operation.</summary>
internal sealed class MoDerivAffMsaFromStemNameSetHandler : IOperationHandler
{
    internal static readonly MoDerivAffMsaFromStemNameSetHandler Instance = new();
    private MoDerivAffMsaFromStemNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName}' requires 'after'.");
        }

        var refId = MoDerivAffMsaFromStemNameSetPayload.Parse(after);

        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromStemNameRA);
        MoDerivAffMsaFromStemNameSetLowering.Apply(cache, moDerivAffMsa, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromStemNameRA);

        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromStemName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromStemNameOperationKinds.SetFromStemName);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromStemNameRA);
        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromStemName, current, current);
    }
}

/// <summary>The <see cref="MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName"/> counterpart to
/// <see cref="MoDerivAffMsaFromStemNameSetHandler"/>.</summary>
internal sealed class MoDerivAffMsaFromStemNameClearHandler : IOperationHandler
{
    internal static readonly MoDerivAffMsaFromStemNameClearHandler Instance = new();
    private MoDerivAffMsaFromStemNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName}' requires 'after'.");
        }

        MoDerivAffMsaFromStemNameClearPayload.Parse(after);

        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromStemNameRA);
        MoDerivAffMsaFromStemNameClearLowering.Apply(moDerivAffMsa);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromStemNameRA);

        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromStemName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromStemNameOperationKinds.ClearFromStemName);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromStemNameRA);
        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromStemName, current, current);
    }
}
