// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoDerivAffMsa.FromProdRestrict (rel/col CmPossibility, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoDerivAffMsa.FromProdRestrict</c> operation kinds.</summary>
public static class MoDerivAffMsaFromProdRestrictOperationKinds
{
    public const string AddRefFromProdRestrict = "grammar/moDerivAffMsa/addRefFromProdRestrict";
    public const string RemoveRefFromProdRestrict = "grammar/moDerivAffMsa/removeRefFromProdRestrict";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefFromProdRestrict);
        OperationKindRegistry.Register(RemoveRefFromProdRestrict);
        OperationHandlerRegistry.Register(AddRefFromProdRestrict, MoDerivAffMsaFromProdRestrictAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefFromProdRestrict, MoDerivAffMsaFromProdRestrictRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict"/>
/// and <see cref="MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoDerivAffMsaFromProdRestrictMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict"/>: resolves the
/// referenced ICmPossibility and adds it to <c>moDerivAffMsa.FromProdRestrictRC</c> (a no-op if already
/// present).</summary>
public static class MoDerivAffMsaFromProdRestrictAddRefLowering
{
    public static void Apply(LcmCache cache, IMoDerivAffMsa moDerivAffMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ICmPossibility>(
            cache, moDerivAffMsa.FromProdRestrictRC, memberId, MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);
}

/// <summary>Lowers <see cref="MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict"/>: resolves the
/// referenced ICmPossibility and removes it from <c>moDerivAffMsa.FromProdRestrictRC</c> (a no-op if
/// absent).</summary>
public static class MoDerivAffMsaFromProdRestrictRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoDerivAffMsa moDerivAffMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ICmPossibility>(
            cache, moDerivAffMsa.FromProdRestrictRC, memberId, MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict"/> operation.</summary>
internal sealed class MoDerivAffMsaFromProdRestrictAddRefHandler : IOperationHandler
{
    internal static readonly MoDerivAffMsaFromProdRestrictAddRefHandler Instance = new();
    private MoDerivAffMsaFromProdRestrictAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict}' requires 'after'.");
        }

        var memberId = MoDerivAffMsaFromProdRestrictMemberPayload.Parse(after, MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);

        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromProdRestrictRC);
        MoDerivAffMsaFromProdRestrictAddRefLowering.Apply(cache, moDerivAffMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromProdRestrict, current, current);
    }
}

/// <summary>The <see cref="MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict"/> counterpart to
/// <see cref="MoDerivAffMsaFromProdRestrictAddRefHandler"/>.</summary>
internal sealed class MoDerivAffMsaFromProdRestrictRemoveRefHandler : IOperationHandler
{
    internal static readonly MoDerivAffMsaFromProdRestrictRemoveRefHandler Instance = new();
    private MoDerivAffMsaFromProdRestrictRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict}' requires 'after'.");
        }

        var memberId = MoDerivAffMsaFromProdRestrictMemberPayload.Parse(after, MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);

        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromProdRestrictRC);
        MoDerivAffMsaFromProdRestrictRemoveRefLowering.Apply(cache, moDerivAffMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moDerivAffMsa.FromProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaFromProdRestrict, current, current);
    }
}
