// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoDerivAffMsa.ToPartOfSpeech (rel/atomic PartOfSpeech, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoDerivAffMsa.ToPartOfSpeech</c> operation kinds.</summary>
public static class MoDerivAffMsaToPartOfSpeechOperationKinds
{
    public const string SetToPartOfSpeech = "grammar/moDerivAffMsa/setToPartOfSpeech";
    public const string ClearToPartOfSpeech = "grammar/moDerivAffMsa/clearToPartOfSpeech";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetToPartOfSpeech);
        OperationKindRegistry.Register(ClearToPartOfSpeech);
        OperationHandlerRegistry.Register(SetToPartOfSpeech, MoDerivAffMsaToPartOfSpeechSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearToPartOfSpeech, MoDerivAffMsaToPartOfSpeechClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoDerivAffMsaToPartOfSpeechSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoDerivAffMsaToPartOfSpeechClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech);
    }
}

/// <summary>Lowers <see cref="MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech"/>: resolves the
/// referenced IPartOfSpeech and assigns it to <c>moDerivAffMsa.ToPartOfSpeechRA</c>.</summary>
public static class MoDerivAffMsaToPartOfSpeechSetLowering
{
    public static void Apply(LcmCache cache, IMoDerivAffMsa moDerivAffMsa, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IPartOfSpeech>(
            cache, value => moDerivAffMsa.ToPartOfSpeechRA = value, refId, MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech);
}

/// <summary>Lowers <see cref="MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech"/>: detaches
/// <c>moDerivAffMsa.ToPartOfSpeechRA</c>.</summary>
public static class MoDerivAffMsaToPartOfSpeechClearLowering
{
    public static void Apply(IMoDerivAffMsa moDerivAffMsa) =>
        ReferenceFieldLowering.ApplyClear<IPartOfSpeech>(value => moDerivAffMsa.ToPartOfSpeechRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech"/> operation.</summary>
internal sealed class MoDerivAffMsaToPartOfSpeechSetHandler : IOperationHandler
{
    internal static readonly MoDerivAffMsaToPartOfSpeechSetHandler Instance = new();
    private MoDerivAffMsaToPartOfSpeechSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech}' requires 'after'.");
        }

        var refId = MoDerivAffMsaToPartOfSpeechSetPayload.Parse(after);

        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.ToPartOfSpeechRA);
        MoDerivAffMsaToPartOfSpeechSetLowering.Apply(cache, moDerivAffMsa, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.ToPartOfSpeechRA);

        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaToPartOfSpeech, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaToPartOfSpeechOperationKinds.SetToPartOfSpeech);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.ToPartOfSpeechRA);
        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaToPartOfSpeech, current, current);
    }
}

/// <summary>The <see cref="MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech"/> counterpart to
/// <see cref="MoDerivAffMsaToPartOfSpeechSetHandler"/>.</summary>
internal sealed class MoDerivAffMsaToPartOfSpeechClearHandler : IOperationHandler
{
    internal static readonly MoDerivAffMsaToPartOfSpeechClearHandler Instance = new();
    private MoDerivAffMsaToPartOfSpeechClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech}' requires 'after'.");
        }

        MoDerivAffMsaToPartOfSpeechClearPayload.Parse(after);

        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.ToPartOfSpeechRA);
        MoDerivAffMsaToPartOfSpeechClearLowering.Apply(moDerivAffMsa);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.ToPartOfSpeechRA);

        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaToPartOfSpeech, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moDerivAffMsa) = TargetResolution.Resolve<IMoDerivAffMsa>(cache, operation, MoDerivAffMsaToPartOfSpeechOperationKinds.ClearToPartOfSpeech);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moDerivAffMsa.ToPartOfSpeechRA);
        return new ExpectedEffect(id, SnapshotFields.MoDerivAffMsaToPartOfSpeech, current, current);
    }
}
