// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoEndoCompound.HeadLast (basic Boolean, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoEndoCompound.HeadLast</c> operation kinds.</summary>
public static class MoEndoCompoundHeadLastOperationKinds
{
    public const string SetHeadLast = "grammar/moEndoCompound/setHeadLast";
    public const string ClearHeadLast = "grammar/moEndoCompound/clearHeadLast";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetHeadLast);
        OperationKindRegistry.Register(ClearHeadLast);
        OperationHandlerRegistry.Register(SetHeadLast, MoEndoCompoundHeadLastSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearHeadLast, MoEndoCompoundHeadLastClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoEndoCompoundHeadLastOperationKinds.SetHeadLast"/>:
/// <c>{ "value": true|false }</c>. Closed: any other property is rejected.</summary>
public static class MoEndoCompoundHeadLastSetPayload
{
    private static readonly string[] AllowedProperties = { "value" };

    public static bool Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoEndoCompoundHeadLastOperationKinds.SetHeadLast);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoEndoCompoundHeadLastOperationKinds.SetHeadLast);

        return ClosedPayloadParsing.GetRequiredBoolean(after, "value", MoEndoCompoundHeadLastOperationKinds.SetHeadLast);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoEndoCompoundHeadLastOperationKinds.ClearHeadLast"/>:
/// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear.</summary>
public static class MoEndoCompoundHeadLastClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoEndoCompoundHeadLastOperationKinds.ClearHeadLast);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoEndoCompoundHeadLastOperationKinds.ClearHeadLast);
    }
}

/// <summary>Lowers <see cref="MoEndoCompoundHeadLastOperationKinds.SetHeadLast"/>: the one LibLCM
/// write it performs, <c>moEndoCompound.HeadLast = value</c>.</summary>
public static class MoEndoCompoundHeadLastSetLowering
{
    public static void Apply(IMoEndoCompound moEndoCompound, bool value) => moEndoCompound.HeadLast = value;
}

/// <summary>Lowers <see cref="MoEndoCompoundHeadLastOperationKinds.ClearHeadLast"/>: resets
/// <c>moEndoCompound.HeadLast</c> to <c>false</c>.</summary>
public static class MoEndoCompoundHeadLastClearLowering
{
    public static void Apply(IMoEndoCompound moEndoCompound) => moEndoCompound.HeadLast = false;
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoEndoCompoundHeadLastOperationKinds.SetHeadLast"/> operation.</summary>
internal sealed class MoEndoCompoundHeadLastSetHandler : IOperationHandler
{
    internal static readonly MoEndoCompoundHeadLastSetHandler Instance = new();
    private MoEndoCompoundHeadLastSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoEndoCompoundHeadLastOperationKinds.SetHeadLast}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoEndoCompoundHeadLastOperationKinds.SetHeadLast}' requires 'after'.");
        }

        var desired = MoEndoCompoundHeadLastSetPayload.Parse(after);

        var (id, moEndoCompound) = TargetResolution.Resolve<IMoEndoCompound>(cache, operation, MoEndoCompoundHeadLastOperationKinds.SetHeadLast);
        touchedTargets.Add(id);

        var before = ReadField(cache, moEndoCompound);
        MoEndoCompoundHeadLastSetLowering.Apply(moEndoCompound, desired);
        var afterValue = ReadField(cache, moEndoCompound);

        return new ExpectedEffect(id, SnapshotFields.MoEndoCompoundHeadLast, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moEndoCompound) = TargetResolution.Resolve<IMoEndoCompound>(cache, operation, MoEndoCompoundHeadLastOperationKinds.SetHeadLast);
        var current = ReadField(cache, moEndoCompound);
        return new ExpectedEffect(id, SnapshotFields.MoEndoCompoundHeadLast, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoEndoCompound moEndoCompound) =>
        MoEndoCompoundSnapshotter.Snapshot(cache, moEndoCompound).AlternativesFields
            .TryGetValue(SnapshotFields.MoEndoCompoundHeadLast, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoEndoCompoundHeadLastOperationKinds.ClearHeadLast"/> counterpart to
/// <see cref="MoEndoCompoundHeadLastSetHandler"/>.</summary>
internal sealed class MoEndoCompoundHeadLastClearHandler : IOperationHandler
{
    internal static readonly MoEndoCompoundHeadLastClearHandler Instance = new();
    private MoEndoCompoundHeadLastClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoEndoCompoundHeadLastOperationKinds.ClearHeadLast}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoEndoCompoundHeadLastOperationKinds.ClearHeadLast}' requires 'after'.");
        }

        MoEndoCompoundHeadLastClearPayload.Parse(after);

        var (id, moEndoCompound) = TargetResolution.Resolve<IMoEndoCompound>(cache, operation, MoEndoCompoundHeadLastOperationKinds.ClearHeadLast);
        touchedTargets.Add(id);

        var before = ReadField(cache, moEndoCompound);
        MoEndoCompoundHeadLastClearLowering.Apply(moEndoCompound);
        var afterValue = ReadField(cache, moEndoCompound);

        return new ExpectedEffect(id, SnapshotFields.MoEndoCompoundHeadLast, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moEndoCompound) = TargetResolution.Resolve<IMoEndoCompound>(cache, operation, MoEndoCompoundHeadLastOperationKinds.ClearHeadLast);
        var current = ReadField(cache, moEndoCompound);
        return new ExpectedEffect(id, SnapshotFields.MoEndoCompoundHeadLast, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoEndoCompound moEndoCompound) =>
        MoEndoCompoundSnapshotter.Snapshot(cache, moEndoCompound).AlternativesFields
            .TryGetValue(SnapshotFields.MoEndoCompoundHeadLast, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
