// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffixTemplate.Final (basic Boolean, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffixTemplate.Final</c> operation kinds.</summary>
public static class MoInflAffixTemplateFinalOperationKinds
{
    public const string SetFinal = "grammar/moInflAffixTemplate/setFinal";
    public const string ClearFinal = "grammar/moInflAffixTemplate/clearFinal";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetFinal);
        OperationKindRegistry.Register(ClearFinal);
        OperationHandlerRegistry.Register(SetFinal, MoInflAffixTemplateFinalSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearFinal, MoInflAffixTemplateFinalClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixTemplateFinalOperationKinds.SetFinal"/>:
/// <c>{ "value": true|false }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffixTemplateFinalSetPayload
{
    private static readonly string[] AllowedProperties = { "value" };

    public static bool Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixTemplateFinalOperationKinds.SetFinal);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixTemplateFinalOperationKinds.SetFinal);

        return ClosedPayloadParsing.GetRequiredBoolean(after, "value", MoInflAffixTemplateFinalOperationKinds.SetFinal);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixTemplateFinalOperationKinds.ClearFinal"/>:
/// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear.</summary>
public static class MoInflAffixTemplateFinalClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixTemplateFinalOperationKinds.ClearFinal);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixTemplateFinalOperationKinds.ClearFinal);
    }
}

/// <summary>Lowers <see cref="MoInflAffixTemplateFinalOperationKinds.SetFinal"/>: the one LibLCM
/// write it performs, <c>moInflAffixTemplate.Final = value</c>.</summary>
public static class MoInflAffixTemplateFinalSetLowering
{
    public static void Apply(IMoInflAffixTemplate moInflAffixTemplate, bool value) => moInflAffixTemplate.Final = value;
}

/// <summary>Lowers <see cref="MoInflAffixTemplateFinalOperationKinds.ClearFinal"/>: resets
/// <c>moInflAffixTemplate.Final</c> to <c>false</c>.</summary>
public static class MoInflAffixTemplateFinalClearLowering
{
    public static void Apply(IMoInflAffixTemplate moInflAffixTemplate) => moInflAffixTemplate.Final = false;
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixTemplateFinalOperationKinds.SetFinal"/> operation.</summary>
internal sealed class MoInflAffixTemplateFinalSetHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateFinalSetHandler Instance = new();
    private MoInflAffixTemplateFinalSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateFinalOperationKinds.SetFinal}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateFinalOperationKinds.SetFinal}' requires 'after'.");
        }

        var desired = MoInflAffixTemplateFinalSetPayload.Parse(after);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateFinalOperationKinds.SetFinal);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixTemplate);
        MoInflAffixTemplateFinalSetLowering.Apply(moInflAffixTemplate, desired);
        var afterValue = ReadField(cache, moInflAffixTemplate);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateFinal, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateFinalOperationKinds.SetFinal);
        var current = ReadField(cache, moInflAffixTemplate);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateFinal, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate) =>
        MoInflAffixTemplateSnapshotter.Snapshot(cache, moInflAffixTemplate).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixTemplateFinal, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoInflAffixTemplateFinalOperationKinds.ClearFinal"/> counterpart to
/// <see cref="MoInflAffixTemplateFinalSetHandler"/>.</summary>
internal sealed class MoInflAffixTemplateFinalClearHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateFinalClearHandler Instance = new();
    private MoInflAffixTemplateFinalClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateFinalOperationKinds.ClearFinal}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateFinalOperationKinds.ClearFinal}' requires 'after'.");
        }

        MoInflAffixTemplateFinalClearPayload.Parse(after);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateFinalOperationKinds.ClearFinal);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixTemplate);
        MoInflAffixTemplateFinalClearLowering.Apply(moInflAffixTemplate);
        var afterValue = ReadField(cache, moInflAffixTemplate);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateFinal, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateFinalOperationKinds.ClearFinal);
        var current = ReadField(cache, moInflAffixTemplate);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateFinal, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate) =>
        MoInflAffixTemplateSnapshotter.Snapshot(cache, moInflAffixTemplate).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixTemplateFinal, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
