// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffMsa.FromProdRestrict (rel/col CmPossibility, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffMsa.FromProdRestrict</c> operation kinds.</summary>
public static class MoInflAffMsaFromProdRestrictOperationKinds
{
    public const string AddRefFromProdRestrict = "grammar/moInflAffMsa/addRefFromProdRestrict";
    public const string RemoveRefFromProdRestrict = "grammar/moInflAffMsa/removeRefFromProdRestrict";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefFromProdRestrict);
        OperationKindRegistry.Register(RemoveRefFromProdRestrict);
        OperationHandlerRegistry.Register(AddRefFromProdRestrict, MoInflAffMsaFromProdRestrictAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefFromProdRestrict, MoInflAffMsaFromProdRestrictRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict"/>
/// and <see cref="MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffMsaFromProdRestrictMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict"/>: resolves the
/// referenced ICmPossibility and adds it to <c>moInflAffMsa.FromProdRestrictRC</c> (a no-op if already
/// present).</summary>
public static class MoInflAffMsaFromProdRestrictAddRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffMsa moInflAffMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ICmPossibility>(
            cache, moInflAffMsa.FromProdRestrictRC, memberId, MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);
}

/// <summary>Lowers <see cref="MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict"/>: resolves the
/// referenced ICmPossibility and removes it from <c>moInflAffMsa.FromProdRestrictRC</c> (a no-op if
/// absent).</summary>
public static class MoInflAffMsaFromProdRestrictRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffMsa moInflAffMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ICmPossibility>(
            cache, moInflAffMsa.FromProdRestrictRC, memberId, MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict"/> operation.</summary>
internal sealed class MoInflAffMsaFromProdRestrictAddRefHandler : IOperationHandler
{
    internal static readonly MoInflAffMsaFromProdRestrictAddRefHandler Instance = new();
    private MoInflAffMsaFromProdRestrictAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict}' requires 'after'.");
        }

        var memberId = MoInflAffMsaFromProdRestrictMemberPayload.Parse(after, MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);

        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.FromProdRestrictRC);
        MoInflAffMsaFromProdRestrictAddRefLowering.Apply(cache, moInflAffMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.FromProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaFromProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaFromProdRestrictOperationKinds.AddRefFromProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.FromProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaFromProdRestrict, current, current);
    }
}

/// <summary>The <see cref="MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict"/> counterpart to
/// <see cref="MoInflAffMsaFromProdRestrictAddRefHandler"/>.</summary>
internal sealed class MoInflAffMsaFromProdRestrictRemoveRefHandler : IOperationHandler
{
    internal static readonly MoInflAffMsaFromProdRestrictRemoveRefHandler Instance = new();
    private MoInflAffMsaFromProdRestrictRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict}' requires 'after'.");
        }

        var memberId = MoInflAffMsaFromProdRestrictMemberPayload.Parse(after, MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);

        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.FromProdRestrictRC);
        MoInflAffMsaFromProdRestrictRemoveRefLowering.Apply(cache, moInflAffMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.FromProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaFromProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaFromProdRestrictOperationKinds.RemoveRefFromProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.FromProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaFromProdRestrict, current, current);
    }
}
