// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffMsa.PartOfSpeech (rel/atomic PartOfSpeech, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffMsa.PartOfSpeech</c> operation kinds.</summary>
public static class MoInflAffMsaPartOfSpeechOperationKinds
{
    public const string SetPartOfSpeech = "grammar/moInflAffMsa/setPartOfSpeech";
    public const string ClearPartOfSpeech = "grammar/moInflAffMsa/clearPartOfSpeech";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetPartOfSpeech);
        OperationKindRegistry.Register(ClearPartOfSpeech);
        OperationHandlerRegistry.Register(SetPartOfSpeech, MoInflAffMsaPartOfSpeechSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearPartOfSpeech, MoInflAffMsaPartOfSpeechClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffMsaPartOfSpeechSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoInflAffMsaPartOfSpeechClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
    }
}

/// <summary>Lowers <see cref="MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech"/>: resolves the
/// referenced IPartOfSpeech and assigns it to <c>moInflAffMsa.PartOfSpeechRA</c>.</summary>
public static class MoInflAffMsaPartOfSpeechSetLowering
{
    public static void Apply(LcmCache cache, IMoInflAffMsa moInflAffMsa, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IPartOfSpeech>(
            cache, value => moInflAffMsa.PartOfSpeechRA = value, refId, MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
}

/// <summary>Lowers <see cref="MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech"/>: detaches
/// <c>moInflAffMsa.PartOfSpeechRA</c>.</summary>
public static class MoInflAffMsaPartOfSpeechClearLowering
{
    public static void Apply(IMoInflAffMsa moInflAffMsa) =>
        ReferenceFieldLowering.ApplyClear<IPartOfSpeech>(value => moInflAffMsa.PartOfSpeechRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech"/> operation.</summary>
internal sealed class MoInflAffMsaPartOfSpeechSetHandler : IOperationHandler
{
    internal static readonly MoInflAffMsaPartOfSpeechSetHandler Instance = new();
    private MoInflAffMsaPartOfSpeechSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech}' requires 'after'.");
        }

        var refId = MoInflAffMsaPartOfSpeechSetPayload.Parse(after);

        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moInflAffMsa.PartOfSpeechRA);
        MoInflAffMsaPartOfSpeechSetLowering.Apply(cache, moInflAffMsa, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moInflAffMsa.PartOfSpeechRA);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaPartOfSpeech, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moInflAffMsa.PartOfSpeechRA);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaPartOfSpeech, current, current);
    }
}

/// <summary>The <see cref="MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech"/> counterpart to
/// <see cref="MoInflAffMsaPartOfSpeechSetHandler"/>.</summary>
internal sealed class MoInflAffMsaPartOfSpeechClearHandler : IOperationHandler
{
    internal static readonly MoInflAffMsaPartOfSpeechClearHandler Instance = new();
    private MoInflAffMsaPartOfSpeechClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech}' requires 'after'.");
        }

        MoInflAffMsaPartOfSpeechClearPayload.Parse(after);

        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moInflAffMsa.PartOfSpeechRA);
        MoInflAffMsaPartOfSpeechClearLowering.Apply(moInflAffMsa);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moInflAffMsa.PartOfSpeechRA);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaPartOfSpeech, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moInflAffMsa.PartOfSpeechRA);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaPartOfSpeech, current, current);
    }
}
