// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflClass.Abbreviation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflClass.Abbreviation</c> operation kinds.</summary>
public static class MoInflClassAbbreviationOperationKinds
{
    public const string SetAbbreviation = "grammar/moInflClass/setAbbreviation";
    public const string ClearAbbreviation = "grammar/moInflClass/clearAbbreviation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetAbbreviation);
        OperationKindRegistry.Register(ClearAbbreviation);
        OperationHandlerRegistry.Register(SetAbbreviation, MoInflClassAbbreviationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearAbbreviation, MoInflClassAbbreviationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflClassAbbreviationOperationKinds.SetAbbreviation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class MoInflClassAbbreviationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflClassAbbreviationOperationKinds.SetAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflClassAbbreviationOperationKinds.SetAbbreviation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", MoInflClassAbbreviationOperationKinds.SetAbbreviation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", MoInflClassAbbreviationOperationKinds.SetAbbreviation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflClassAbbreviationOperationKinds.ClearAbbreviation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class MoInflClassAbbreviationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflClassAbbreviationOperationKinds.ClearAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflClassAbbreviationOperationKinds.ClearAbbreviation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", MoInflClassAbbreviationOperationKinds.ClearAbbreviation);
    }
}

/// <summary>Lowers <see cref="MoInflClassAbbreviationOperationKinds.SetAbbreviation"/>: sets one
/// writing-system alternative of <c>moInflClass.Abbreviation</c>.</summary>
public static class MoInflClassAbbreviationSetLowering
{
    public static void Apply(LcmCache cache, IMoInflClass moInflClass, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, moInflClass.Abbreviation, writingSystemTag, text, MoInflClassAbbreviationOperationKinds.SetAbbreviation);
}

/// <summary>Lowers <see cref="MoInflClassAbbreviationOperationKinds.ClearAbbreviation"/>: clears one
/// writing-system alternative of <c>moInflClass.Abbreviation</c>.</summary>
public static class MoInflClassAbbreviationClearLowering
{
    public static void Apply(LcmCache cache, IMoInflClass moInflClass, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, moInflClass.Abbreviation, writingSystemTag, MoInflClassAbbreviationOperationKinds.ClearAbbreviation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflClassAbbreviationOperationKinds.SetAbbreviation"/> operation.</summary>
internal sealed class MoInflClassAbbreviationSetHandler : IOperationHandler
{
    internal static readonly MoInflClassAbbreviationSetHandler Instance = new();
    private MoInflClassAbbreviationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflClassAbbreviationOperationKinds.SetAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflClassAbbreviationOperationKinds.SetAbbreviation}' requires 'after'.");
        }

        var (writingSystemTag, text) = MoInflClassAbbreviationSetPayload.Parse(after);

        var (id, moInflClass) = TargetResolution.Resolve<IMoInflClass>(cache, operation, MoInflClassAbbreviationOperationKinds.SetAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflClass);
        MoInflClassAbbreviationSetLowering.Apply(cache, moInflClass, writingSystemTag, text);
        var afterValue = ReadField(cache, moInflClass);

        return new ExpectedEffect(id, SnapshotFields.MoInflClassAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflClass) = TargetResolution.Resolve<IMoInflClass>(cache, operation, MoInflClassAbbreviationOperationKinds.SetAbbreviation);
        var current = ReadField(cache, moInflClass);
        return new ExpectedEffect(id, SnapshotFields.MoInflClassAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflClass moInflClass) =>
        MoInflClassSnapshotter.Snapshot(cache, moInflClass).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflClassAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoInflClassAbbreviationOperationKinds.ClearAbbreviation"/> counterpart to
/// <see cref="MoInflClassAbbreviationSetHandler"/>.</summary>
internal sealed class MoInflClassAbbreviationClearHandler : IOperationHandler
{
    internal static readonly MoInflClassAbbreviationClearHandler Instance = new();
    private MoInflClassAbbreviationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflClassAbbreviationOperationKinds.ClearAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflClassAbbreviationOperationKinds.ClearAbbreviation}' requires 'after'.");
        }

        var writingSystemTag = MoInflClassAbbreviationClearPayload.Parse(after);

        var (id, moInflClass) = TargetResolution.Resolve<IMoInflClass>(cache, operation, MoInflClassAbbreviationOperationKinds.ClearAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflClass);
        MoInflClassAbbreviationClearLowering.Apply(cache, moInflClass, writingSystemTag);
        var afterValue = ReadField(cache, moInflClass);

        return new ExpectedEffect(id, SnapshotFields.MoInflClassAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflClass) = TargetResolution.Resolve<IMoInflClass>(cache, operation, MoInflClassAbbreviationOperationKinds.ClearAbbreviation);
        var current = ReadField(cache, moInflClass);
        return new ExpectedEffect(id, SnapshotFields.MoInflClassAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflClass moInflClass) =>
        MoInflClassSnapshotter.Snapshot(cache, moInflClass).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflClassAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
