// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffixTemplate.SuffixSlots (rel/seq MoInflAffixSlot, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffixTemplate.SuffixSlots</c> operation kinds.</summary>
public static class MoInflAffixTemplateSuffixSlotsOperationKinds
{
    public const string AddRefSuffixSlots = "grammar/moInflAffixTemplate/addRefSuffixSlots";
    public const string RemoveRefSuffixSlots = "grammar/moInflAffixTemplate/removeRefSuffixSlots";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefSuffixSlots);
        OperationKindRegistry.Register(RemoveRefSuffixSlots);
        OperationHandlerRegistry.Register(AddRefSuffixSlots, MoInflAffixTemplateSuffixSlotsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefSuffixSlots, MoInflAffixTemplateSuffixSlotsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots"/>
/// and <see cref="MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffixTemplateSuffixSlotsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots"/>: resolves the
/// referenced IMoInflAffixSlot and adds it to <c>moInflAffixTemplate.SuffixSlotsRS</c> (a no-op if already
/// present).</summary>
public static class MoInflAffixTemplateSuffixSlotsAddRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoInflAffixSlot>(
            cache, moInflAffixTemplate.SuffixSlotsRS, memberId, MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots);
}

/// <summary>Lowers <see cref="MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots"/>: resolves the
/// referenced IMoInflAffixSlot and removes it from <c>moInflAffixTemplate.SuffixSlotsRS</c> (a no-op if
/// absent).</summary>
public static class MoInflAffixTemplateSuffixSlotsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoInflAffixSlot>(
            cache, moInflAffixTemplate.SuffixSlotsRS, memberId, MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots"/> operation.</summary>
internal sealed class MoInflAffixTemplateSuffixSlotsAddRefHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateSuffixSlotsAddRefHandler Instance = new();
    private MoInflAffixTemplateSuffixSlotsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots}' requires 'after'.");
        }

        var memberId = MoInflAffixTemplateSuffixSlotsMemberPayload.Parse(after, MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.SuffixSlotsRS);
        MoInflAffixTemplateSuffixSlotsAddRefLowering.Apply(cache, moInflAffixTemplate, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.SuffixSlotsRS);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateSuffixSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateSuffixSlotsOperationKinds.AddRefSuffixSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.SuffixSlotsRS);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateSuffixSlots, current, current);
    }
}

/// <summary>The <see cref="MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots"/> counterpart to
/// <see cref="MoInflAffixTemplateSuffixSlotsAddRefHandler"/>.</summary>
internal sealed class MoInflAffixTemplateSuffixSlotsRemoveRefHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateSuffixSlotsRemoveRefHandler Instance = new();
    private MoInflAffixTemplateSuffixSlotsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots}' requires 'after'.");
        }

        var memberId = MoInflAffixTemplateSuffixSlotsMemberPayload.Parse(after, MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.SuffixSlotsRS);
        MoInflAffixTemplateSuffixSlotsRemoveRefLowering.Apply(cache, moInflAffixTemplate, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.SuffixSlotsRS);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateSuffixSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateSuffixSlotsOperationKinds.RemoveRefSuffixSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.SuffixSlotsRS);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateSuffixSlots, current, current);
    }
}
