// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffMsa.Slots (rel/col MoInflAffixSlot, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffMsa.Slots</c> operation kinds.</summary>
public static class MoInflAffMsaSlotsOperationKinds
{
    public const string AddRefSlots = "grammar/moInflAffMsa/addRefSlots";
    public const string RemoveRefSlots = "grammar/moInflAffMsa/removeRefSlots";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefSlots);
        OperationKindRegistry.Register(RemoveRefSlots);
        OperationHandlerRegistry.Register(AddRefSlots, MoInflAffMsaSlotsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefSlots, MoInflAffMsaSlotsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoInflAffMsaSlotsOperationKinds.AddRefSlots"/>
/// and <see cref="MoInflAffMsaSlotsOperationKinds.RemoveRefSlots"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffMsaSlotsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoInflAffMsaSlotsOperationKinds.AddRefSlots"/>: resolves the
/// referenced IMoInflAffixSlot and adds it to <c>moInflAffMsa.SlotsRC</c> (a no-op if already
/// present).</summary>
public static class MoInflAffMsaSlotsAddRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffMsa moInflAffMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoInflAffixSlot>(
            cache, moInflAffMsa.SlotsRC, memberId, MoInflAffMsaSlotsOperationKinds.AddRefSlots);
}

/// <summary>Lowers <see cref="MoInflAffMsaSlotsOperationKinds.RemoveRefSlots"/>: resolves the
/// referenced IMoInflAffixSlot and removes it from <c>moInflAffMsa.SlotsRC</c> (a no-op if
/// absent).</summary>
public static class MoInflAffMsaSlotsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffMsa moInflAffMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoInflAffixSlot>(
            cache, moInflAffMsa.SlotsRC, memberId, MoInflAffMsaSlotsOperationKinds.RemoveRefSlots);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffMsaSlotsOperationKinds.AddRefSlots"/> operation.</summary>
internal sealed class MoInflAffMsaSlotsAddRefHandler : IOperationHandler
{
    internal static readonly MoInflAffMsaSlotsAddRefHandler Instance = new();
    private MoInflAffMsaSlotsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaSlotsOperationKinds.AddRefSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaSlotsOperationKinds.AddRefSlots}' requires 'after'.");
        }

        var memberId = MoInflAffMsaSlotsMemberPayload.Parse(after, MoInflAffMsaSlotsOperationKinds.AddRefSlots);

        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaSlotsOperationKinds.AddRefSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.SlotsRC);
        MoInflAffMsaSlotsAddRefLowering.Apply(cache, moInflAffMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.SlotsRC);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaSlotsOperationKinds.AddRefSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.SlotsRC);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaSlots, current, current);
    }
}

/// <summary>The <see cref="MoInflAffMsaSlotsOperationKinds.RemoveRefSlots"/> counterpart to
/// <see cref="MoInflAffMsaSlotsAddRefHandler"/>.</summary>
internal sealed class MoInflAffMsaSlotsRemoveRefHandler : IOperationHandler
{
    internal static readonly MoInflAffMsaSlotsRemoveRefHandler Instance = new();
    private MoInflAffMsaSlotsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaSlotsOperationKinds.RemoveRefSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffMsaSlotsOperationKinds.RemoveRefSlots}' requires 'after'.");
        }

        var memberId = MoInflAffMsaSlotsMemberPayload.Parse(after, MoInflAffMsaSlotsOperationKinds.RemoveRefSlots);

        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaSlotsOperationKinds.RemoveRefSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.SlotsRC);
        MoInflAffMsaSlotsRemoveRefLowering.Apply(cache, moInflAffMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.SlotsRC);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffMsa) = TargetResolution.Resolve<IMoInflAffMsa>(cache, operation, MoInflAffMsaSlotsOperationKinds.RemoveRefSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moInflAffMsa.SlotsRC);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffMsaSlots, current, current);
    }
}
