// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffixTemplate.Disabled (basic Boolean, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffixTemplate.Disabled</c> operation kinds.</summary>
public static class MoInflAffixTemplateDisabledOperationKinds
{
    public const string SetDisabled = "grammar/moInflAffixTemplate/setDisabled";
    public const string ClearDisabled = "grammar/moInflAffixTemplate/clearDisabled";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetDisabled);
        OperationKindRegistry.Register(ClearDisabled);
        OperationHandlerRegistry.Register(SetDisabled, MoInflAffixTemplateDisabledSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearDisabled, MoInflAffixTemplateDisabledClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixTemplateDisabledOperationKinds.SetDisabled"/>:
/// <c>{ "value": true|false }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffixTemplateDisabledSetPayload
{
    private static readonly string[] AllowedProperties = { "value" };

    public static bool Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixTemplateDisabledOperationKinds.SetDisabled);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixTemplateDisabledOperationKinds.SetDisabled);

        return ClosedPayloadParsing.GetRequiredBoolean(after, "value", MoInflAffixTemplateDisabledOperationKinds.SetDisabled);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixTemplateDisabledOperationKinds.ClearDisabled"/>:
/// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear.</summary>
public static class MoInflAffixTemplateDisabledClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixTemplateDisabledOperationKinds.ClearDisabled);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixTemplateDisabledOperationKinds.ClearDisabled);
    }
}

/// <summary>Lowers <see cref="MoInflAffixTemplateDisabledOperationKinds.SetDisabled"/>: the one LibLCM
/// write it performs, <c>moInflAffixTemplate.Disabled = value</c>.</summary>
public static class MoInflAffixTemplateDisabledSetLowering
{
    public static void Apply(IMoInflAffixTemplate moInflAffixTemplate, bool value) => moInflAffixTemplate.Disabled = value;
}

/// <summary>Lowers <see cref="MoInflAffixTemplateDisabledOperationKinds.ClearDisabled"/>: resets
/// <c>moInflAffixTemplate.Disabled</c> to <c>false</c>.</summary>
public static class MoInflAffixTemplateDisabledClearLowering
{
    public static void Apply(IMoInflAffixTemplate moInflAffixTemplate) => moInflAffixTemplate.Disabled = false;
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixTemplateDisabledOperationKinds.SetDisabled"/> operation.</summary>
internal sealed class MoInflAffixTemplateDisabledSetHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateDisabledSetHandler Instance = new();
    private MoInflAffixTemplateDisabledSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateDisabledOperationKinds.SetDisabled}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateDisabledOperationKinds.SetDisabled}' requires 'after'.");
        }

        var desired = MoInflAffixTemplateDisabledSetPayload.Parse(after);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateDisabledOperationKinds.SetDisabled);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixTemplate);
        MoInflAffixTemplateDisabledSetLowering.Apply(moInflAffixTemplate, desired);
        var afterValue = ReadField(cache, moInflAffixTemplate);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateDisabled, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateDisabledOperationKinds.SetDisabled);
        var current = ReadField(cache, moInflAffixTemplate);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateDisabled, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate) =>
        MoInflAffixTemplateSnapshotter.Snapshot(cache, moInflAffixTemplate).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixTemplateDisabled, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoInflAffixTemplateDisabledOperationKinds.ClearDisabled"/> counterpart to
/// <see cref="MoInflAffixTemplateDisabledSetHandler"/>.</summary>
internal sealed class MoInflAffixTemplateDisabledClearHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateDisabledClearHandler Instance = new();
    private MoInflAffixTemplateDisabledClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateDisabledOperationKinds.ClearDisabled}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateDisabledOperationKinds.ClearDisabled}' requires 'after'.");
        }

        MoInflAffixTemplateDisabledClearPayload.Parse(after);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateDisabledOperationKinds.ClearDisabled);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixTemplate);
        MoInflAffixTemplateDisabledClearLowering.Apply(moInflAffixTemplate);
        var afterValue = ReadField(cache, moInflAffixTemplate);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateDisabled, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateDisabledOperationKinds.ClearDisabled);
        var current = ReadField(cache, moInflAffixTemplate);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateDisabled, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate) =>
        MoInflAffixTemplateSnapshotter.Snapshot(cache, moInflAffixTemplate).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixTemplateDisabled, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
