// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffixSlot.Optional (basic Boolean, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffixSlot.Optional</c> operation kinds.</summary>
public static class MoInflAffixSlotOptionalOperationKinds
{
    public const string SetOptional = "grammar/moInflAffixSlot/setOptional";
    public const string ClearOptional = "grammar/moInflAffixSlot/clearOptional";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetOptional);
        OperationKindRegistry.Register(ClearOptional);
        OperationHandlerRegistry.Register(SetOptional, MoInflAffixSlotOptionalSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearOptional, MoInflAffixSlotOptionalClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixSlotOptionalOperationKinds.SetOptional"/>:
/// <c>{ "value": true|false }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffixSlotOptionalSetPayload
{
    private static readonly string[] AllowedProperties = { "value" };

    public static bool Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixSlotOptionalOperationKinds.SetOptional);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixSlotOptionalOperationKinds.SetOptional);

        return ClosedPayloadParsing.GetRequiredBoolean(after, "value", MoInflAffixSlotOptionalOperationKinds.SetOptional);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixSlotOptionalOperationKinds.ClearOptional"/>:
/// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear.</summary>
public static class MoInflAffixSlotOptionalClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixSlotOptionalOperationKinds.ClearOptional);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixSlotOptionalOperationKinds.ClearOptional);
    }
}

/// <summary>Lowers <see cref="MoInflAffixSlotOptionalOperationKinds.SetOptional"/>: the one LibLCM
/// write it performs, <c>moInflAffixSlot.Optional = value</c>.</summary>
public static class MoInflAffixSlotOptionalSetLowering
{
    public static void Apply(IMoInflAffixSlot moInflAffixSlot, bool value) => moInflAffixSlot.Optional = value;
}

/// <summary>Lowers <see cref="MoInflAffixSlotOptionalOperationKinds.ClearOptional"/>: resets
/// <c>moInflAffixSlot.Optional</c> to <c>false</c>.</summary>
public static class MoInflAffixSlotOptionalClearLowering
{
    public static void Apply(IMoInflAffixSlot moInflAffixSlot) => moInflAffixSlot.Optional = false;
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixSlotOptionalOperationKinds.SetOptional"/> operation.</summary>
internal sealed class MoInflAffixSlotOptionalSetHandler : IOperationHandler
{
    internal static readonly MoInflAffixSlotOptionalSetHandler Instance = new();
    private MoInflAffixSlotOptionalSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotOptionalOperationKinds.SetOptional}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotOptionalOperationKinds.SetOptional}' requires 'after'.");
        }

        var desired = MoInflAffixSlotOptionalSetPayload.Parse(after);

        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotOptionalOperationKinds.SetOptional);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixSlot);
        MoInflAffixSlotOptionalSetLowering.Apply(moInflAffixSlot, desired);
        var afterValue = ReadField(cache, moInflAffixSlot);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotOptional, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotOptionalOperationKinds.SetOptional);
        var current = ReadField(cache, moInflAffixSlot);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotOptional, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixSlot moInflAffixSlot) =>
        MoInflAffixSlotSnapshotter.Snapshot(cache, moInflAffixSlot).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixSlotOptional, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoInflAffixSlotOptionalOperationKinds.ClearOptional"/> counterpart to
/// <see cref="MoInflAffixSlotOptionalSetHandler"/>.</summary>
internal sealed class MoInflAffixSlotOptionalClearHandler : IOperationHandler
{
    internal static readonly MoInflAffixSlotOptionalClearHandler Instance = new();
    private MoInflAffixSlotOptionalClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotOptionalOperationKinds.ClearOptional}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotOptionalOperationKinds.ClearOptional}' requires 'after'.");
        }

        MoInflAffixSlotOptionalClearPayload.Parse(after);

        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotOptionalOperationKinds.ClearOptional);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixSlot);
        MoInflAffixSlotOptionalClearLowering.Apply(moInflAffixSlot);
        var afterValue = ReadField(cache, moInflAffixSlot);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotOptional, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotOptionalOperationKinds.ClearOptional);
        var current = ReadField(cache, moInflAffixSlot);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotOptional, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixSlot moInflAffixSlot) =>
        MoInflAffixSlotSnapshotter.Snapshot(cache, moInflAffixSlot).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixSlotOptional, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
