// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoModifyFromInput.Modification (rel/atomic PhNCFeatures, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoModifyFromInput.Modification</c> operation kinds.</summary>
public static class MoModifyFromInputModificationOperationKinds
{
    public const string SetModification = "grammar/moModifyFromInput/setModification";
    public const string ClearModification = "grammar/moModifyFromInput/clearModification";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetModification);
        OperationKindRegistry.Register(ClearModification);
        OperationHandlerRegistry.Register(SetModification, MoModifyFromInputModificationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearModification, MoModifyFromInputModificationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoModifyFromInputModificationOperationKinds.SetModification"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoModifyFromInputModificationSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoModifyFromInputModificationOperationKinds.SetModification);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoModifyFromInputModificationOperationKinds.SetModification);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoModifyFromInputModificationOperationKinds.SetModification);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoModifyFromInputModificationOperationKinds.ClearModification"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoModifyFromInputModificationClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoModifyFromInputModificationOperationKinds.ClearModification);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoModifyFromInputModificationOperationKinds.ClearModification);
    }
}

/// <summary>Lowers <see cref="MoModifyFromInputModificationOperationKinds.SetModification"/>: resolves the
/// referenced IPhNCFeatures and assigns it to <c>moModifyFromInput.ModificationRA</c>.</summary>
public static class MoModifyFromInputModificationSetLowering
{
    public static void Apply(LcmCache cache, IMoModifyFromInput moModifyFromInput, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IPhNCFeatures>(
            cache, value => moModifyFromInput.ModificationRA = value, refId, MoModifyFromInputModificationOperationKinds.SetModification);
}

/// <summary>Lowers <see cref="MoModifyFromInputModificationOperationKinds.ClearModification"/>: detaches
/// <c>moModifyFromInput.ModificationRA</c>.</summary>
public static class MoModifyFromInputModificationClearLowering
{
    public static void Apply(IMoModifyFromInput moModifyFromInput) =>
        ReferenceFieldLowering.ApplyClear<IPhNCFeatures>(value => moModifyFromInput.ModificationRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoModifyFromInputModificationOperationKinds.SetModification"/> operation.</summary>
internal sealed class MoModifyFromInputModificationSetHandler : IOperationHandler
{
    internal static readonly MoModifyFromInputModificationSetHandler Instance = new();
    private MoModifyFromInputModificationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoModifyFromInputModificationOperationKinds.SetModification}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoModifyFromInputModificationOperationKinds.SetModification}' requires 'after'.");
        }

        var refId = MoModifyFromInputModificationSetPayload.Parse(after);

        var (id, moModifyFromInput) = TargetResolution.Resolve<IMoModifyFromInput>(cache, operation, MoModifyFromInputModificationOperationKinds.SetModification);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moModifyFromInput.ModificationRA);
        MoModifyFromInputModificationSetLowering.Apply(cache, moModifyFromInput, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moModifyFromInput.ModificationRA);

        return new ExpectedEffect(id, SnapshotFields.MoModifyFromInputModification, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moModifyFromInput) = TargetResolution.Resolve<IMoModifyFromInput>(cache, operation, MoModifyFromInputModificationOperationKinds.SetModification);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moModifyFromInput.ModificationRA);
        return new ExpectedEffect(id, SnapshotFields.MoModifyFromInputModification, current, current);
    }
}

/// <summary>The <see cref="MoModifyFromInputModificationOperationKinds.ClearModification"/> counterpart to
/// <see cref="MoModifyFromInputModificationSetHandler"/>.</summary>
internal sealed class MoModifyFromInputModificationClearHandler : IOperationHandler
{
    internal static readonly MoModifyFromInputModificationClearHandler Instance = new();
    private MoModifyFromInputModificationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoModifyFromInputModificationOperationKinds.ClearModification}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoModifyFromInputModificationOperationKinds.ClearModification}' requires 'after'.");
        }

        MoModifyFromInputModificationClearPayload.Parse(after);

        var (id, moModifyFromInput) = TargetResolution.Resolve<IMoModifyFromInput>(cache, operation, MoModifyFromInputModificationOperationKinds.ClearModification);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moModifyFromInput.ModificationRA);
        MoModifyFromInputModificationClearLowering.Apply(moModifyFromInput);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moModifyFromInput.ModificationRA);

        return new ExpectedEffect(id, SnapshotFields.MoModifyFromInputModification, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moModifyFromInput) = TargetResolution.Resolve<IMoModifyFromInput>(cache, operation, MoModifyFromInputModificationOperationKinds.ClearModification);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moModifyFromInput.ModificationRA);
        return new ExpectedEffect(id, SnapshotFields.MoModifyFromInputModification, current, current);
    }
}
