// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoStemMsa.InflectionClass (rel/atomic MoInflClass, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoStemMsa.InflectionClass</c> operation kinds.</summary>
public static class MoStemMsaInflectionClassOperationKinds
{
    public const string SetInflectionClass = "grammar/moStemMsa/setInflectionClass";
    public const string ClearInflectionClass = "grammar/moStemMsa/clearInflectionClass";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetInflectionClass);
        OperationKindRegistry.Register(ClearInflectionClass);
        OperationHandlerRegistry.Register(SetInflectionClass, MoStemMsaInflectionClassSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearInflectionClass, MoStemMsaInflectionClassClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemMsaInflectionClassOperationKinds.SetInflectionClass"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoStemMsaInflectionClassSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemMsaInflectionClassOperationKinds.SetInflectionClass);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemMsaInflectionClassOperationKinds.SetInflectionClass);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoStemMsaInflectionClassOperationKinds.SetInflectionClass);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemMsaInflectionClassOperationKinds.ClearInflectionClass"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoStemMsaInflectionClassClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemMsaInflectionClassOperationKinds.ClearInflectionClass);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemMsaInflectionClassOperationKinds.ClearInflectionClass);
    }
}

/// <summary>Lowers <see cref="MoStemMsaInflectionClassOperationKinds.SetInflectionClass"/>: resolves the
/// referenced IMoInflClass and assigns it to <c>moStemMsa.InflectionClassRA</c>.</summary>
public static class MoStemMsaInflectionClassSetLowering
{
    public static void Apply(LcmCache cache, IMoStemMsa moStemMsa, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IMoInflClass>(
            cache, value => moStemMsa.InflectionClassRA = value, refId, MoStemMsaInflectionClassOperationKinds.SetInflectionClass);
}

/// <summary>Lowers <see cref="MoStemMsaInflectionClassOperationKinds.ClearInflectionClass"/>: detaches
/// <c>moStemMsa.InflectionClassRA</c>.</summary>
public static class MoStemMsaInflectionClassClearLowering
{
    public static void Apply(IMoStemMsa moStemMsa) =>
        ReferenceFieldLowering.ApplyClear<IMoInflClass>(value => moStemMsa.InflectionClassRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoStemMsaInflectionClassOperationKinds.SetInflectionClass"/> operation.</summary>
internal sealed class MoStemMsaInflectionClassSetHandler : IOperationHandler
{
    internal static readonly MoStemMsaInflectionClassSetHandler Instance = new();
    private MoStemMsaInflectionClassSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaInflectionClassOperationKinds.SetInflectionClass}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaInflectionClassOperationKinds.SetInflectionClass}' requires 'after'.");
        }

        var refId = MoStemMsaInflectionClassSetPayload.Parse(after);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaInflectionClassOperationKinds.SetInflectionClass);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.InflectionClassRA);
        MoStemMsaInflectionClassSetLowering.Apply(cache, moStemMsa, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.InflectionClassRA);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaInflectionClass, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaInflectionClassOperationKinds.SetInflectionClass);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.InflectionClassRA);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaInflectionClass, current, current);
    }
}

/// <summary>The <see cref="MoStemMsaInflectionClassOperationKinds.ClearInflectionClass"/> counterpart to
/// <see cref="MoStemMsaInflectionClassSetHandler"/>.</summary>
internal sealed class MoStemMsaInflectionClassClearHandler : IOperationHandler
{
    internal static readonly MoStemMsaInflectionClassClearHandler Instance = new();
    private MoStemMsaInflectionClassClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaInflectionClassOperationKinds.ClearInflectionClass}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaInflectionClassOperationKinds.ClearInflectionClass}' requires 'after'.");
        }

        MoStemMsaInflectionClassClearPayload.Parse(after);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaInflectionClassOperationKinds.ClearInflectionClass);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.InflectionClassRA);
        MoStemMsaInflectionClassClearLowering.Apply(moStemMsa);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.InflectionClassRA);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaInflectionClass, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaInflectionClassOperationKinds.ClearInflectionClass);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.InflectionClassRA);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaInflectionClass, current, current);
    }
}
