// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoStemAllomorph.StemName (rel/atomic MoStemName, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoStemAllomorph.StemName</c> operation kinds.</summary>
public static class MoStemAllomorphStemNameOperationKinds
{
    public const string SetStemName = "grammar/moStemAllomorph/setStemName";
    public const string ClearStemName = "grammar/moStemAllomorph/clearStemName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetStemName);
        OperationKindRegistry.Register(ClearStemName);
        OperationHandlerRegistry.Register(SetStemName, MoStemAllomorphStemNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearStemName, MoStemAllomorphStemNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemAllomorphStemNameOperationKinds.SetStemName"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoStemAllomorphStemNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemAllomorphStemNameOperationKinds.SetStemName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemAllomorphStemNameOperationKinds.SetStemName);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoStemAllomorphStemNameOperationKinds.SetStemName);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemAllomorphStemNameOperationKinds.ClearStemName"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoStemAllomorphStemNameClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemAllomorphStemNameOperationKinds.ClearStemName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemAllomorphStemNameOperationKinds.ClearStemName);
    }
}

/// <summary>Lowers <see cref="MoStemAllomorphStemNameOperationKinds.SetStemName"/>: resolves the
/// referenced IMoStemName and assigns it to <c>moStemAllomorph.StemNameRA</c>.</summary>
public static class MoStemAllomorphStemNameSetLowering
{
    public static void Apply(LcmCache cache, IMoStemAllomorph moStemAllomorph, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IMoStemName>(
            cache, value => moStemAllomorph.StemNameRA = value, refId, MoStemAllomorphStemNameOperationKinds.SetStemName);
}

/// <summary>Lowers <see cref="MoStemAllomorphStemNameOperationKinds.ClearStemName"/>: detaches
/// <c>moStemAllomorph.StemNameRA</c>.</summary>
public static class MoStemAllomorphStemNameClearLowering
{
    public static void Apply(IMoStemAllomorph moStemAllomorph) =>
        ReferenceFieldLowering.ApplyClear<IMoStemName>(value => moStemAllomorph.StemNameRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoStemAllomorphStemNameOperationKinds.SetStemName"/> operation.</summary>
internal sealed class MoStemAllomorphStemNameSetHandler : IOperationHandler
{
    internal static readonly MoStemAllomorphStemNameSetHandler Instance = new();
    private MoStemAllomorphStemNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphStemNameOperationKinds.SetStemName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphStemNameOperationKinds.SetStemName}' requires 'after'.");
        }

        var refId = MoStemAllomorphStemNameSetPayload.Parse(after);

        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphStemNameOperationKinds.SetStemName);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moStemAllomorph.StemNameRA);
        MoStemAllomorphStemNameSetLowering.Apply(cache, moStemAllomorph, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moStemAllomorph.StemNameRA);

        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphStemName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphStemNameOperationKinds.SetStemName);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moStemAllomorph.StemNameRA);
        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphStemName, current, current);
    }
}

/// <summary>The <see cref="MoStemAllomorphStemNameOperationKinds.ClearStemName"/> counterpart to
/// <see cref="MoStemAllomorphStemNameSetHandler"/>.</summary>
internal sealed class MoStemAllomorphStemNameClearHandler : IOperationHandler
{
    internal static readonly MoStemAllomorphStemNameClearHandler Instance = new();
    private MoStemAllomorphStemNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphStemNameOperationKinds.ClearStemName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphStemNameOperationKinds.ClearStemName}' requires 'after'.");
        }

        MoStemAllomorphStemNameClearPayload.Parse(after);

        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphStemNameOperationKinds.ClearStemName);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moStemAllomorph.StemNameRA);
        MoStemAllomorphStemNameClearLowering.Apply(moStemAllomorph);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moStemAllomorph.StemNameRA);

        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphStemName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphStemNameOperationKinds.ClearStemName);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moStemAllomorph.StemNameRA);
        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphStemName, current, current);
    }
}
