// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoStemMsa.PartOfSpeech (rel/atomic PartOfSpeech, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoStemMsa.PartOfSpeech</c> operation kinds.</summary>
public static class MoStemMsaPartOfSpeechOperationKinds
{
    public const string SetPartOfSpeech = "grammar/moStemMsa/setPartOfSpeech";
    public const string ClearPartOfSpeech = "grammar/moStemMsa/clearPartOfSpeech";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetPartOfSpeech);
        OperationKindRegistry.Register(ClearPartOfSpeech);
        OperationHandlerRegistry.Register(SetPartOfSpeech, MoStemMsaPartOfSpeechSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearPartOfSpeech, MoStemMsaPartOfSpeechClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoStemMsaPartOfSpeechSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class MoStemMsaPartOfSpeechClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
    }
}

/// <summary>Lowers <see cref="MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech"/>: resolves the
/// referenced IPartOfSpeech and assigns it to <c>moStemMsa.PartOfSpeechRA</c>.</summary>
public static class MoStemMsaPartOfSpeechSetLowering
{
    public static void Apply(LcmCache cache, IMoStemMsa moStemMsa, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IPartOfSpeech>(
            cache, value => moStemMsa.PartOfSpeechRA = value, refId, MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
}

/// <summary>Lowers <see cref="MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech"/>: detaches
/// <c>moStemMsa.PartOfSpeechRA</c>.</summary>
public static class MoStemMsaPartOfSpeechClearLowering
{
    public static void Apply(IMoStemMsa moStemMsa) =>
        ReferenceFieldLowering.ApplyClear<IPartOfSpeech>(value => moStemMsa.PartOfSpeechRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech"/> operation.</summary>
internal sealed class MoStemMsaPartOfSpeechSetHandler : IOperationHandler
{
    internal static readonly MoStemMsaPartOfSpeechSetHandler Instance = new();
    private MoStemMsaPartOfSpeechSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech}' requires 'after'.");
        }

        var refId = MoStemMsaPartOfSpeechSetPayload.Parse(after);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.PartOfSpeechRA);
        MoStemMsaPartOfSpeechSetLowering.Apply(cache, moStemMsa, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.PartOfSpeechRA);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaPartOfSpeech, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaPartOfSpeechOperationKinds.SetPartOfSpeech);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.PartOfSpeechRA);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaPartOfSpeech, current, current);
    }
}

/// <summary>The <see cref="MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech"/> counterpart to
/// <see cref="MoStemMsaPartOfSpeechSetHandler"/>.</summary>
internal sealed class MoStemMsaPartOfSpeechClearHandler : IOperationHandler
{
    internal static readonly MoStemMsaPartOfSpeechClearHandler Instance = new();
    private MoStemMsaPartOfSpeechClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech}' requires 'after'.");
        }

        MoStemMsaPartOfSpeechClearPayload.Parse(after);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.PartOfSpeechRA);
        MoStemMsaPartOfSpeechClearLowering.Apply(moStemMsa);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.PartOfSpeechRA);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaPartOfSpeech, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaPartOfSpeechOperationKinds.ClearPartOfSpeech);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(moStemMsa.PartOfSpeechRA);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaPartOfSpeech, current, current);
    }
}
