// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoStemName.Abbreviation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoStemName.Abbreviation</c> operation kinds.</summary>
public static class MoStemNameAbbreviationOperationKinds
{
    public const string SetAbbreviation = "grammar/moStemName/setAbbreviation";
    public const string ClearAbbreviation = "grammar/moStemName/clearAbbreviation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetAbbreviation);
        OperationKindRegistry.Register(ClearAbbreviation);
        OperationHandlerRegistry.Register(SetAbbreviation, MoStemNameAbbreviationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearAbbreviation, MoStemNameAbbreviationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemNameAbbreviationOperationKinds.SetAbbreviation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class MoStemNameAbbreviationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemNameAbbreviationOperationKinds.SetAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemNameAbbreviationOperationKinds.SetAbbreviation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", MoStemNameAbbreviationOperationKinds.SetAbbreviation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", MoStemNameAbbreviationOperationKinds.SetAbbreviation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoStemNameAbbreviationOperationKinds.ClearAbbreviation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class MoStemNameAbbreviationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoStemNameAbbreviationOperationKinds.ClearAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoStemNameAbbreviationOperationKinds.ClearAbbreviation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", MoStemNameAbbreviationOperationKinds.ClearAbbreviation);
    }
}

/// <summary>Lowers <see cref="MoStemNameAbbreviationOperationKinds.SetAbbreviation"/>: sets one
/// writing-system alternative of <c>moStemName.Abbreviation</c>.</summary>
public static class MoStemNameAbbreviationSetLowering
{
    public static void Apply(LcmCache cache, IMoStemName moStemName, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, moStemName.Abbreviation, writingSystemTag, text, MoStemNameAbbreviationOperationKinds.SetAbbreviation);
}

/// <summary>Lowers <see cref="MoStemNameAbbreviationOperationKinds.ClearAbbreviation"/>: clears one
/// writing-system alternative of <c>moStemName.Abbreviation</c>.</summary>
public static class MoStemNameAbbreviationClearLowering
{
    public static void Apply(LcmCache cache, IMoStemName moStemName, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, moStemName.Abbreviation, writingSystemTag, MoStemNameAbbreviationOperationKinds.ClearAbbreviation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoStemNameAbbreviationOperationKinds.SetAbbreviation"/> operation.</summary>
internal sealed class MoStemNameAbbreviationSetHandler : IOperationHandler
{
    internal static readonly MoStemNameAbbreviationSetHandler Instance = new();
    private MoStemNameAbbreviationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemNameAbbreviationOperationKinds.SetAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemNameAbbreviationOperationKinds.SetAbbreviation}' requires 'after'.");
        }

        var (writingSystemTag, text) = MoStemNameAbbreviationSetPayload.Parse(after);

        var (id, moStemName) = TargetResolution.Resolve<IMoStemName>(cache, operation, MoStemNameAbbreviationOperationKinds.SetAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, moStemName);
        MoStemNameAbbreviationSetLowering.Apply(cache, moStemName, writingSystemTag, text);
        var afterValue = ReadField(cache, moStemName);

        return new ExpectedEffect(id, SnapshotFields.MoStemNameAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemName) = TargetResolution.Resolve<IMoStemName>(cache, operation, MoStemNameAbbreviationOperationKinds.SetAbbreviation);
        var current = ReadField(cache, moStemName);
        return new ExpectedEffect(id, SnapshotFields.MoStemNameAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoStemName moStemName) =>
        MoStemNameSnapshotter.Snapshot(cache, moStemName).AlternativesFields
            .TryGetValue(SnapshotFields.MoStemNameAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoStemNameAbbreviationOperationKinds.ClearAbbreviation"/> counterpart to
/// <see cref="MoStemNameAbbreviationSetHandler"/>.</summary>
internal sealed class MoStemNameAbbreviationClearHandler : IOperationHandler
{
    internal static readonly MoStemNameAbbreviationClearHandler Instance = new();
    private MoStemNameAbbreviationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemNameAbbreviationOperationKinds.ClearAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemNameAbbreviationOperationKinds.ClearAbbreviation}' requires 'after'.");
        }

        var writingSystemTag = MoStemNameAbbreviationClearPayload.Parse(after);

        var (id, moStemName) = TargetResolution.Resolve<IMoStemName>(cache, operation, MoStemNameAbbreviationOperationKinds.ClearAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, moStemName);
        MoStemNameAbbreviationClearLowering.Apply(cache, moStemName, writingSystemTag);
        var afterValue = ReadField(cache, moStemName);

        return new ExpectedEffect(id, SnapshotFields.MoStemNameAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemName) = TargetResolution.Resolve<IMoStemName>(cache, operation, MoStemNameAbbreviationOperationKinds.ClearAbbreviation);
        var current = ReadField(cache, moStemName);
        return new ExpectedEffect(id, SnapshotFields.MoStemNameAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoStemName moStemName) =>
        MoStemNameSnapshotter.Snapshot(cache, moStemName).AlternativesFields
            .TryGetValue(SnapshotFields.MoStemNameAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
