// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoStemAllomorph.PhoneEnv (rel/col PhEnvironment, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoStemAllomorph.PhoneEnv</c> operation kinds.</summary>
public static class MoStemAllomorphPhoneEnvOperationKinds
{
    public const string AddRefPhoneEnv = "grammar/moStemAllomorph/addRefPhoneEnv";
    public const string RemoveRefPhoneEnv = "grammar/moStemAllomorph/removeRefPhoneEnv";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefPhoneEnv);
        OperationKindRegistry.Register(RemoveRefPhoneEnv);
        OperationHandlerRegistry.Register(AddRefPhoneEnv, MoStemAllomorphPhoneEnvAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefPhoneEnv, MoStemAllomorphPhoneEnvRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv"/>
/// and <see cref="MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoStemAllomorphPhoneEnvMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv"/>: resolves the
/// referenced IPhEnvironment and adds it to <c>moStemAllomorph.PhoneEnvRC</c> (a no-op if already
/// present).</summary>
public static class MoStemAllomorphPhoneEnvAddRefLowering
{
    public static void Apply(LcmCache cache, IMoStemAllomorph moStemAllomorph, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhEnvironment>(
            cache, moStemAllomorph.PhoneEnvRC, memberId, MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);
}

/// <summary>Lowers <see cref="MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv"/>: resolves the
/// referenced IPhEnvironment and removes it from <c>moStemAllomorph.PhoneEnvRC</c> (a no-op if
/// absent).</summary>
public static class MoStemAllomorphPhoneEnvRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoStemAllomorph moStemAllomorph, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhEnvironment>(
            cache, moStemAllomorph.PhoneEnvRC, memberId, MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv"/> operation.</summary>
internal sealed class MoStemAllomorphPhoneEnvAddRefHandler : IOperationHandler
{
    internal static readonly MoStemAllomorphPhoneEnvAddRefHandler Instance = new();
    private MoStemAllomorphPhoneEnvAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv}' requires 'after'.");
        }

        var memberId = MoStemAllomorphPhoneEnvMemberPayload.Parse(after, MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);

        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemAllomorph.PhoneEnvRC);
        MoStemAllomorphPhoneEnvAddRefLowering.Apply(cache, moStemAllomorph, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemAllomorph.PhoneEnvRC);

        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphPhoneEnv, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphPhoneEnvOperationKinds.AddRefPhoneEnv);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemAllomorph.PhoneEnvRC);
        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphPhoneEnv, current, current);
    }
}

/// <summary>The <see cref="MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv"/> counterpart to
/// <see cref="MoStemAllomorphPhoneEnvAddRefHandler"/>.</summary>
internal sealed class MoStemAllomorphPhoneEnvRemoveRefHandler : IOperationHandler
{
    internal static readonly MoStemAllomorphPhoneEnvRemoveRefHandler Instance = new();
    private MoStemAllomorphPhoneEnvRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv}' requires 'after'.");
        }

        var memberId = MoStemAllomorphPhoneEnvMemberPayload.Parse(after, MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);

        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemAllomorph.PhoneEnvRC);
        MoStemAllomorphPhoneEnvRemoveRefLowering.Apply(cache, moStemAllomorph, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemAllomorph.PhoneEnvRC);

        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphPhoneEnv, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemAllomorph) = TargetResolution.Resolve<IMoStemAllomorph>(cache, operation, MoStemAllomorphPhoneEnvOperationKinds.RemoveRefPhoneEnv);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemAllomorph.PhoneEnvRC);
        return new ExpectedEffect(id, SnapshotFields.MoStemAllomorphPhoneEnv, current, current);
    }
}
