// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoStemMsa.ProdRestrict (rel/col CmPossibility, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoStemMsa.ProdRestrict</c> operation kinds.</summary>
public static class MoStemMsaProdRestrictOperationKinds
{
    public const string AddRefProdRestrict = "grammar/moStemMsa/addRefProdRestrict";
    public const string RemoveRefProdRestrict = "grammar/moStemMsa/removeRefProdRestrict";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefProdRestrict);
        OperationKindRegistry.Register(RemoveRefProdRestrict);
        OperationHandlerRegistry.Register(AddRefProdRestrict, MoStemMsaProdRestrictAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefProdRestrict, MoStemMsaProdRestrictRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict"/>
/// and <see cref="MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoStemMsaProdRestrictMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict"/>: resolves the
/// referenced ICmPossibility and adds it to <c>moStemMsa.ProdRestrictRC</c> (a no-op if already
/// present).</summary>
public static class MoStemMsaProdRestrictAddRefLowering
{
    public static void Apply(LcmCache cache, IMoStemMsa moStemMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ICmPossibility>(
            cache, moStemMsa.ProdRestrictRC, memberId, MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict);
}

/// <summary>Lowers <see cref="MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict"/>: resolves the
/// referenced ICmPossibility and removes it from <c>moStemMsa.ProdRestrictRC</c> (a no-op if
/// absent).</summary>
public static class MoStemMsaProdRestrictRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoStemMsa moStemMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ICmPossibility>(
            cache, moStemMsa.ProdRestrictRC, memberId, MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict"/> operation.</summary>
internal sealed class MoStemMsaProdRestrictAddRefHandler : IOperationHandler
{
    internal static readonly MoStemMsaProdRestrictAddRefHandler Instance = new();
    private MoStemMsaProdRestrictAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict}' requires 'after'.");
        }

        var memberId = MoStemMsaProdRestrictMemberPayload.Parse(after, MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.ProdRestrictRC);
        MoStemMsaProdRestrictAddRefLowering.Apply(cache, moStemMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.ProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaProdRestrictOperationKinds.AddRefProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.ProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaProdRestrict, current, current);
    }
}

/// <summary>The <see cref="MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict"/> counterpart to
/// <see cref="MoStemMsaProdRestrictAddRefHandler"/>.</summary>
internal sealed class MoStemMsaProdRestrictRemoveRefHandler : IOperationHandler
{
    internal static readonly MoStemMsaProdRestrictRemoveRefHandler Instance = new();
    private MoStemMsaProdRestrictRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict}' requires 'after'.");
        }

        var memberId = MoStemMsaProdRestrictMemberPayload.Parse(after, MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.ProdRestrictRC);
        MoStemMsaProdRestrictRemoveRefLowering.Apply(cache, moStemMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.ProdRestrictRC);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaProdRestrict, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaProdRestrictOperationKinds.RemoveRefProdRestrict);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.ProdRestrictRC);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaProdRestrict, current, current);
    }
}
