// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoStemMsa.Slots (rel/col MoInflAffixSlot, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoStemMsa.Slots</c> operation kinds.</summary>
public static class MoStemMsaSlotsOperationKinds
{
    public const string AddRefSlots = "grammar/moStemMsa/addRefSlots";
    public const string RemoveRefSlots = "grammar/moStemMsa/removeRefSlots";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefSlots);
        OperationKindRegistry.Register(RemoveRefSlots);
        OperationHandlerRegistry.Register(AddRefSlots, MoStemMsaSlotsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefSlots, MoStemMsaSlotsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoStemMsaSlotsOperationKinds.AddRefSlots"/>
/// and <see cref="MoStemMsaSlotsOperationKinds.RemoveRefSlots"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoStemMsaSlotsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoStemMsaSlotsOperationKinds.AddRefSlots"/>: resolves the
/// referenced IMoInflAffixSlot and adds it to <c>moStemMsa.SlotsRC</c> (a no-op if already
/// present).</summary>
public static class MoStemMsaSlotsAddRefLowering
{
    public static void Apply(LcmCache cache, IMoStemMsa moStemMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoInflAffixSlot>(
            cache, moStemMsa.SlotsRC, memberId, MoStemMsaSlotsOperationKinds.AddRefSlots);
}

/// <summary>Lowers <see cref="MoStemMsaSlotsOperationKinds.RemoveRefSlots"/>: resolves the
/// referenced IMoInflAffixSlot and removes it from <c>moStemMsa.SlotsRC</c> (a no-op if
/// absent).</summary>
public static class MoStemMsaSlotsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoStemMsa moStemMsa, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoInflAffixSlot>(
            cache, moStemMsa.SlotsRC, memberId, MoStemMsaSlotsOperationKinds.RemoveRefSlots);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoStemMsaSlotsOperationKinds.AddRefSlots"/> operation.</summary>
internal sealed class MoStemMsaSlotsAddRefHandler : IOperationHandler
{
    internal static readonly MoStemMsaSlotsAddRefHandler Instance = new();
    private MoStemMsaSlotsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaSlotsOperationKinds.AddRefSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaSlotsOperationKinds.AddRefSlots}' requires 'after'.");
        }

        var memberId = MoStemMsaSlotsMemberPayload.Parse(after, MoStemMsaSlotsOperationKinds.AddRefSlots);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaSlotsOperationKinds.AddRefSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.SlotsRC);
        MoStemMsaSlotsAddRefLowering.Apply(cache, moStemMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.SlotsRC);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaSlotsOperationKinds.AddRefSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.SlotsRC);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaSlots, current, current);
    }
}

/// <summary>The <see cref="MoStemMsaSlotsOperationKinds.RemoveRefSlots"/> counterpart to
/// <see cref="MoStemMsaSlotsAddRefHandler"/>.</summary>
internal sealed class MoStemMsaSlotsRemoveRefHandler : IOperationHandler
{
    internal static readonly MoStemMsaSlotsRemoveRefHandler Instance = new();
    private MoStemMsaSlotsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaSlotsOperationKinds.RemoveRefSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoStemMsaSlotsOperationKinds.RemoveRefSlots}' requires 'after'.");
        }

        var memberId = MoStemMsaSlotsMemberPayload.Parse(after, MoStemMsaSlotsOperationKinds.RemoveRefSlots);

        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaSlotsOperationKinds.RemoveRefSlots);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.SlotsRC);
        MoStemMsaSlotsRemoveRefLowering.Apply(cache, moStemMsa, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.SlotsRC);

        return new ExpectedEffect(id, SnapshotFields.MoStemMsaSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moStemMsa) = TargetResolution.Resolve<IMoStemMsa>(cache, operation, MoStemMsaSlotsOperationKinds.RemoveRefSlots);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(moStemMsa.SlotsRC);
        return new ExpectedEffect(id, SnapshotFields.MoStemMsaSlots, current, current);
    }
}
