// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PartOfSpeech.DefaultInflectionClass (rel/atomic MoInflClass, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PartOfSpeech.DefaultInflectionClass</c> operation kinds.</summary>
public static class PartOfSpeechDefaultInflectionClassOperationKinds
{
    public const string SetDefaultInflectionClass = "grammar/partOfSpeech/setDefaultInflectionClass";
    public const string ClearDefaultInflectionClass = "grammar/partOfSpeech/clearDefaultInflectionClass";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetDefaultInflectionClass);
        OperationKindRegistry.Register(ClearDefaultInflectionClass);
        OperationHandlerRegistry.Register(SetDefaultInflectionClass, PartOfSpeechDefaultInflectionClassSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearDefaultInflectionClass, PartOfSpeechDefaultInflectionClassClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PartOfSpeechDefaultInflectionClassSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class PartOfSpeechDefaultInflectionClassClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass);
    }
}

/// <summary>Lowers <see cref="PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass"/>: resolves the
/// referenced IMoInflClass and assigns it to <c>partOfSpeech.DefaultInflectionClassRA</c>.</summary>
public static class PartOfSpeechDefaultInflectionClassSetLowering
{
    public static void Apply(LcmCache cache, IPartOfSpeech partOfSpeech, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IMoInflClass>(
            cache, value => partOfSpeech.DefaultInflectionClassRA = value, refId, PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass);
}

/// <summary>Lowers <see cref="PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass"/>: detaches
/// <c>partOfSpeech.DefaultInflectionClassRA</c>.</summary>
public static class PartOfSpeechDefaultInflectionClassClearLowering
{
    public static void Apply(IPartOfSpeech partOfSpeech) =>
        ReferenceFieldLowering.ApplyClear<IMoInflClass>(value => partOfSpeech.DefaultInflectionClassRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass"/> operation.</summary>
internal sealed class PartOfSpeechDefaultInflectionClassSetHandler : IOperationHandler
{
    internal static readonly PartOfSpeechDefaultInflectionClassSetHandler Instance = new();
    private PartOfSpeechDefaultInflectionClassSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass}' requires 'after'.");
        }

        var refId = PartOfSpeechDefaultInflectionClassSetPayload.Parse(after);

        var (id, partOfSpeech) = TargetResolution.Resolve<IPartOfSpeech>(cache, operation, PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(partOfSpeech.DefaultInflectionClassRA);
        PartOfSpeechDefaultInflectionClassSetLowering.Apply(cache, partOfSpeech, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(partOfSpeech.DefaultInflectionClassRA);

        return new ExpectedEffect(id, SnapshotFields.PartOfSpeechDefaultInflectionClass, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, partOfSpeech) = TargetResolution.Resolve<IPartOfSpeech>(cache, operation, PartOfSpeechDefaultInflectionClassOperationKinds.SetDefaultInflectionClass);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(partOfSpeech.DefaultInflectionClassRA);
        return new ExpectedEffect(id, SnapshotFields.PartOfSpeechDefaultInflectionClass, current, current);
    }
}

/// <summary>The <see cref="PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass"/> counterpart to
/// <see cref="PartOfSpeechDefaultInflectionClassSetHandler"/>.</summary>
internal sealed class PartOfSpeechDefaultInflectionClassClearHandler : IOperationHandler
{
    internal static readonly PartOfSpeechDefaultInflectionClassClearHandler Instance = new();
    private PartOfSpeechDefaultInflectionClassClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass}' requires 'after'.");
        }

        PartOfSpeechDefaultInflectionClassClearPayload.Parse(after);

        var (id, partOfSpeech) = TargetResolution.Resolve<IPartOfSpeech>(cache, operation, PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(partOfSpeech.DefaultInflectionClassRA);
        PartOfSpeechDefaultInflectionClassClearLowering.Apply(partOfSpeech);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(partOfSpeech.DefaultInflectionClassRA);

        return new ExpectedEffect(id, SnapshotFields.PartOfSpeechDefaultInflectionClass, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, partOfSpeech) = TargetResolution.Resolve<IPartOfSpeech>(cache, operation, PartOfSpeechDefaultInflectionClassOperationKinds.ClearDefaultInflectionClass);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(partOfSpeech.DefaultInflectionClassRA);
        return new ExpectedEffect(id, SnapshotFields.PartOfSpeechDefaultInflectionClass, current, current);
    }
}
