// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhCode.Representation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhCode.Representation</c> operation kinds.</summary>
public static class PhCodeRepresentationOperationKinds
{
    public const string SetRepresentation = "grammar/phCode/setRepresentation";
    public const string ClearRepresentation = "grammar/phCode/clearRepresentation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetRepresentation);
        OperationKindRegistry.Register(ClearRepresentation);
        OperationHandlerRegistry.Register(SetRepresentation, PhCodeRepresentationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearRepresentation, PhCodeRepresentationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhCodeRepresentationOperationKinds.SetRepresentation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class PhCodeRepresentationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhCodeRepresentationOperationKinds.SetRepresentation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhCodeRepresentationOperationKinds.SetRepresentation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", PhCodeRepresentationOperationKinds.SetRepresentation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", PhCodeRepresentationOperationKinds.SetRepresentation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhCodeRepresentationOperationKinds.ClearRepresentation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class PhCodeRepresentationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhCodeRepresentationOperationKinds.ClearRepresentation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhCodeRepresentationOperationKinds.ClearRepresentation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", PhCodeRepresentationOperationKinds.ClearRepresentation);
    }
}

/// <summary>Lowers <see cref="PhCodeRepresentationOperationKinds.SetRepresentation"/>: sets one
/// writing-system alternative of <c>phCode.Representation</c>.</summary>
public static class PhCodeRepresentationSetLowering
{
    public static void Apply(LcmCache cache, IPhCode phCode, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, phCode.Representation, writingSystemTag, text, PhCodeRepresentationOperationKinds.SetRepresentation);
}

/// <summary>Lowers <see cref="PhCodeRepresentationOperationKinds.ClearRepresentation"/>: clears one
/// writing-system alternative of <c>phCode.Representation</c>.</summary>
public static class PhCodeRepresentationClearLowering
{
    public static void Apply(LcmCache cache, IPhCode phCode, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, phCode.Representation, writingSystemTag, PhCodeRepresentationOperationKinds.ClearRepresentation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhCodeRepresentationOperationKinds.SetRepresentation"/> operation.</summary>
internal sealed class PhCodeRepresentationSetHandler : IOperationHandler
{
    internal static readonly PhCodeRepresentationSetHandler Instance = new();
    private PhCodeRepresentationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhCodeRepresentationOperationKinds.SetRepresentation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhCodeRepresentationOperationKinds.SetRepresentation}' requires 'after'.");
        }

        var (writingSystemTag, text) = PhCodeRepresentationSetPayload.Parse(after);

        var (id, phCode) = TargetResolution.Resolve<IPhCode>(cache, operation, PhCodeRepresentationOperationKinds.SetRepresentation);
        touchedTargets.Add(id);

        var before = ReadField(cache, phCode);
        PhCodeRepresentationSetLowering.Apply(cache, phCode, writingSystemTag, text);
        var afterValue = ReadField(cache, phCode);

        return new ExpectedEffect(id, SnapshotFields.PhCodeRepresentation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phCode) = TargetResolution.Resolve<IPhCode>(cache, operation, PhCodeRepresentationOperationKinds.SetRepresentation);
        var current = ReadField(cache, phCode);
        return new ExpectedEffect(id, SnapshotFields.PhCodeRepresentation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhCode phCode) =>
        PhCodeSnapshotter.Snapshot(cache, phCode).AlternativesFields
            .TryGetValue(SnapshotFields.PhCodeRepresentation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhCodeRepresentationOperationKinds.ClearRepresentation"/> counterpart to
/// <see cref="PhCodeRepresentationSetHandler"/>.</summary>
internal sealed class PhCodeRepresentationClearHandler : IOperationHandler
{
    internal static readonly PhCodeRepresentationClearHandler Instance = new();
    private PhCodeRepresentationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhCodeRepresentationOperationKinds.ClearRepresentation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhCodeRepresentationOperationKinds.ClearRepresentation}' requires 'after'.");
        }

        var writingSystemTag = PhCodeRepresentationClearPayload.Parse(after);

        var (id, phCode) = TargetResolution.Resolve<IPhCode>(cache, operation, PhCodeRepresentationOperationKinds.ClearRepresentation);
        touchedTargets.Add(id);

        var before = ReadField(cache, phCode);
        PhCodeRepresentationClearLowering.Apply(cache, phCode, writingSystemTag);
        var afterValue = ReadField(cache, phCode);

        return new ExpectedEffect(id, SnapshotFields.PhCodeRepresentation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phCode) = TargetResolution.Resolve<IPhCode>(cache, operation, PhCodeRepresentationOperationKinds.ClearRepresentation);
        var current = ReadField(cache, phCode);
        return new ExpectedEffect(id, SnapshotFields.PhCodeRepresentation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhCode phCode) =>
        PhCodeSnapshotter.Snapshot(cache, phCode).AlternativesFields
            .TryGetValue(SnapshotFields.PhCodeRepresentation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
