// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhFeatureConstraint.Feature (rel/atomic FsFeatDefn, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhFeatureConstraint.Feature</c> operation kinds.</summary>
public static class PhFeatureConstraintFeatureOperationKinds
{
    public const string SetFeature = "grammar/phFeatureConstraint/setFeature";
    public const string ClearFeature = "grammar/phFeatureConstraint/clearFeature";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetFeature);
        OperationKindRegistry.Register(ClearFeature);
        OperationHandlerRegistry.Register(SetFeature, PhFeatureConstraintFeatureSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearFeature, PhFeatureConstraintFeatureClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhFeatureConstraintFeatureOperationKinds.SetFeature"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhFeatureConstraintFeatureSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhFeatureConstraintFeatureOperationKinds.SetFeature);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhFeatureConstraintFeatureOperationKinds.SetFeature);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", PhFeatureConstraintFeatureOperationKinds.SetFeature);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhFeatureConstraintFeatureOperationKinds.ClearFeature"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class PhFeatureConstraintFeatureClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhFeatureConstraintFeatureOperationKinds.ClearFeature);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhFeatureConstraintFeatureOperationKinds.ClearFeature);
    }
}

/// <summary>Lowers <see cref="PhFeatureConstraintFeatureOperationKinds.SetFeature"/>: resolves the
/// referenced IFsFeatDefn and assigns it to <c>phFeatureConstraint.FeatureRA</c>.</summary>
public static class PhFeatureConstraintFeatureSetLowering
{
    public static void Apply(LcmCache cache, IPhFeatureConstraint phFeatureConstraint, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IFsFeatDefn>(
            cache, value => phFeatureConstraint.FeatureRA = value, refId, PhFeatureConstraintFeatureOperationKinds.SetFeature);
}

/// <summary>Lowers <see cref="PhFeatureConstraintFeatureOperationKinds.ClearFeature"/>: detaches
/// <c>phFeatureConstraint.FeatureRA</c>.</summary>
public static class PhFeatureConstraintFeatureClearLowering
{
    public static void Apply(IPhFeatureConstraint phFeatureConstraint) =>
        ReferenceFieldLowering.ApplyClear<IFsFeatDefn>(value => phFeatureConstraint.FeatureRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhFeatureConstraintFeatureOperationKinds.SetFeature"/> operation.</summary>
internal sealed class PhFeatureConstraintFeatureSetHandler : IOperationHandler
{
    internal static readonly PhFeatureConstraintFeatureSetHandler Instance = new();
    private PhFeatureConstraintFeatureSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhFeatureConstraintFeatureOperationKinds.SetFeature}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhFeatureConstraintFeatureOperationKinds.SetFeature}' requires 'after'.");
        }

        var refId = PhFeatureConstraintFeatureSetPayload.Parse(after);

        var (id, phFeatureConstraint) = TargetResolution.Resolve<IPhFeatureConstraint>(cache, operation, PhFeatureConstraintFeatureOperationKinds.SetFeature);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(phFeatureConstraint.FeatureRA);
        PhFeatureConstraintFeatureSetLowering.Apply(cache, phFeatureConstraint, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(phFeatureConstraint.FeatureRA);

        return new ExpectedEffect(id, SnapshotFields.PhFeatureConstraintFeature, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phFeatureConstraint) = TargetResolution.Resolve<IPhFeatureConstraint>(cache, operation, PhFeatureConstraintFeatureOperationKinds.SetFeature);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(phFeatureConstraint.FeatureRA);
        return new ExpectedEffect(id, SnapshotFields.PhFeatureConstraintFeature, current, current);
    }
}

/// <summary>The <see cref="PhFeatureConstraintFeatureOperationKinds.ClearFeature"/> counterpart to
/// <see cref="PhFeatureConstraintFeatureSetHandler"/>.</summary>
internal sealed class PhFeatureConstraintFeatureClearHandler : IOperationHandler
{
    internal static readonly PhFeatureConstraintFeatureClearHandler Instance = new();
    private PhFeatureConstraintFeatureClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhFeatureConstraintFeatureOperationKinds.ClearFeature}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhFeatureConstraintFeatureOperationKinds.ClearFeature}' requires 'after'.");
        }

        PhFeatureConstraintFeatureClearPayload.Parse(after);

        var (id, phFeatureConstraint) = TargetResolution.Resolve<IPhFeatureConstraint>(cache, operation, PhFeatureConstraintFeatureOperationKinds.ClearFeature);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(phFeatureConstraint.FeatureRA);
        PhFeatureConstraintFeatureClearLowering.Apply(phFeatureConstraint);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(phFeatureConstraint.FeatureRA);

        return new ExpectedEffect(id, SnapshotFields.PhFeatureConstraintFeature, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phFeatureConstraint) = TargetResolution.Resolve<IPhFeatureConstraint>(cache, operation, PhFeatureConstraintFeatureOperationKinds.ClearFeature);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(phFeatureConstraint.FeatureRA);
        return new ExpectedEffect(id, SnapshotFields.PhFeatureConstraintFeature, current, current);
    }
}
