// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhIterationContext.Member (rel/atomic PhPhonContext, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhIterationContext.Member</c> operation kinds.</summary>
public static class PhIterationContextMemberOperationKinds
{
    public const string SetMember = "grammar/phIterationContext/setMember";
    public const string ClearMember = "grammar/phIterationContext/clearMember";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetMember);
        OperationKindRegistry.Register(ClearMember);
        OperationHandlerRegistry.Register(SetMember, PhIterationContextMemberSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearMember, PhIterationContextMemberClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhIterationContextMemberOperationKinds.SetMember"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhIterationContextMemberSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhIterationContextMemberOperationKinds.SetMember);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhIterationContextMemberOperationKinds.SetMember);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", PhIterationContextMemberOperationKinds.SetMember);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhIterationContextMemberOperationKinds.ClearMember"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class PhIterationContextMemberClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhIterationContextMemberOperationKinds.ClearMember);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhIterationContextMemberOperationKinds.ClearMember);
    }
}

/// <summary>Lowers <see cref="PhIterationContextMemberOperationKinds.SetMember"/>: resolves the
/// referenced IPhPhonContext and assigns it to <c>phIterationContext.MemberRA</c>.</summary>
public static class PhIterationContextMemberSetLowering
{
    public static void Apply(LcmCache cache, IPhIterationContext phIterationContext, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IPhPhonContext>(
            cache, value => phIterationContext.MemberRA = value, refId, PhIterationContextMemberOperationKinds.SetMember);
}

/// <summary>Lowers <see cref="PhIterationContextMemberOperationKinds.ClearMember"/>: detaches
/// <c>phIterationContext.MemberRA</c>.</summary>
public static class PhIterationContextMemberClearLowering
{
    public static void Apply(IPhIterationContext phIterationContext) =>
        ReferenceFieldLowering.ApplyClear<IPhPhonContext>(value => phIterationContext.MemberRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhIterationContextMemberOperationKinds.SetMember"/> operation.</summary>
internal sealed class PhIterationContextMemberSetHandler : IOperationHandler
{
    internal static readonly PhIterationContextMemberSetHandler Instance = new();
    private PhIterationContextMemberSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhIterationContextMemberOperationKinds.SetMember}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhIterationContextMemberOperationKinds.SetMember}' requires 'after'.");
        }

        var refId = PhIterationContextMemberSetPayload.Parse(after);

        var (id, phIterationContext) = TargetResolution.Resolve<IPhIterationContext>(cache, operation, PhIterationContextMemberOperationKinds.SetMember);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(phIterationContext.MemberRA);
        PhIterationContextMemberSetLowering.Apply(cache, phIterationContext, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(phIterationContext.MemberRA);

        return new ExpectedEffect(id, SnapshotFields.PhIterationContextMember, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phIterationContext) = TargetResolution.Resolve<IPhIterationContext>(cache, operation, PhIterationContextMemberOperationKinds.SetMember);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(phIterationContext.MemberRA);
        return new ExpectedEffect(id, SnapshotFields.PhIterationContextMember, current, current);
    }
}

/// <summary>The <see cref="PhIterationContextMemberOperationKinds.ClearMember"/> counterpart to
/// <see cref="PhIterationContextMemberSetHandler"/>.</summary>
internal sealed class PhIterationContextMemberClearHandler : IOperationHandler
{
    internal static readonly PhIterationContextMemberClearHandler Instance = new();
    private PhIterationContextMemberClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhIterationContextMemberOperationKinds.ClearMember}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhIterationContextMemberOperationKinds.ClearMember}' requires 'after'.");
        }

        PhIterationContextMemberClearPayload.Parse(after);

        var (id, phIterationContext) = TargetResolution.Resolve<IPhIterationContext>(cache, operation, PhIterationContextMemberOperationKinds.ClearMember);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(phIterationContext.MemberRA);
        PhIterationContextMemberClearLowering.Apply(phIterationContext);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(phIterationContext.MemberRA);

        return new ExpectedEffect(id, SnapshotFields.PhIterationContextMember, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phIterationContext) = TargetResolution.Resolve<IPhIterationContext>(cache, operation, PhIterationContextMemberOperationKinds.ClearMember);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(phIterationContext.MemberRA);
        return new ExpectedEffect(id, SnapshotFields.PhIterationContextMember, current, current);
    }
}
