// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhNaturalClass.Abbreviation (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhNaturalClass.Abbreviation</c> operation kinds.</summary>
public static class PhNaturalClassAbbreviationOperationKinds
{
    public const string SetAbbreviation = "grammar/phNaturalClass/setAbbreviation";
    public const string ClearAbbreviation = "grammar/phNaturalClass/clearAbbreviation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetAbbreviation);
        OperationKindRegistry.Register(ClearAbbreviation);
        OperationHandlerRegistry.Register(SetAbbreviation, PhNaturalClassAbbreviationSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearAbbreviation, PhNaturalClassAbbreviationClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhNaturalClassAbbreviationOperationKinds.SetAbbreviation"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class PhNaturalClassAbbreviationSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhNaturalClassAbbreviationOperationKinds.SetAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhNaturalClassAbbreviationOperationKinds.SetAbbreviation);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", PhNaturalClassAbbreviationOperationKinds.SetAbbreviation);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", PhNaturalClassAbbreviationOperationKinds.SetAbbreviation);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class PhNaturalClassAbbreviationClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation);
    }
}

/// <summary>Lowers <see cref="PhNaturalClassAbbreviationOperationKinds.SetAbbreviation"/>: sets one
/// writing-system alternative of <c>phNaturalClass.Abbreviation</c>.</summary>
public static class PhNaturalClassAbbreviationSetLowering
{
    public static void Apply(LcmCache cache, IPhNaturalClass phNaturalClass, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, phNaturalClass.Abbreviation, writingSystemTag, text, PhNaturalClassAbbreviationOperationKinds.SetAbbreviation);
}

/// <summary>Lowers <see cref="PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation"/>: clears one
/// writing-system alternative of <c>phNaturalClass.Abbreviation</c>.</summary>
public static class PhNaturalClassAbbreviationClearLowering
{
    public static void Apply(LcmCache cache, IPhNaturalClass phNaturalClass, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, phNaturalClass.Abbreviation, writingSystemTag, PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhNaturalClassAbbreviationOperationKinds.SetAbbreviation"/> operation.</summary>
internal sealed class PhNaturalClassAbbreviationSetHandler : IOperationHandler
{
    internal static readonly PhNaturalClassAbbreviationSetHandler Instance = new();
    private PhNaturalClassAbbreviationSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassAbbreviationOperationKinds.SetAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassAbbreviationOperationKinds.SetAbbreviation}' requires 'after'.");
        }

        var (writingSystemTag, text) = PhNaturalClassAbbreviationSetPayload.Parse(after);

        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassAbbreviationOperationKinds.SetAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, phNaturalClass);
        PhNaturalClassAbbreviationSetLowering.Apply(cache, phNaturalClass, writingSystemTag, text);
        var afterValue = ReadField(cache, phNaturalClass);

        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassAbbreviationOperationKinds.SetAbbreviation);
        var current = ReadField(cache, phNaturalClass);
        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhNaturalClass phNaturalClass) =>
        PhNaturalClassSnapshotter.Snapshot(cache, phNaturalClass).AlternativesFields
            .TryGetValue(SnapshotFields.PhNaturalClassAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation"/> counterpart to
/// <see cref="PhNaturalClassAbbreviationSetHandler"/>.</summary>
internal sealed class PhNaturalClassAbbreviationClearHandler : IOperationHandler
{
    internal static readonly PhNaturalClassAbbreviationClearHandler Instance = new();
    private PhNaturalClassAbbreviationClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation}' requires 'after'.");
        }

        var writingSystemTag = PhNaturalClassAbbreviationClearPayload.Parse(after);

        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation);
        touchedTargets.Add(id);

        var before = ReadField(cache, phNaturalClass);
        PhNaturalClassAbbreviationClearLowering.Apply(cache, phNaturalClass, writingSystemTag);
        var afterValue = ReadField(cache, phNaturalClass);

        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassAbbreviation, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassAbbreviationOperationKinds.ClearAbbreviation);
        var current = ReadField(cache, phNaturalClass);
        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassAbbreviation, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhNaturalClass phNaturalClass) =>
        PhNaturalClassSnapshotter.Snapshot(cache, phNaturalClass).AlternativesFields
            .TryGetValue(SnapshotFields.PhNaturalClassAbbreviation, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
