// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhNCSegments.Segments (rel/col PhPhoneme, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhNCSegments.Segments</c> operation kinds.</summary>
public static class PhNCSegmentsSegmentsOperationKinds
{
    public const string AddRefSegments = "grammar/phNCSegments/addRefSegments";
    public const string RemoveRefSegments = "grammar/phNCSegments/removeRefSegments";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefSegments);
        OperationKindRegistry.Register(RemoveRefSegments);
        OperationHandlerRegistry.Register(AddRefSegments, PhNCSegmentsSegmentsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefSegments, PhNCSegmentsSegmentsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="PhNCSegmentsSegmentsOperationKinds.AddRefSegments"/>
/// and <see cref="PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhNCSegmentsSegmentsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="PhNCSegmentsSegmentsOperationKinds.AddRefSegments"/>: resolves the
/// referenced IPhPhoneme and adds it to <c>phNCSegments.SegmentsRC</c> (a no-op if already
/// present).</summary>
public static class PhNCSegmentsSegmentsAddRefLowering
{
    public static void Apply(LcmCache cache, IPhNCSegments phNCSegments, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhPhoneme>(
            cache, phNCSegments.SegmentsRC, memberId, PhNCSegmentsSegmentsOperationKinds.AddRefSegments);
}

/// <summary>Lowers <see cref="PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments"/>: resolves the
/// referenced IPhPhoneme and removes it from <c>phNCSegments.SegmentsRC</c> (a no-op if
/// absent).</summary>
public static class PhNCSegmentsSegmentsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IPhNCSegments phNCSegments, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhPhoneme>(
            cache, phNCSegments.SegmentsRC, memberId, PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhNCSegmentsSegmentsOperationKinds.AddRefSegments"/> operation.</summary>
internal sealed class PhNCSegmentsSegmentsAddRefHandler : IOperationHandler
{
    internal static readonly PhNCSegmentsSegmentsAddRefHandler Instance = new();
    private PhNCSegmentsSegmentsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNCSegmentsSegmentsOperationKinds.AddRefSegments}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNCSegmentsSegmentsOperationKinds.AddRefSegments}' requires 'after'.");
        }

        var memberId = PhNCSegmentsSegmentsMemberPayload.Parse(after, PhNCSegmentsSegmentsOperationKinds.AddRefSegments);

        var (id, phNCSegments) = TargetResolution.Resolve<IPhNCSegments>(cache, operation, PhNCSegmentsSegmentsOperationKinds.AddRefSegments);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phNCSegments.SegmentsRC);
        PhNCSegmentsSegmentsAddRefLowering.Apply(cache, phNCSegments, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phNCSegments.SegmentsRC);

        return new ExpectedEffect(id, SnapshotFields.PhNCSegmentsSegments, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phNCSegments) = TargetResolution.Resolve<IPhNCSegments>(cache, operation, PhNCSegmentsSegmentsOperationKinds.AddRefSegments);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phNCSegments.SegmentsRC);
        return new ExpectedEffect(id, SnapshotFields.PhNCSegmentsSegments, current, current);
    }
}

/// <summary>The <see cref="PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments"/> counterpart to
/// <see cref="PhNCSegmentsSegmentsAddRefHandler"/>.</summary>
internal sealed class PhNCSegmentsSegmentsRemoveRefHandler : IOperationHandler
{
    internal static readonly PhNCSegmentsSegmentsRemoveRefHandler Instance = new();
    private PhNCSegmentsSegmentsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments}' requires 'after'.");
        }

        var memberId = PhNCSegmentsSegmentsMemberPayload.Parse(after, PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments);

        var (id, phNCSegments) = TargetResolution.Resolve<IPhNCSegments>(cache, operation, PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phNCSegments.SegmentsRC);
        PhNCSegmentsSegmentsRemoveRefLowering.Apply(cache, phNCSegments, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phNCSegments.SegmentsRC);

        return new ExpectedEffect(id, SnapshotFields.PhNCSegmentsSegments, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phNCSegments) = TargetResolution.Resolve<IPhNCSegments>(cache, operation, PhNCSegmentsSegmentsOperationKinds.RemoveRefSegments);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phNCSegments.SegmentsRC);
        return new ExpectedEffect(id, SnapshotFields.PhNCSegmentsSegments, current, current);
    }
}
