// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSegRuleRHS.ReqRuleFeats (rel/col PhPhonRuleFeat, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSegRuleRHS.ReqRuleFeats</c> operation kinds.</summary>
public static class PhSegRuleRHSReqRuleFeatsOperationKinds
{
    public const string AddRefReqRuleFeats = "grammar/phSegRuleRHS/addRefReqRuleFeats";
    public const string RemoveRefReqRuleFeats = "grammar/phSegRuleRHS/removeRefReqRuleFeats";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefReqRuleFeats);
        OperationKindRegistry.Register(RemoveRefReqRuleFeats);
        OperationHandlerRegistry.Register(AddRefReqRuleFeats, PhSegRuleRHSReqRuleFeatsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefReqRuleFeats, PhSegRuleRHSReqRuleFeatsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats"/>
/// and <see cref="PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhSegRuleRHSReqRuleFeatsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats"/>: resolves the
/// referenced IPhPhonRuleFeat and adds it to <c>phSegRuleRHS.ReqRuleFeatsRC</c> (a no-op if already
/// present).</summary>
public static class PhSegRuleRHSReqRuleFeatsAddRefLowering
{
    public static void Apply(LcmCache cache, IPhSegRuleRHS phSegRuleRHS, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhPhonRuleFeat>(
            cache, phSegRuleRHS.ReqRuleFeatsRC, memberId, PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats);
}

/// <summary>Lowers <see cref="PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats"/>: resolves the
/// referenced IPhPhonRuleFeat and removes it from <c>phSegRuleRHS.ReqRuleFeatsRC</c> (a no-op if
/// absent).</summary>
public static class PhSegRuleRHSReqRuleFeatsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IPhSegRuleRHS phSegRuleRHS, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhPhonRuleFeat>(
            cache, phSegRuleRHS.ReqRuleFeatsRC, memberId, PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats"/> operation.</summary>
internal sealed class PhSegRuleRHSReqRuleFeatsAddRefHandler : IOperationHandler
{
    internal static readonly PhSegRuleRHSReqRuleFeatsAddRefHandler Instance = new();
    private PhSegRuleRHSReqRuleFeatsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats}' requires 'after'.");
        }

        var memberId = PhSegRuleRHSReqRuleFeatsMemberPayload.Parse(after, PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats);

        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.ReqRuleFeatsRC);
        PhSegRuleRHSReqRuleFeatsAddRefLowering.Apply(cache, phSegRuleRHS, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.ReqRuleFeatsRC);

        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSReqRuleFeats, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSReqRuleFeatsOperationKinds.AddRefReqRuleFeats);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.ReqRuleFeatsRC);
        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSReqRuleFeats, current, current);
    }
}

/// <summary>The <see cref="PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats"/> counterpart to
/// <see cref="PhSegRuleRHSReqRuleFeatsAddRefHandler"/>.</summary>
internal sealed class PhSegRuleRHSReqRuleFeatsRemoveRefHandler : IOperationHandler
{
    internal static readonly PhSegRuleRHSReqRuleFeatsRemoveRefHandler Instance = new();
    private PhSegRuleRHSReqRuleFeatsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats}' requires 'after'.");
        }

        var memberId = PhSegRuleRHSReqRuleFeatsMemberPayload.Parse(after, PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats);

        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.ReqRuleFeatsRC);
        PhSegRuleRHSReqRuleFeatsRemoveRefLowering.Apply(cache, phSegRuleRHS, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.ReqRuleFeatsRC);

        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSReqRuleFeats, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSReqRuleFeatsOperationKinds.RemoveRefReqRuleFeats);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.ReqRuleFeatsRC);
        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSReqRuleFeats, current, current);
    }
}
