// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSequenceContext.Members (rel/seq PhPhonContext, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSequenceContext.Members</c> operation kinds.</summary>
public static class PhSequenceContextMembersOperationKinds
{
    public const string AddRefMembers = "grammar/phSequenceContext/addRefMembers";
    public const string RemoveRefMembers = "grammar/phSequenceContext/removeRefMembers";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefMembers);
        OperationKindRegistry.Register(RemoveRefMembers);
        OperationHandlerRegistry.Register(AddRefMembers, PhSequenceContextMembersAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefMembers, PhSequenceContextMembersRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="PhSequenceContextMembersOperationKinds.AddRefMembers"/>
/// and <see cref="PhSequenceContextMembersOperationKinds.RemoveRefMembers"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhSequenceContextMembersMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="PhSequenceContextMembersOperationKinds.AddRefMembers"/>: resolves the
/// referenced IPhPhonContext and adds it to <c>phSequenceContext.MembersRS</c> (a no-op if already
/// present).</summary>
public static class PhSequenceContextMembersAddRefLowering
{
    public static void Apply(LcmCache cache, IPhSequenceContext phSequenceContext, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhPhonContext>(
            cache, phSequenceContext.MembersRS, memberId, PhSequenceContextMembersOperationKinds.AddRefMembers);
}

/// <summary>Lowers <see cref="PhSequenceContextMembersOperationKinds.RemoveRefMembers"/>: resolves the
/// referenced IPhPhonContext and removes it from <c>phSequenceContext.MembersRS</c> (a no-op if
/// absent).</summary>
public static class PhSequenceContextMembersRemoveRefLowering
{
    public static void Apply(LcmCache cache, IPhSequenceContext phSequenceContext, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhPhonContext>(
            cache, phSequenceContext.MembersRS, memberId, PhSequenceContextMembersOperationKinds.RemoveRefMembers);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSequenceContextMembersOperationKinds.AddRefMembers"/> operation.</summary>
internal sealed class PhSequenceContextMembersAddRefHandler : IOperationHandler
{
    internal static readonly PhSequenceContextMembersAddRefHandler Instance = new();
    private PhSequenceContextMembersAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSequenceContextMembersOperationKinds.AddRefMembers}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSequenceContextMembersOperationKinds.AddRefMembers}' requires 'after'.");
        }

        var memberId = PhSequenceContextMembersMemberPayload.Parse(after, PhSequenceContextMembersOperationKinds.AddRefMembers);

        var (id, phSequenceContext) = TargetResolution.Resolve<IPhSequenceContext>(cache, operation, PhSequenceContextMembersOperationKinds.AddRefMembers);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSequenceContext.MembersRS);
        PhSequenceContextMembersAddRefLowering.Apply(cache, phSequenceContext, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSequenceContext.MembersRS);

        return new ExpectedEffect(id, SnapshotFields.PhSequenceContextMembers, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSequenceContext) = TargetResolution.Resolve<IPhSequenceContext>(cache, operation, PhSequenceContextMembersOperationKinds.AddRefMembers);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSequenceContext.MembersRS);
        return new ExpectedEffect(id, SnapshotFields.PhSequenceContextMembers, current, current);
    }
}

/// <summary>The <see cref="PhSequenceContextMembersOperationKinds.RemoveRefMembers"/> counterpart to
/// <see cref="PhSequenceContextMembersAddRefHandler"/>.</summary>
internal sealed class PhSequenceContextMembersRemoveRefHandler : IOperationHandler
{
    internal static readonly PhSequenceContextMembersRemoveRefHandler Instance = new();
    private PhSequenceContextMembersRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSequenceContextMembersOperationKinds.RemoveRefMembers}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSequenceContextMembersOperationKinds.RemoveRefMembers}' requires 'after'.");
        }

        var memberId = PhSequenceContextMembersMemberPayload.Parse(after, PhSequenceContextMembersOperationKinds.RemoveRefMembers);

        var (id, phSequenceContext) = TargetResolution.Resolve<IPhSequenceContext>(cache, operation, PhSequenceContextMembersOperationKinds.RemoveRefMembers);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSequenceContext.MembersRS);
        PhSequenceContextMembersRemoveRefLowering.Apply(cache, phSequenceContext, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSequenceContext.MembersRS);

        return new ExpectedEffect(id, SnapshotFields.PhSequenceContextMembers, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSequenceContext) = TargetResolution.Resolve<IPhSequenceContext>(cache, operation, PhSequenceContextMembersOperationKinds.RemoveRefMembers);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSequenceContext.MembersRS);
        return new ExpectedEffect(id, SnapshotFields.PhSequenceContextMembers, current, current);
    }
}
