// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command (docs/plan-motif.md, MOT-4 slice 2).
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSegRuleRHS.InputPOSes (rel/col PartOfSpeech, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSegRuleRHS.InputPOSes</c> operation kinds.</summary>
public static class PhSegRuleRHSInputPOSesOperationKinds
{
    public const string AddRefInputPOSes = "grammar/phSegRuleRHS/addRefInputPOSes";
    public const string RemoveRefInputPOSes = "grammar/phSegRuleRHS/removeRefInputPOSes";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefInputPOSes);
        OperationKindRegistry.Register(RemoveRefInputPOSes);
        OperationHandlerRegistry.Register(AddRefInputPOSes, PhSegRuleRHSInputPOSesAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefInputPOSes, PhSegRuleRHSInputPOSesRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes"/>
/// and <see cref="PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhSegRuleRHSInputPOSesMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes"/>: resolves the
/// referenced IPartOfSpeech and adds it to <c>phSegRuleRHS.InputPOSesRC</c> (a no-op if already
/// present).</summary>
public static class PhSegRuleRHSInputPOSesAddRefLowering
{
    public static void Apply(LcmCache cache, IPhSegRuleRHS phSegRuleRHS, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPartOfSpeech>(
            cache, phSegRuleRHS.InputPOSesRC, memberId, PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes);
}

/// <summary>Lowers <see cref="PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes"/>: resolves the
/// referenced IPartOfSpeech and removes it from <c>phSegRuleRHS.InputPOSesRC</c> (a no-op if
/// absent).</summary>
public static class PhSegRuleRHSInputPOSesRemoveRefLowering
{
    public static void Apply(LcmCache cache, IPhSegRuleRHS phSegRuleRHS, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPartOfSpeech>(
            cache, phSegRuleRHS.InputPOSesRC, memberId, PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes"/> operation.</summary>
internal sealed class PhSegRuleRHSInputPOSesAddRefHandler : IOperationHandler
{
    internal static readonly PhSegRuleRHSInputPOSesAddRefHandler Instance = new();
    private PhSegRuleRHSInputPOSesAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes}' requires 'after'.");
        }

        var memberId = PhSegRuleRHSInputPOSesMemberPayload.Parse(after, PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes);

        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.InputPOSesRC);
        PhSegRuleRHSInputPOSesAddRefLowering.Apply(cache, phSegRuleRHS, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.InputPOSesRC);

        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSInputPOSes, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSInputPOSesOperationKinds.AddRefInputPOSes);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.InputPOSesRC);
        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSInputPOSes, current, current);
    }
}

/// <summary>The <see cref="PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes"/> counterpart to
/// <see cref="PhSegRuleRHSInputPOSesAddRefHandler"/>.</summary>
internal sealed class PhSegRuleRHSInputPOSesRemoveRefHandler : IOperationHandler
{
    internal static readonly PhSegRuleRHSInputPOSesRemoveRefHandler Instance = new();
    private PhSegRuleRHSInputPOSesRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes}' requires 'after'.");
        }

        var memberId = PhSegRuleRHSInputPOSesMemberPayload.Parse(after, PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes);

        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes);
        touchedTargets.Add(id);

        var before = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.InputPOSesRC);
        PhSegRuleRHSInputPOSesRemoveRefLowering.Apply(cache, phSegRuleRHS, memberId);
        var afterValue = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.InputPOSesRC);

        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSInputPOSes, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegRuleRHS) = TargetResolution.Resolve<IPhSegRuleRHS>(cache, operation, PhSegRuleRHSInputPOSesOperationKinds.RemoveRefInputPOSes);
        var current = ReferenceCollectionFieldSnapshotting.ReadAlternatives(phSegRuleRHS.InputPOSesRC);
        return new ExpectedEffect(id, SnapshotFields.PhSegRuleRHSInputPOSes, current, current);
    }
}
