// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSimpleContextBdry.FeatureStructure (rel/atomic PhBdryMarker, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSimpleContextBdry.FeatureStructure</c> operation kinds.</summary>
public static class PhSimpleContextBdryFeatureStructureOperationKinds
{
    public const string SetFeatureStructure = "grammar/phSimpleContextBdry/setFeatureStructure";
    public const string ClearFeatureStructure = "grammar/phSimpleContextBdry/clearFeatureStructure";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetFeatureStructure);
        OperationKindRegistry.Register(ClearFeatureStructure);
        OperationHandlerRegistry.Register(SetFeatureStructure, PhSimpleContextBdryFeatureStructureSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearFeatureStructure, PhSimpleContextBdryFeatureStructureClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhSimpleContextBdryFeatureStructureSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class PhSimpleContextBdryFeatureStructureClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure);
    }
}

/// <summary>Lowers <see cref="PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure"/>: resolves the
/// referenced IPhBdryMarker and assigns it to <c>phSimpleContextBdry.FeatureStructureRA</c>.</summary>
public static class PhSimpleContextBdryFeatureStructureSetLowering
{
    public static void Apply(LcmCache cache, IPhSimpleContextBdry phSimpleContextBdry, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IPhBdryMarker>(
            cache, value => phSimpleContextBdry.FeatureStructureRA = value, refId, PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure);
}

/// <summary>Lowers <see cref="PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure"/>: detaches
/// <c>phSimpleContextBdry.FeatureStructureRA</c>.</summary>
public static class PhSimpleContextBdryFeatureStructureClearLowering
{
    public static void Apply(IPhSimpleContextBdry phSimpleContextBdry) =>
        ReferenceFieldLowering.ApplyClear<IPhBdryMarker>(value => phSimpleContextBdry.FeatureStructureRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure"/> operation.</summary>
internal sealed class PhSimpleContextBdryFeatureStructureSetHandler : IOperationHandler
{
    internal static readonly PhSimpleContextBdryFeatureStructureSetHandler Instance = new();
    private PhSimpleContextBdryFeatureStructureSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure}' requires 'after'.");
        }

        var refId = PhSimpleContextBdryFeatureStructureSetPayload.Parse(after);

        var (id, phSimpleContextBdry) = TargetResolution.Resolve<IPhSimpleContextBdry>(cache, operation, PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(phSimpleContextBdry.FeatureStructureRA);
        PhSimpleContextBdryFeatureStructureSetLowering.Apply(cache, phSimpleContextBdry, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(phSimpleContextBdry.FeatureStructureRA);

        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextBdryFeatureStructure, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSimpleContextBdry) = TargetResolution.Resolve<IPhSimpleContextBdry>(cache, operation, PhSimpleContextBdryFeatureStructureOperationKinds.SetFeatureStructure);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(phSimpleContextBdry.FeatureStructureRA);
        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextBdryFeatureStructure, current, current);
    }
}

/// <summary>The <see cref="PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure"/> counterpart to
/// <see cref="PhSimpleContextBdryFeatureStructureSetHandler"/>.</summary>
internal sealed class PhSimpleContextBdryFeatureStructureClearHandler : IOperationHandler
{
    internal static readonly PhSimpleContextBdryFeatureStructureClearHandler Instance = new();
    private PhSimpleContextBdryFeatureStructureClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure}' requires 'after'.");
        }

        PhSimpleContextBdryFeatureStructureClearPayload.Parse(after);

        var (id, phSimpleContextBdry) = TargetResolution.Resolve<IPhSimpleContextBdry>(cache, operation, PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(phSimpleContextBdry.FeatureStructureRA);
        PhSimpleContextBdryFeatureStructureClearLowering.Apply(phSimpleContextBdry);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(phSimpleContextBdry.FeatureStructureRA);

        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextBdryFeatureStructure, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSimpleContextBdry) = TargetResolution.Resolve<IPhSimpleContextBdry>(cache, operation, PhSimpleContextBdryFeatureStructureOperationKinds.ClearFeatureStructure);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(phSimpleContextBdry.FeatureStructureRA);
        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextBdryFeatureStructure, current, current);
    }
}
